### ISSUE TITLE
Ravendb.Client ssl connection

### ISSUE THREAD

**Issue by lucascebertin** [ravendb/ravendb#10922]
Hi guys, I'm facing a SSL connection problem and couldn't try to figure this out, any hint or tip would be great.

Raven is exposed behind a https with a self signed certificate and a client certificate is needed to gain authenticated access.
I'm working with dotnet core 3.1 in a Manjaro.

I got the SSL cert this way:
```
openssl s_client -showcerts -verify 5 -connect raven_domain:443 < /dev/null
```

Copied the BEGIN/END part, trusted in my local CA store and tried a simples curl connection pointing to /studio/index.html.
My curl returns `{"Type":"InvalidAuth","Message":"This server requires client certificate for authentication, but none was provided by the client."}`
That's expected, the auth client certificate is not being passed anyway, so OK.

After some search about store trusting on dotnet core 3.1, found that now, for using Libcurl back, I should use these configs:
```csharp
AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
```
Then, tried to initialize my store and get statistics:
```csharp
var clientCertificate = new X509Certificate2("mycert.pfx");
var database = "MyDatabase";

using (var store = new DocumentStore()
{
    Certificate = clientCertificate,
    Database = database,
    Urls = new[] {"https://raven_domain/"}
}.Initialize())
{
    store.Maintenance.ForDatabase(database).Send(new GetStatisticsOperation());
}
```

After that, got the following stacktrace:
```
Unhandled exception. System.AggregateException: Failed to retrieve database topology from all known nodes.
https://raven_domain -> An error occurred while sending the request. -> SSL peer certificate or SSH remote key was not OK (An error occurred while sending the request.)
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Raven.Client.Http.RequestExecutor.SendAsync[TResult](ServerNode chosenNode, RavenCommand`1 command, SessionInfo sessionInfo, HttpRequestMessage request, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 1093
   at Raven.Client.Http.RequestExecutor.SendRequestToServer[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, HttpRequestMessage request, String url, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 1037
   at Raven.Client.Http.RequestExecutor.SendRequestToServer[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, HttpRequestMessage request, String url, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 1060
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 892
   at Raven.Client.Http.RequestExecutor.UpdateTopologyAsync(UpdateTopologyParameters parameters) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 511
   at Raven.Client.Http.RequestExecutor.FirstTopologyUpdate(String[] initialUrls, Nullable`1 applicationIdentifier) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 728
   --- End of inner exception stack trace ---
   at Raven.Client.Http.RequestExecutor.ThrowExceptions(List`1 list) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 804
   at Raven.Client.Http.RequestExecutor.FirstTopologyUpdate(String[] initialUrls, Nullable`1 applicationIdentifier) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 781
   at Raven.Client.Http.RequestExecutor.WaitForTopologyUpdate(Task topologyUpdate) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 658
   at Raven.Client.Http.RequestExecutor.UnlikelyExecuteAsync[TResult](RavenCommand`1 command, JsonOperationContext context, Task topologyUpdate, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Http\RequestExecutor.cs:line 628
   at Raven.Client.Documents.Operations.MaintenanceOperationExecutor.SendAsync[TResult](IMaintenanceOperation`1 operation, CancellationToken token) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Documents\Operations\MaintenanceOperationExecutor.cs:line 62
   at Raven.Client.Util.AsyncHelpers.RunSync[T](Func`1 task) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Util\AsyncHelpers.cs:line 133
   at Raven.Client.Documents.Operations.MaintenanceOperationExecutor.Send[TResult](IMaintenanceOperation`1 operation) in C:\Builds\RavenDB-Stable-4.2\42046\src\Raven.Client\Documents\Operations\MaintenanceOperationExecutor.cs:line 43
   at AppPlayground.Program.Main(String[] args) in /home/lucasbertin/Projetos/OSS/dotnet-raven-certificates/AppPlayground/Program.cs:line 76
```

I got this thing working after add a custom RemoteCertificateValidationCallback and looking for my cert thumbprint, this looks a little bit hacky:
```csharp
RequestExecutor.RemoteCertificateValidationCallback += (message, cert, chain, sslPolicyErrors) => 
{
    if (sslPolicyErrors == SslPolicyErrors.None ||
        cert.GetCertHashString() == "MY_THUMB_HERE") return true;

    return false;
};
```

Any help would be really appreciated, don't know how to get this working without this manual check process.

Thanks :)

**Comment by ayende** [comment]
A) You can just use the Let's Encrypt mode, and all of this will Just Work.
B) What is it that you are trying to do? Use a self signed certificate in this context?

**Comment by lucascebertin** [comment]
The ravendb is reachable behind a VPN, it's a DEV environment, don't know if lets encrypt would be an option but I will pass that info to raven sysadmins.

Well, the HTTPS have a cert self signed and I received a client certificate for ravendb client initialization.

**Comment by ayende** [comment]
There is no issue with setting up with Let's Encrypt in VPN / local environment. See here: https://www.youtube.com/watch?v=K-2iZ_lJVag

If you want to use a self signed certificate for the RavenDB server, you need to either:

* Add the CA that signed the server cert to the trusted root.
* Change the `RemoteCertificateValidationCallback` to trust it explicit (either via the thumbprint or by checking who the signer is).

**Comment by lucascebertin** [comment]
Oh, thanks for the setup video.

Ok, CA trusted.
About RemoteCertificateValidationCallback, so, what I did here is OK?

```csharp
RequestExecutor.RemoteCertificateValidationCallback += (message, cert, chain, sslPolicyErrors) => 
{
    if (sslPolicyErrors == SslPolicyErrors.None ||
        cert.GetCertHashString() == "MY_THUMB_HERE") return true;

    return false;
};
```

Do you have any example of how to check the signer?

Thanks!

**Comment by ayende** [comment]
In `RemoteCertificateValidationCallback`, you can access the `chain` and see if any of the certificates there is trusted by you.
You can do that using either the `GetCertHashString()`, `Thumbprint` property or by checking the public key for the cert.

**Comment by ayende** [comment]
Note that this means that you won't be doing validation such as `ValidBefore`, CRL, etc.

**Comment by lucascebertin** [comment]
Oh, got it, I should look for any cert trusted in full chain and do other validations.
Well, ok, now I have a lot of information and can pick any one to move on.
Thanks for your help on it and can close this issue.
