### ISSUE TITLE
Document Refresh does not run after the specified time by @refresh flag when @flag contains FromClusterTransaction

### ISSUE THREAD

**Issue by bukefalos** [ravendb/ravendb#12179]
Document refresh fail on exception when document is saved in cluster wide transaction. I faced problem originally described on [stackoverflow]( https://stackoverflow.com/questions/67330275/ravendb-document-refresh-feature-does-not-run-at-nor-after-the-specified-time-b )

Problem spotted both on: 
- 5.1.7 docker image running on Windows 10
- 4.2.111 docker image running on Windows 10

I have checked out RavenDB git repository and ran `v5.1` branch locally. After saving same document I observed problem but with a different stacktrace:

```---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
FromClusterTransaction, expect change vector of length 1, 
---- Assert Long Message ----

   at Raven.Server.Documents.DocumentsStorage.FlagsProperlySet(DocumentFlags flags, String changeVector) in C:\sources\ravendb\src\Raven.Server\Documents\DocumentsStorage.cs:line 1950
   at Raven.Server.Documents.DocumentPutAction.PutDocument(DocumentsOperationContext context, String id, String expectedChangeVector, BlittableJsonReaderObject document, Nullable`1 lastModifiedTicks, String changeVector, DocumentFlags flags, NonPersistentDocumentFlags nonPersistentFlags) in C:\sources\ravendb\src\Raven.Server\Documents\DocumentPutAction.cs:line 189
   at Raven.Server.Documents.Expiration.ExpirationStorage.RefreshDocuments(DocumentsOperationContext context, Dictionary`2 expired, DateTime currentTime) in C:\sources\ravendb\src\Raven.Server\Documents\Expiration\ExpirationStorage.cs:line 293
   at Raven.Server.Documents.Expiration.ExpiredDocumentsCleaner.DeleteExpiredDocumentsCommand.ExecuteCmd(DocumentsOperationContext context) in C:\sources\ravendb\src\Raven.Server\Documents\Expiration\ExpiredDocumentsCleaner.cs:line 202
   at Raven.Server.Documents.TransactionOperationsMerger.MergedTransactionCommand.Execute(DocumentsOperationContext context, RecordingState recordingState) in C:\sources\ravendb\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 103
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 executedOps, DocumentsOperationContext context, Task previousOperation, DurationMeasurement& meter) in C:\sources\ravendb\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 909
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsOnce() in C:\sources\ravendb\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 517
   at Raven.Server.Documents.TransactionOperationsMerger.MergeOperationThreadProc() in C:\sources\ravendb\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 345
   at Raven.Server.Documents.TransactionOperationsMerger.<Start>b__20_0(Object x) in C:\sources\ravendb\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 75
   at Raven.Server.Utils.PoolOfThreads.PooledThread.DoWork() in C:\sources\ravendb\src\Raven.Server\Utils\PoolOfThreads.cs:line 216
   at Raven.Server.Utils.PoolOfThreads.PooledThread.Run() in C:\sources\ravendb\src\Raven.Server\Utils\PoolOfThreads.cs:line 186
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

looks like `changeVector` needs to be updated in `DocumentPutAction.PutDocument` otherwise will remain null and cause issue in this scenario. Side effect is that other documents might not be also refreshed

Mentioned in https://issues.hibernatingrhinos.com/issue/RavenDB-16710

**Comment by ayende** [comment]
Fix is here: https://github.com/ravendb/ravendb/pull/12180
