### ISSUE TITLE
Forbidden Access on /admin/debug/node/ping

### ISSUE THREAD

**Issue by farhadnowzari** [ravendb/ravendb#12345]
Hi,

We are encountering an issue.

We have installed ravendb on WindowsServer 2012 R2.
The installation was successful. We used a self-signed certificate since we don't have internet access on the server so Let's encrypt was not an option.
We used the generated auth certificate by raven and we successfully logged in into the ravendb dashboard.
But when creating the database it throws the following error:
```
The database 'TestDB' was created but is not accessible, because all of the nodes on which this database was supposed to reside on, threw an exception.
System.IO.InvalidDataException: The database 'TestDB' was created but is not accessible, because all of the nodes on which this database was supposed to reside on, threw an exception.
 ---> System.AggregateException: One or more errors occurred. (Forbidden access to @https://demo.local:4434,  does not have permission to access it or is unknown. Method: GET, Request: https://demo.local:4434/rachis/waitfor?index=24
{"Type":"InvalidAuth","Message":"This server requires client certificate for authentication, but none was provided by the client. Did you forget to install the certificate?\r\nYour certificate store may be cached by the browser. Create a new private browsing tab, which will not cache any certificates. (Ctrl+Shift+N in Chrome, Ctrl+Shift+P in Firefox)"})
 ---> Raven.Client.Exceptions.Security.AuthorizationException: Forbidden access to @https://demo.local:4434,  does not have permission to access it or is unknown. Method: GET, Request: https://demo.local:4434/rachis/waitfor?index=24
{"Type":"InvalidAuth","Message":"This server requires client certificate for authentication, but none was provided by the client. Did you forget to install the certificate?\r\nYour certificate store may be cached by the browser. Create a new private browsing tab, which will not cache any certificates. (Ctrl+Shift+N in Chrome, Ctrl+Shift+P in Firefox)"}
   at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Client\Http\RequestExecutor.cs:line 1437
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Client\Http\RequestExecutor.cs:line 901
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Client\Http\RequestExecutor.cs:line 901
   at Raven.Server.Web.RequestHandler.<>c__DisplayClass22_0.<<WaitForExecutionOnRelevantNodes>g__ExecuteTask|0>d.MoveNext() in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Web\RequestHandler.cs:line 242
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Raven.Server.Web.RequestHandler.WaitForExecutionOnRelevantNodes(JsonOperationContext context, String database, ClusterTopology clusterTopology, List`1 members, Int64 index) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Web\RequestHandler.cs:line 226
   at Raven.Server.Web.System.AdminDatabasesHandler.CreateDatabase(String name, DatabaseRecord databaseRecord, TransactionOperationContext context, Int32 replicationFactor, Nullable`1 index, String raftRequestId) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 463
   at Raven.Server.Web.System.AdminDatabasesHandler.Put() in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 333
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Routing\RequestRouter.cs:line 357
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\RavenServerStartup.cs:line 237
 
```
The database looks healthy and we can create documents for it from the dashboard and the only node which we are having looks healthy.

But with the error it seemed like there is something wrong, so we looked it up and found this link:
https://issues.hibernatingrhinos.com/issue/RavenDB-13904

Here it has mentioned that we check what does `/admin/debug/node/ping` returns.
well it exactly returns the same error as the shared one above.
We are using a `Community License`.

**Comment by ayende** [comment]
You have a proxy on the machine that does HTTPS termination? 
Basically, the server is unable to authenticate with itself, which usually means that there is something in the middle there.

**Comment by farhadnowzari** [comment]
There is no proxy.
The issue is that, there is no issue with it the error just happens.
but we could connect to the database with the auth cert (we are using Raven dependency injection library) and we could add/remove/modify documents from the code.
and as you can see the node looks pretty healthy.
![image](https://user-images.githubusercontent.com/57224511/121340611-1a299000-c920-11eb-9f47-0235ed6b17fe.png)

**Comment by ayende** [comment]
How are you running this instance?

**Comment by ayende** [comment]
I mean, K8s, container, etc?
