### ISSUE TITLE
Using Group as a property name referencing a document prevent RavenDB from including it

### ISSUE THREAD

**Issue by pmengal** [ravendb/ravendb#12473]
When a document contains a property named Group that references another document by its ID (in a different collection), the query parser is unable to understand what we want. Renaming the property to something else fixed the problem.

Raven.Server.Documents.Queries.Parser.QueryParser+ParseException: 1:67 Unable to understand include clause expression but got: Group
Query: 
from 'DriverSessions' where 'Group' = $p0 include Account,Circuit,Group
   at Raven.Server.Documents.Queries.Parser.QueryParser.ThrowParseException(String msg) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Queries\Parser\QueryParser.cs:line 2312
   at Raven.Server.Documents.Queries.Parser.QueryParser.IncludeClause() in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Queries\Parser\QueryParser.cs:line 1248
   at Raven.Server.Documents.Queries.Parser.QueryParser.TryParse(Query& query, String& message, QueryType queryType, Boolean recursive) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Queries\Parser\QueryParser.cs:line 178
   at Raven.Server.Documents.Queries.QueryMetadata.ParseQuery(String q, QueryType queryType, DocumentDatabase database) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Queries\QueryMetadata.cs:line 51
   at Raven.Server.Documents.Queries.IndexQueryServerSide.Create(HttpContext httpContext, BlittableJsonReaderObject json, QueryMetadataCache cache, RequestTimeTracker tracker, DocumentDatabase database, QueryType queryType) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Queries\IndexQueryServerSide.cs:line 147
   at Raven.Server.Documents.Handlers.QueriesHandler.GetIndexQuery(JsonOperationContext context, HttpMethod method, RequestTimeTracker tracker) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 202
   at Raven.Server.Documents.Handlers.QueriesHandler.Query(QueryOperationContext queryContext, OperationCancelToken token, RequestTimeTracker tracker, HttpMethod method, Boolean diagnostics) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 170
   at Raven.Server.Documents.Handlers.QueriesHandler.HandleQuery(HttpMethod httpMethod) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 88
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\Routing\RequestRouter.cs:line 357
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.1\51027\src\Raven.Server\RavenServerStartup.cs:line 237. Response: {"Url":"/databases/LapViz/queries?queryHash=12245220938589498094","Type":"Raven.Server.Documents.Queries.Parser.QueryParser+ParseException","Message":"1:67 Unable to understand include clause expression but got: Group\r\nQuery: \r\nfrom 'DriverSessions' where 'Group' = $p0 include Account,Circuit,Group","Error":"Raven.Server.Documents.Queries.Parser.QueryParser+ParseException: 1:67 Unable to understand include clause expression but got: Group\r\nQuery: \r\nfrom 'DriverSessions' where 'Group' = $p0 include Account,Circuit,Group\r\n   at Raven.Server.Documents.Queries.Parser.QueryParser.ThrowParseException(String msg) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Queries\\Parser\\QueryParser.cs:line 2312\r\n   at Raven.Server.Documents.Queries.Parser.QueryParser.IncludeClause() in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Queries\\Parser\\QueryParser.cs:line 1248\r\n   at Raven.Server.Documents.Queries.Parser.QueryParser.TryParse(Query& query, String& message, QueryType queryType, Boolean recursive) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Queries\\Parser\\QueryParser.cs:line 178\r\n   at Raven.Server.Documents.Queries.QueryMetadata.ParseQuery(String q, QueryType queryType, DocumentDatabase database) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Queries\\QueryMetadata.cs:line 51\r\n   at Raven.Server.Documents.Queries.IndexQueryServerSide.Create(HttpContext httpContext, BlittableJsonReaderObject json, QueryMetadataCache cache, RequestTimeTracker tracker, DocumentDatabase database, QueryType queryType) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Queries\\IndexQueryServerSide.cs:line 147\r\n   at Raven.Server.Documents.Handlers.QueriesHandler.GetIndexQuery(JsonOperationContext context, HttpMethod method, RequestTimeTracker tracker) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 202\r\n   at Raven.Server.Documents.Handlers.QueriesHandler.Query(QueryOperationContext queryContext, OperationCancelToken token, RequestTimeTracker tracker, HttpMethod method, Boolean diagnostics) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 170\r\n   at Raven.Server.Documents.Handlers.QueriesHandler.HandleQuery(HttpMethod httpMethod) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 88\r\n   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\Routing\\RequestRouter.cs:line 357\r\n   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\\Builds\\RavenDB-Stable-5.1\\51027\\src\\Raven.Server\\RavenServerStartup.cs:line 237"}

**Comment by ayende** [comment]
You need to escape the field:

`from 'DriverSessions' where 'Group' = $p0 include Account,Circuit,'Group'`



How are you generating this query? Manually or via the API?

**Comment by pmengal** [comment]
@ayende using the API: .Include(x => x.Group).

Renaming the property Group to anything else solves the problem

**Comment by ayende** [comment]
As workaround, I think you can use: `Include("'Group'")`, at any rate, we'll issue a fix

**Comment by grisha-kotler** [comment]
https://github.com/ravendb/ravendb/pull/12475
