### ISSUE TITLE
Secondary level Include with Projection fails

### ISSUE THREAD

**Issue by mjohnson0580** [ravendb/ravendb#12549]
Tested with v5.2.1

When executing the following query

```
var users = await session.Query<User, UserIndex>()
                                             .Include(u => u.Roles.Select(r => r.Role))
                                             .Select(u => new
                                             {
                                                 u.FirstName,
                                                 u.LastName,
                                                 Roles = u.Roles.Select(r => new { r.Role }).ToList()
                                             })
                                             .ToListAsync();
```

The following exception is being thrown

```
Raven.Client.Exceptions.InvalidQueryException : Raven.Client.Exceptions.InvalidQueryException: Unknown alias Roles[], but there are aliases specified in the query (u)
Query: from index 'UserIndex' as u select { FirstName : u.FirstName, LastName : u.LastName, Roles : u.Roles.map(function(r){return {Role:r.Role};}) } include 'Roles[].Role'
Parameters: {}
   at Raven.Server.Documents.Queries.QueryMetadata.ThrowUnknownAlias(String alias, BlittableJsonReaderObject parameters) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Queries\QueryMetadata.cs:line 1851
   at Raven.Server.Documents.Queries.QueryMetadata.<HandleQueryInclude>g__AddInclude|105_0(QueryExpression include, String path, List`1& listToAdd, <>c__DisplayClass105_0& ) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Queries\QueryMetadata.cs:line 458
   at Raven.Server.Documents.Queries.QueryMetadata.HandleQueryInclude(BlittableJsonReaderObject parameters)
   at Raven.Server.Documents.Queries.QueryMetadata.Build(BlittableJsonReaderObject parameters) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Queries\QueryMetadata.cs:line 359
   at Raven.Server.Documents.Queries.QueryMetadata..ctor(Query query, BlittableJsonReaderObject parameters, UInt64 cacheKey, Boolean addSpatialProperties) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Queries\QueryMetadata.cs:line 94
   at Raven.Server.Documents.Queries.QueryMetadata..ctor(String query, BlittableJsonReaderObject parameters, UInt64 cacheKey, Boolean addSpatialProperties, QueryType queryType, DocumentDatabase database) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Queries\QueryMetadata.cs:line 47
   at Raven.Server.Documents.Queries.IndexQueryServerSide.Create(HttpContext httpContext, BlittableJsonReaderObject json, QueryMetadataCache cache, RequestTimeTracker tracker, Boolean addSpatialProperties, DocumentDatabase database, QueryType queryType) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Queries\IndexQueryServerSide.cs:line 122
   at Raven.Server.Documents.Handlers.QueriesHandler.GetIndexQuery(JsonOperationContext context, HttpMethod method, RequestTimeTracker tracker) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 203
   at Raven.Server.Documents.Handlers.QueriesHandler.Query(QueryOperationContext queryContext, OperationCancelToken token, RequestTimeTracker tracker, HttpMethod method, Boolean diagnostics) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 116
   at Raven.Server.Documents.Handlers.QueriesHandler.HandleQuery(HttpMethod httpMethod) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 63
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Routing\RequestRouter.cs:line 344
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\RavenServerStartup.cs:line 174
   at Raven.Client.Exceptions.ExceptionDispatcher.<Throw>d__2.MoveNext() in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 119
```

**Comment by ppekrol** [comment]
Thank you, it looks like the include should be `u.Roles[].Role`. I've created an issue to handle this: https://issues.hibernatingrhinos.com/issue/RavenDB-17041

**Comment by shiranshalom** [comment]
@mjohnson0580 Can you please share your index definition and classes? We want to be sure that we're covering your scenario.
You can follow the PR in the following link:
https://github.com/ravendb/ravendb/pull/12583

**Comment by mjohnson0580** [comment]
Hi @shiranshalom,
Thanks for fixing this issue. Here are our index and classes:
```
public class UserIndex : AbstractIndexCreationTask<User>
{
    public UserIndex()
    {
        Map = users => from user in users
                       select new
                       {
                           user.Username,
                           user.EmployeeNo,
                           user.FirstName,
                           user.LastName,
                           user.Active,
                           user.Deleted
                       };
    }
}

public class User
{
    public User()
    {
        Roles = new List<UserRole>();
    }

    public string Id { get; set; }
    public string Username { get; set; }
    public string Password { get; set; }
    public string EmployeeNo { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string EmailAddress { get; set; }
    public string MobileNumber { get; set; }
    public bool Active { get; set; }
    public bool Deleted { get; set; }

    public List<UserRole> Roles { get; set; }
}

public class UserRole
{
    public string Id { get; set; }
    public string Role { get; set; } // Role document id
    public string RoleName { get; set; }
}

public class Role
{
    public string Id { get; set; }
    public string Name { get; set; }
}
```
