### ISSUE TITLE
Cannot append timeseries with too many values

### ISSUE THREAD

**Issue by AlexKrt** [ravendb/ravendb#12603]
I got the following exception.
  executing following statement
                    ISessionDocumentTimeSeries tsf = session.TimeSeriesFor(documentId, name);
                    if (trend.Readings != null)
                    {
                        tsf.Append(trend.TrendReadingTimeStamp, trend.Readings);
                    }

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'TimeSeriesValuesSegment can handle up to 32 values, but had: 9403')
   at Raven.Server.Documents.TimeSeries.TimeSeriesValuesSegment.ThrowValuesOutOfRange(Int32 numberOfValues) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TimeSeries\TimeSeriesValuesSegment.cs:line 785
   at Raven.Server.Documents.TimeSeries.TimeSeriesValuesSegment.Initialize(Int32 numberOfValues) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TimeSeries\TimeSeriesValuesSegment.cs:line 114
   at Raven.Server.Documents.TimeSeries.TimeSeriesStorage.TimeSeriesSegmentHolder.AppendToNewSegment(SingleResult item) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TimeSeries\TimeSeriesStorage.cs:line 1031
   at Raven.Server.Documents.TimeSeries.TimeSeriesStorage.AppendTimestamp(DocumentsOperationContext context, String documentId, String collection, String name, IEnumerable`1 toAppend, String changeVectorFromReplication, Boolean verifyName, Boolean addNewNameToMetadata) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TimeSeries\TimeSeriesStorage.cs:line 1243
   at Raven.Server.Documents.TimeSeries.TimeSeriesStorage.AppendTimestamp(DocumentsOperationContext context, String documentId, String collection, String name, IEnumerable`1 toAppend, String changeVectorFromReplication) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TimeSeries\TimeSeriesStorage.cs:line 1114
   at Raven.Server.Documents.Handlers.TimeSeriesHandler.ExecuteTimeSeriesBatchCommand.ExecuteCmd(DocumentsOperationContext context) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Handlers\TimeSeriesHandler.cs:line 866
   at Raven.Server.Documents.Handlers.BatchHandler.MergedBatchCommand.ExecuteCmd(DocumentsOperationContext context) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 1029
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 executedOps, DocumentsOperationContext context, Task previousOperation, DurationMeasurement& meter) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 909
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsOnce() in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 517
--- End of stack trace from previous location ---
   at Raven.Server.Documents.TransactionOperationsMerger.Enqueue(MergedTransactionCommand cmd) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 144
   at Raven.Server.Documents.Handlers.BatchHandler.BulkDocs() in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 142
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\Routing\RequestRouter.cs:line 356
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.2\52001\src\Raven.Server\RavenServerStartup.cs:line 239

**Comment by karmeli87** [comment]
Hi,

For a single timestamp it isn't supported to append more than 32 values and you have 9403 of them.

Can you elaborate on the `trend.Readings` why do they have so many values for a single timestamp?

**Comment by AlexKrt** [comment]
Ok, I am new to this and now I know that there are max 32 values per timestamp(is it documented?). I was actually trying to save the whole trend knowing the values interval is 2 seconds and initial timestamp is the start.
But doesn't that mean what for every timesttamp you can only have up to 32 trends? Besides you cannot name them accordingly like trend 1, trend 2 etc. Instead it is just Value#0, Value#1 - not convenient. Or is there a different way?
Thank you.

**Comment by ayende** [comment]
You can name them in the settings, but your situation looks like it calls for 9,403 separate timestamps, not multiple values at a single time.

Examples for multiple values at point in time: `lat/lng @ 12:00`

**Comment by karmeli87** [comment]
Why not to store it with the original timestamp? It will allow you easier querying / aggregation etc..
You can append as many entries as you like, only when call `SaveChanges` we issue a single request to the server to store those values.

Here is the relevant documentation about the value limitation: https://ravendb.net/docs/article-page/5.2/csharp/document-extensions/timeseries/overview#values

and you can name them :-)
Take a look at that https://ravendb.net/docs/article-page/5.2/csharp/document-extensions/timeseries/client-api/named-time-series-values#registering-a-time-series-type

You also can see how this looks like in the Company collection of the sample database (you can create a sample database in the live-test http://live-test.ravendb.net/)

**Comment by AlexKrt** [comment]
Ok, I did.
![image](https://user-images.githubusercontent.com/26931516/128343548-031dba21-9119-4e0e-a1e2-a740ac84bbae.png)
But still max 32 trends per every time point. Thanks G-d, I only have 14.
![image](https://user-images.githubusercontent.com/26931516/128343751-767e1de9-fd5b-4eee-bd7a-a58a9642c6ed.png)
BTW no Nans allowed?

**Comment by ayende** [comment]
What is it that you are storing?
And yes, NaN isn't a valid value.
