### ISSUE TITLE
Exception on Query with Highlighting/Explanation

### ISSUE THREAD

**Issue by oiBio** [ravendb/ravendb#13647]
I get the following exception when i run my (complex) query with included highlightings. Another factory might be, that i runs lazily
It only throws in specific search terms like "ahmed" or "pat". And only in one specific database and i cant reproduce this with another dataset. So my query works 99.9% of the time, and only in this specific dataset it throws the error.

```
[2022-02-15T14:27:00.204Z] Error: System.InvalidOperationException: Got an error from server, status code: 500
{"Url":"/databases/Artemis.Dahmen/queries?queryHash=6147327430259935937","Type":"System.ArgumentOutOfRangeException","Message":"StartIndex cannot be less than zero. (Parameter 'startIndex')","Error":"System.ArgumentOutOfRangeException: StartIndex cannot be less than zero. (Parameter 'startIndex')\n   at System.String.Substring(Int32 startIndex, Int32 length)\n   at Lucene.Net.Search.Vectorhighlight.BaseFragmentsBuilder.MakeFragment(WeightedFragInfo fragInfo, String src, Int32 adjustedStart, Int32 fragCharSize) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Persistence\\Lucene\\Highlightings\\FastVectorHightlighter\\BaseFragmentsBuilder.cs:line 139\n   at Lucene.Net.Search.Vectorhighlight.BaseFragmentsBuilder.MakeFragment(StringBuilder buffer, Int32[] index, Field[] values, WeightedFragInfo fragInfo, Int32 fragCharSize, IState state) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Persistence\\Lucene\\Highlightings\\FastVectorHightlighter\\BaseFragmentsBuilder.cs:line 116\n   at Lucene.Net.Search.Vectorhighlight.BaseFragmentsBuilder.CreateFragments(IndexReader reader, Int32 docId, String fieldName, FieldFragList fieldFragList, Int32 maxNumFragments, Int32 fragCharSize, IState state) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Persistence\\Lucene\\Highlightings\\FastVectorHightlighter\\BaseFragmentsBuilder.cs:line 93\n   at Raven.Server.Documents.Indexes.Persistence.Lucene.IndexReadOperation.GetHighlighterResults(IndexQueryServerSide query, IndexSearcher searcher, ScoreDoc scoreDoc, Document document, Document luceneDocument, JsonOperationContext context) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Persistence\\Lucene\\IndexReadOperation.cs:line 294\n   at Raven.Server.Documents.Indexes.Persistence.Lucene.IndexReadOperation.<Query>g__CreateQueryResult|14_0(Document d, <>c__DisplayClass14_0& , <>c__DisplayClass14_1& , <>c__DisplayClass14_2& ) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Persistence\\Lucene\\IndexReadOperation.cs:line 229\n   at Raven.Server.Documents.Indexes.Persistence.Lucene.IndexReadOperation.Query(IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Persistence\\Lucene\\IndexReadOperation.cs:line 162\n   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Index.cs:line 3190\n   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Index.cs:line 3229\n   at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Indexes\\Index.cs:line 3004\n   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Queries\\StaticIndexQueryRunner.cs:line 41\n   at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Queries\\QueryRunner.cs:line 79\n   at Raven.Server.Documents.Handlers.QueriesHandler.Query(QueryOperationContext queryContext, OperationCancelToken token, RequestTimeTracker tracker, HttpMethod method, Boolean diagnostics) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 176\n   at Raven.Server.Documents.Handlers.QueriesHandler.HandleQuery(HttpMethod httpMethod) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 88\n   at Raven.Server.Documents.Handlers.MultiGetHandler.HandleRequestAsync(BlittableJsonReaderObject request, JsonOperationContext context, MultiGetHttpResponseStream responseStream, AsyncBlittableJsonTextWriter writer, HttpContext httpContext, HostString host, String scheme, LazyStringValue resultProperty, LazyStringValue statusProperty, LazyStringValue headersProperty, StringBuilder trafficWatchStringBuilder) in C:\\Builds\\RavenDB-Stable-5.3\\53001\\src\\Raven.Server\\Documents\\Handlers\\MultiGetHandler.cs:line 189"}
   at Raven.Client.Documents.Session.AsyncDocumentSession.ExecuteLazyOperationsSingleStep(ResponseTimeInformation responseTimeInformation, List`1 requests, Stopwatch sw, CancellationToken token) in C:\Builds\RavenDB-Stable-5.2\52012\src\Raven.Client\Documents\Session\AsyncDocumentSession.Lazy.cs:line 138
   at Raven.Client.Documents.Session.AsyncDocumentSession.ExecuteAllPendingLazyOperationsAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.2\52012\src\Raven.Client\Documents\Session\AsyncDocumentSession.Lazy.cs:line 87
```
Unfortunatly i cant share the database due to our  GDPR guidelines.
In the Traffic Watch the query gets indicated as 200 and the multiget looks like this.

```
{"Query":"from index 'BewerbersucheEinfachIndex' where SoftDeleted != $p0 and IstPseudonymisiert != $p1 and (true and not exists(VorraussichtlicheLöschungAm) or (exists(VorraussichtlicheLöschungAm) and not VorraussichtlicheLöschungAm <= $p2 and not ImLöschContainerSeit <= $p3)) and (boost(NiederlassungIdListe in ($p4), 0) or boost(BewerberpoolVereinbarung = $p5, 0)) and (((boost(search(Name, $p6), 10) or boost(regex(Name, $p7), 10)) or search(Sonstiges, $p8) or search(Dokumente, $p9) or boost(search(Highlight, $p10), 0.001) or boost(regex(PersonalNummer, $p11), 5))) select facet(KandidatenStatusId) limit $p12, $p13","PageSize":20,"QueryParameters":{"p0":true,"p1":true,"p2":"2022-02-15T00:00:00.0000000","p3":"2022-02-15T00:00:00.0000000","p4":["Niederlassung/e49dee4a-955b-4687-a692-2fb8863221c2","Niederlassung/1e648d27-5301-4555-831f-3bd1b5f32b59","Niederlassung/b0d56d87-8db3-4f60-939d-3e8f91305838","Niederlassung/fcf7095c-0e53-4411-b782-9abd5f716e22","Niederlassung/2e4c6b3e-b5cf-4d93-89d6-c9af95207a64","Niederlassung/f55c5476-6fe2-45a6-9915-adca036c9435","Niederlassung/0d8c84fd-ccee-4f3f-906b-a4ef909b02e4","Niederlassung/396a1986-de82-4750-a340-94030eed3a88","Niederlassung/124dea8d-181d-4d8e-b507-23177b5ea100","Niederlassung/fdaf905b-4146-4c91-88d0-a033a85cd0f9","Niederlassung/4ffdc8b6-ac63-4143-96c5-05ce8f77bf44","Niederlassung/78015a90-daae-43af-a949-8485d758e1e0","Niederlassung/f77652d1-4f11-45ce-9d6a-389445f4b2a0","Niederlassung/23849376-1c36-4502-9a26-860420e7667d","Niederlassung/5cbe4776-7c20-4899-afef-11d0d660b419"],"p5":true,"p6":"ahmed","p7":"ahmed","p8":"ahmed","p9":"ahmed","p10":"ahmed","p11":"ahmed","p12":0,"p13":20}}
{"Query":"from index 'BewerbersucheEinfachIndex' as e where e.SoftDeleted != $p0 and e.IstPseudonymisiert != $p1 and (true and not exists(e.VorraussichtlicheLöschungAm) or (exists(e.VorraussichtlicheLöschungAm) and not e.VorraussichtlicheLöschungAm <= $p2 and not e.ImLöschContainerSeit <= $p3)) and (boost(e.NiederlassungIdListe in ($p4), 0) or boost(e.BewerberpoolVereinbarung = $p5, 0)) and (((boost(search(e.Name, $p9), 10) or boost(regex(e.Name, $p10), 10)) or search(e.Sonstiges, $p11) or search(e.Dokumente, $p12) or boost(search(e.Highlight, $p13), 0.001) or boost(regex(e.PersonalNummer, $p14), 5))) order by score(), ErstelltAm desc select { Id : e.KandidatenId, PersonalNummer : e.PersonalNummer, Anrede : e.Anrede, Name : e.Name, Geburtstag : e.Geburtsdatum, VerfuegbarAb : e.VerfuegbarAb, ZuletztAktualisiertAm : (e.ZuletztAktualisiertAm!=null?e.ZuletztAktualisiertAm:e.ErstelltAm), ErstelltAm : e.ErstelltAm, Email : e.Email, Telefon : e.TelefonNummer, Bemerkung : e.Bemerkung, Tags : e.Tags, DatenschutzVereinbarungZugestimmt : e.DatenschutzVereinbarung, BewerberpoolVereinbarungZugestimmt : e.BewerberpoolVereinbarung, Wohnort : e.Wohnort, WohnortPlz : e.WohnortPlz, Strasse : e.Strasse, Geolocation : e.Geolocation, GewuenschtesGehalt : e.GewünschtesGehalt, ProfilbildVorhanden : e.ProfilbildVorhanden, Kenntnisse : e.Kenntnisse, UngeordneteKompetenzen : e.UngeordneteKompetenzen, Sprachkenntnisse : e.Sprachkenntnisse, Softskills : e.SoftSkills, Ausbildungen : e.Ausbildungen, BerufserfahrungListe : e.Berufserfahrungen, ProfilVollstaendigkeitInProzent : e.ProfilVollständigkeitInProzent, VonUmkreissuche : $p15, IstArbeitnehmerÜberlassung : e.IstArbeitnehmerÜberlassung, IstPersonalVermittlung : e.IstPersonalVermittlung, Mobilität : e.Mobilität, MobilitätUmkreisKm : e.MobilitätUmkreisKm, MobilitätUmkreisStd : e.MobilitätUmkreisStd, ArbeitsStatus : e.ArbeitsStatus, ArbeitssuchendSeit : e.ArbeitssuchendSeit, GehaltMin : e.GehaltMin, GehaltsArt : e.GehaltsArt, BeworbenAls : e.BeworbenAls, BerufeListe : e.BerufeListe, KategorieId : e.KandidatenKategorieId, AktuellerProzessStatus : e.AktuellerProzessStatus, KandidatenStatusId : e.KandidatenStatusId, BeworbenVia : e.BeworbenVia, BetreuerId : e.BetreuerId, NiederlassungIdListe : e.NiederlassungIdListe, Exposes : e.Exposes, ZuletztVersendeteExpose : e.ZuletztVersendeteExpose, Bewerbungen : e.Bewerbungen } include highlight(Highlight,18,10,$p7),highlight(Dokumente,256,5,$p8),explanations($p6) limit $p16, $p17","PageSize":20,"QueryParameters":{"p0":true,"p1":true,"p2":"2022-02-15T00:00:00.0000000","p3":"2022-02-15T00:00:00.0000000","p4":["Niederlassung/e49dee4a-955b-4687-a692-2fb8863221c2","Niederlassung/1e648d27-5301-4555-831f-3bd1b5f32b59","Niederlassung/b0d56d87-8db3-4f60-939d-3e8f91305838","Niederlassung/fcf7095c-0e53-4411-b782-9abd5f716e22","Niederlassung/2e4c6b3e-b5cf-4d93-89d6-c9af95207a64","Niederlassung/f55c5476-6fe2-45a6-9915-adca036c9435","Niederlassung/0d8c84fd-ccee-4f3f-906b-a4ef909b02e4","Niederlassung/396a1986-de82-4750-a340-94030eed3a88","Niederlassung/124dea8d-181d-4d8e-b507-23177b5ea100","Niederlassung/fdaf905b-4146-4c91-88d0-a033a85cd0f9","Niederlassung/4ffdc8b6-ac63-4143-96c5-05ce8f77bf44","Niederlassung/78015a90-daae-43af-a949-8485d758e1e0","Niederlassung/f77652d1-4f11-45ce-9d6a-389445f4b2a0","Niederlassung/23849376-1c36-4502-9a26-860420e7667d","Niederlassung/5cbe4776-7c20-4899-afef-11d0d660b419"],"p5":true,"p6":{"GroupKey":"KandidatenId"},"p7":{"GroupKey":"KandidatenId","PreTags":["*|<*"],"PostTags":[">|*"]},"p8":{"GroupKey":"KandidatenId"},"p9":"ahmed","p10":"ahmed","p11":"ahmed","p12":"ahmed","p13":"ahmed","p14":"ahmed","p15":false,"p16":0,"p17":20}}

```

Then i remove the Highlightings part from the query it works without issues

`.Highlight(e => e.Highlight, 18, 10, new HighlightingOptions() { PreTags = new[] { _preTags }, PostTags = new[] { _postTags }, GroupKey = _indexGroupKey }, out highlightings)`

**Comment by ayende** [comment]
Hm...
Can you try to create sample data and re-run it? Without additional information, it is fairly hard to figure out. 
We probably only need the `Highlight` field to work with this. And you can probably look at the relevant document matches for this query

**Comment by oiBio** [comment]
i tried trim down all my data so i can reproduce the error. In this process i tried the to a minimal query 

```
from index 'BewerbersucheEinfachIndex' as e 
where search(e.Highlight, "ahmed")
select e.KandidatenId, e.Name
include Highlight("Highlight",18,10)
```

this throws (in the Studio)
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at Raven.Server.Documents.Indexes.Persistence.Lucene.IndexReadOperation.GetHighlighterResults(IndexQueryServerSide query, IndexSearcher searcher, ScoreDoc scoreDoc, Document document, Document luceneDocument, JsonOperationContext context) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Persistence\Lucene\IndexReadOperation.cs:line 317
   at Raven.Server.Documents.Indexes.Persistence.Lucene.IndexReadOperation.<Query>g__CreateQueryResult|14_0(Document d, <>c__DisplayClass14_0& , <>c__DisplayClass14_1& , <>c__DisplayClass14_2& ) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Persistence\Lucene\IndexReadOperation.cs:line 229
   at Raven.Server.Documents.Indexes.Persistence.Lucene.IndexReadOperation.Query(IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Persistence\Lucene\IndexReadOperation.cs:line 162
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Index.cs:line 3190
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Index.cs:line 3229
   at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Index.cs:line 3004
   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Queries\StaticIndexQueryRunner.cs:line 41
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 79
   at Raven.Server.Documents.Handlers.QueriesHandler.Query(QueryOperationContext queryContext, OperationCancelToken token, RequestTimeTracker tracker, HttpMethod method, Boolean diagnostics) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 176
   at Raven.Server.Documents.Handlers.QueriesHandler.HandleQuery(HttpMethod httpMethod) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 88
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Routing\RequestRouter.cs:line 356
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\RavenServerStartup.cs:line 239
```

then i dont include `include Highlight("Highlight",18,10)` then the query executes as expected. 

But when i try to select the Highlight field i also get an exception.

```
from index 'BewerbersucheEinfachIndex' as e 
where search(e.Highlight, "ahmed")
select e.KandidatenId, e.Name, e.Highlight
```
```
System.IO.InvalidDataException: Cannot have a '<' in this position at  (1,2) around: <p>seit 2012 in Deutschland, seit dem hat er Erfahrung als Lagerarbeiter, Produktionshelfer und zuletzt als Schichtleiter sammeln können. er sucht ab sofort eine Tätigkeit in der Produktion oder Lager / AK 13.01.2021</p>P":"87.139.255.127","CertificateThumbprint":"9262F4341FFF8189E47180CAE73B0017040D5817","RequestId":5855,"HttpMethod":"POST","ElapsedMilliseconds":0,"ResponseStatusCode":200,"RequestUri":"https://a.aveo-ravendb.development.run:5443/databases/Artemis.IndexOffError/queries?queryHash=9316769340989081163","AbsoluteUri":"https://a.aveo-ravendb.development.run:5443","ResponseSizeInBytes":922,"Type":"Queries"}���z�@)l
�2��# �H6ǒ�9�9e�ksÔ�Z<������n��D�����kI���º�y$�uc�sP��qG-�gVgx��W��զ��H}�g��掜�k8lBS"��#��G������zk�o9a/�I+�߸·�'��Ě�uf�C���\�D�/`e@�WZ�[�L#�#����ŗ�@�pUjz�kh�6�4з	
�ٽٟ���Zɫ8�#�y���kg�dR��r��n�e��e&����3"s��r��U�g�#��nKɃ!����=2>R�O'�/����Dpn���r�N'�a��9�*��1�v��{�O���
   at Sparrow.Json.Parsing.UnmanagedJsonParser.ThrowException(String message, Exception inner) in C:\Builds\RavenDB-Stable-5.3\53001\src\Sparrow\Json\Parsing\UnmanagedJsonParser.cs:line 931
   at Sparrow.Json.Parsing.UnmanagedJsonParser.ThrowCannotHaveCharInThisPosition(Byte b) in C:\Builds\RavenDB-Stable-5.3\53001\src\Sparrow\Json\Parsing\UnmanagedJsonParser.cs:line 426
   at Sparrow.Json.Parsing.UnmanagedJsonParser.ReadUnlikely(Byte b, UInt32& pos, Boolean& couldRead) in C:\Builds\RavenDB-Stable-5.3\53001\src\Sparrow\Json\Parsing\UnmanagedJsonParser.cs:line 401
   at Sparrow.Json.BlittableJsonDocumentBuilder.ReadInternal[TWriteStrategy]() in C:\Builds\RavenDB-Stable-5.3\53001\src\Sparrow\Json\BlittableJsonDocumentBuilder.cs:line 127
   at Sparrow.Server.Json.Sync.JsonOperationContextSyncExtensions.ParseToMemory(SyncJsonOperationContext syncContext, Stream stream, String debugTag, UsageMode mode, MemoryBuffer bytes, IBlittableDocumentModifier modifier) in C:\Builds\RavenDB-Stable-5.3\53001\src\Sparrow.Server\Json\Sync\JsonOperationContextSyncApiExtensions.cs:line 91
   at Sparrow.Server.Json.Sync.JsonOperationContextSyncExtensions.ParseToMemory(SyncJsonOperationContext syncContext, Stream stream, String debugTag, UsageMode mode, IBlittableDocumentModifier modifier) in C:\Builds\RavenDB-Stable-5.3\53001\src\Sparrow.Server\Json\Sync\JsonOperationContextSyncApiExtensions.cs:line 61
   at Sparrow.Server.Json.Sync.JsonOperationContextSyncExtensions.ReadForMemory(SyncJsonOperationContext syncContext, String jsonString, String documentId) in C:\Builds\RavenDB-Stable-5.3\53001\src\Sparrow.Server\Json\Sync\JsonOperationContextSyncApiExtensions.cs:line 55
   at Raven.Server.Documents.Queries.Results.QueryResultRetrieverBase.TryExtractValueFromIndex(FieldToFetch fieldToFetch, Document indexDocument, DynamicJsonValue toFill, IState state) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Queries\Results\QueryResultRetrieverBase.cs:line 451
   at Raven.Server.Documents.Queries.Results.QueryResultRetrieverBase.GetProjection(Document input, ScoreDoc scoreDoc, String lowerId, IState state, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Queries\Results\QueryResultRetrieverBase.cs:line 175
   at Raven.Server.Documents.Queries.Results.StoredValueQueryResultRetriever.Get(Document input, ScoreDoc scoreDoc, IState state, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Queries\Results\MapReduceQueryResultRetriever.cs:line 110
   at Raven.Server.Documents.Indexes.Persistence.Lucene.IndexReadOperation.Query(IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Persistence\Lucene\IndexReadOperation.cs:line 159
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Index.cs:line 3190
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Index.cs:line 3229
   at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Indexes\Index.cs:line 3004
   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Queries\StaticIndexQueryRunner.cs:line 41
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 79
   at Raven.Server.Documents.Handlers.QueriesHandler.Query(QueryOperationContext queryContext, OperationCancelToken token, RequestTimeTracker tracker, HttpMethod method, Boolean diagnostics) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 176
   at Raven.Server.Documents.Handlers.QueriesHandler.HandleQuery(HttpMethod httpMethod) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 88
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\Routing\RequestRouter.cs:line 356
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.3\53001\src\Raven.Server\RavenServerStartup.cs:line 239
```

Maybe this is an encoding problem?

**Comment by grisha-kotler** [comment]
Can you export the relevant collection and the index and share it with us?

**Comment by oiBio** [comment]
in the current state not. it contains names, adresses and so i cant share them. But i try to strip the data futher down. Maybe i can idetify one single problematic record and trim/delete all gdpr relative fields.
Im currently working on it

**Comment by oiBio** [comment]
Okay... i could track the record down which caused the error.

Attached you find the database export with the index and record.
[Dump of IndexOff2 2022-02-16 14-46.zip](https://github.com/ravendb/ravendb/files/8080326/Dump.of.IndexOff2.2022-02-16.14-46.zip)

this is the query you need to run agains the database

 ```
            var query = session.Advanced
                .AsyncDocumentQuery<IndexErrorTestClass>("TESTIndexOff")
                .Search("Highlight", "ahmed")
                .Highlight("Highlight", 18, 10, 
                    new HighlightingOptions() { PreTags = new[] { "<|" }, PostTags = new[] { "|>" }, GroupKey = "KandidatenId" }, 
                    out var _)
                ;
            await query.ToListAsync();  // Thows the Error
```
The result class does not matter much, but this was the one i used in my tests
` public record IndexErrorTestClass(string Name, string Vorname); `  


i think it is related to the fact, that the search term "ahmed" occurs multiple times inside the text.... but should this throw an error? When you dont include the Highlight the query work

**Comment by ayende** [comment]
Can you send the `ToString()` of the query?

**Comment by oiBio** [comment]
`from index 'TESTIndexOff' where search(Highlight, $p0) include highlight(Highlight,18,10,$p1)`

**Comment by haludi** [comment]
Hi,

We have managed to reproduce it.
Thank you for the information.
I will update you on the progress.

Best regards,
Igal

**Comment by haludi** [comment]
Hi,

You can track the issue here -
https://issues.hibernatingrhinos.com/issue/RavenDB-18078

Best regards,
Igal
