### ISSUE TITLE
Error in map function in field of type DateOnly?

### ISSUE THREAD

**Issue by montyclt** [ravendb/ravendb#13943]
This is my index:
```cs
public record CustomerProfileResult
{
    public string Name { get; init; }
    public CustomerType CustomerType { get; init; }
    public EmailAddress EmailAddress { get; init; }
    public Document Document { get; init; }
    public IEnumerable<CustomerProfileContractResult> Contracts { get; init; }
}

public record IndividualCustomerProfileResult : CustomerProfileResult
{
    public string GivenName { get; init; }
    public string FamilyName { get; init; }
    public DateOnly BirthDate { get; init; }
}

public record Result : IndividualCustomerProfileResult
{
    public Id<Customer> Id { get; init; }
    public new DateOnly? BirthDate { get; init; }
    public new CustomerType? CustomerType { get; init; }
}

public class Core_Customers_CustomerProfile : AbstractMultiMapIndexCreationTask<Result>
{
    public Core_Customers_CustomerProfile()
    {
        AddMap<BusinessCustomer>(customers =>
            from customer in customers
            select new Result
            {
                Id = customer.Id,
                Contracts = null,
                Document = customer.Document,
                Name = customer.Name,
                CustomerType = customer.Type,
                EmailAddress = customer.EmailAddress,
                BirthDate = null,
                FamilyName = null,
                GivenName = null,
            });
        
        AddMap<IndividualCustomer>(customers =>
            from customer in customers
            select new Result
            {
                Id = customer.Id,
                Contracts = null,
                Document = customer.Document,
                Name = customer.Name,
                BirthDate = customer.BirthDate,
                CustomerType = customer.Type,
                EmailAddress = customer.EmailAddress,
                FamilyName = customer.PersonName.FamilyName,
                GivenName = customer.PersonName.GivenName
            });
        
        AddMap<Contract>(contracts =>
            from contract in contracts
            select new Result
            {
                Id = contract.CustomerId,
                Contracts = new []
                {
                    new CustomerProfileContractResult
                    {
                        Address = contract.Address,
                        Name = contract.Name,
                        Phone = contract.Phone,
                        ContractId = contract.Id
                    }
                },
                Document = null,
                Name = null,
                CustomerType = null,
                EmailAddress = null,
                BirthDate = null,
                FamilyName = null,
                GivenName = null
            });

        Reduce = results =>
            from result in results
            group result by result.Id
            into g
            select new Result
            {
                Id = g.Key,
                Contracts = g.SelectMany(x => x.Contracts),
                Document = g.Select(x => x.Document).First(x => x != null),
                Name = g.Select(x => x.Name).First(x => x != null),
                CustomerType = g.Select(x => x.CustomerType).First(x => x != null),
                EmailAddress = g.Select(x => x.EmailAddress).First(x => x != null),
                BirthDate = g.Select(x => x.BirthDate).First(x => x != null),
                FamilyName = g.Select(x => x.FamilyName).First(x => x != null),
                GivenName = g.Select(x => x.GivenName).First(x => x != null)
            };
    }
}
```

I get this error:
```
Failed to execute mapping function on 34-A. Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Member 'System.DateOnly.MinValue.get' cannot be accessed with an instance reference; qualify it with a type name instead
   at CallSite.Target(Closure , CallSite , Object )
   at Raven.Server.Documents.Indexes.Persistence.Lucene.Documents.PropertyAccessor.ValueTypeAccessor.GetValue(Object target) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\Indexes\Persistence\Lucene\Documents\PropertyAccessor.cs:line 124
   at Raven.Server.Documents.Indexes.Persistence.Lucene.Documents.PropertyAccessor.GetPropertiesInOrder(Object target)+MoveNext() in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\Indexes\Persistence\Lucene\Documents\PropertyAccessor.cs:line 29
   at Raven.Server.Utils.TypeConverter.ToBlittableSupportedType(Object root, Object value, Boolean flattenArrays, Boolean forIndexing, Int32 recursiveLevel, Engine engine, JsonOperationContext context, BlittableSupportedReturnType& blittableSupportedReturnType) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Utils\TypeConverter.cs:line 375
   at Raven.Server.Documents.Indexes.MapReduce.Static.MapReduceIndex.AnonymousObjectToBlittableMapResultsEnumerableWrapper.Enumerator.MoveNext() in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\Indexes\MapReduce\Static\MapReduceIndex.cs:line 559
   at Raven.Server.Documents.Indexes.MapReduce.MapReduceIndexBase`2.PutMapResults(LazyStringValue lowerId, LazyStringValue sourceDocumentId, IEnumerable`1 mappedResults, TransactionOperationContext indexContext, IndexingStatsScope stats) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\Indexes\MapReduce\MapReduceIndexBase.cs:line 118
   at Raven.Server.Documents.Indexes.MapReduce.Static.MapReduceIndex.HandleMap(IndexItem indexItem, IEnumerable mapResults, Lazy`1 writer, TransactionOperationContext indexContext, IndexingStatsScope stats) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\Indexes\MapReduce\Static\MapReduceIndex.cs:line 383
   at Raven.Server.Documents.Indexes.Workers.MapItems.Execute(QueryOperationContext queryContext, TransactionOperationContext indexContext, Lazy`1 writeOperation, IndexingStatsScope stats, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\Indexes\Workers\MapItems.cs:line 105
```

**Comment by montyclt** [comment]
I'm using `DateTime?` as workaround:

```cs
AddMap<IndividualCustomer>(customers =>
    from customer in customers
    select new Result
    {
        Id = customer.Id,
        Contracts = null,
        Document = customer.Document,
        Name = customer.Name,
        BirthDate = customer.BirthDate.ToDateTime(new TimeOnly()), // <----
        CustomerType = customer.Type,
        EmailAddress = customer.EmailAddress,
        FamilyName = customer.PersonName.FamilyName,
        GivenName = customer.PersonName.GivenName
    });
``

**Comment by haludi** [comment]
Hi,

Can you submit a full failing test for this?
https://ravendb.net/docs/article-page/4.2/csharp/start/test-driver

Best regards,
Igal

**Comment by maciejaszyk** [comment]
Hi,
I tried to reproduce it from your index but it's working. Can you take a look at this test and compare it with your data?

Thanks!


```

using System;
using System.Linq;
using FastTests;
using Raven.Client.Documents.Indexes;
using Raven.Client.Documents.Operations.Indexes;
using Xunit;
using Xunit.Abstractions;

namespace SlowTests.Issues;

public class DateOnlyFailingTest : RavenTestBase
{
    public DateOnlyFailingTest(ITestOutputHelper output) : base(output)
    {
    }

    [Fact]
    public void ShouldWork()
    {
        using var store = GetDocumentStore();
        {
            using var s = store.OpenSession();
            s.Store(new BussinessCustomer
            {
                Id = "bus1",
              
            });
            s.Store(new IndividualCustomer
            {
                Id = "cus1",
                BirthDate = null //new DateOnly(2022, 9, 10)
            });
            s.Store(new Contract
            {
                Id = "con1",
               
            });
            s.SaveChanges();
        }

        var index = new Core_Customers_CustomerProfile();
        index.Execute(store);
        Indexes.WaitForIndexing(store);
        var indexErrors = store.Maintenance.Send(new GetIndexErrorsOperation(new[] { index.IndexName }));
        Assert.Equal(0, indexErrors[0].Errors.Length);
    }
    
    record BussinessCustomer
    {
        public string Id { get; init; }
    }

    record IndividualCustomer
    {
        public string Id { get; init; }
        public DateOnly? BirthDate { get; init; }
    }

    record Contract
    {
        public string Id { get; init; }
    }

    public record CustomerProfileResult
    {
        public string Id { get; init; }
    }

    public record IndividualCustomerProfileResult : CustomerProfileResult
    {
        public DateOnly BirthDate { get; init; }
    }

    public record Result : IndividualCustomerProfileResult
    {
        public new DateOnly? BirthDate { get; init; }
    }
    
    private class Core_Customers_CustomerProfile : AbstractMultiMapIndexCreationTask<Result>
    {
        public Core_Customers_CustomerProfile()
        {
            AddMap<BussinessCustomer>(customers =>
                from customer in customers
                select new Result {Id = customer.Id, BirthDate = null,});

            AddMap<IndividualCustomer>(customers =>
                from customer in customers
                select new Result {Id = customer.Id, BirthDate = customer.BirthDate,});

            AddMap<Contract>(contracts =>
                from contract in contracts
                select new Result {Id = contract.Id, BirthDate = null,});

            Reduce = results =>
                from result in results
                group result by result.Id
                into g
                select new Result {Id = g.Key, BirthDate = g.Select(x => x.BirthDate).First(x => x != null),};
        }
    }
}

```

**Comment by maciejaszyk** [comment]
Hello,
I've reproduced it and already working on it. You can check the progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-18404 .

Thanks for your feedback.

**Comment by montyclt** [comment]
> Hello, I've reproduced it and already working on it. You can check the progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-18404 .
> 
> Thanks for your feedback.

Is fixed in the last nightly build?

**Comment by maciejaszyk** [comment]
> > Hello, I've reproduced it and already working on it. You can check the progress here: https://issues.hibernatingrhinos.com/issue/RavenDB-18404 .
> > Thanks for your feedback.
> 
> Is fixed in the last nightly build?

Yes, the changes are available in the latest nightly build.
To get all the fixes you've to update Server and Client.
