### ISSUE TITLE
EarlyOutOfMemoryException during Import after increasing RAM

### ISSUE THREAD

**Issue by Ron-Brouwer** [ravendb/ravendb#14099]
Hi Guys,

We are trying to import some millions of documents into RavenDB using the Management Studio. Haven't seen any issues with this before, but now after doubling the available RAM this morning (24Gb -> 48Gb) Import fails with EOOM (while moving into production today). The server isn't handling any other workload besides this Import.

We are currently retrying the operation without indexing.
Any help is much appreciated.

**Stacktrace during Import:**

```
The amount of available memory to commit on the system is low. Commit charge: 87.815 GBytes / 87.938 GBytes. Memory: 47.584 GBytes / 47.999 GBytes
Sparrow.LowMemory.EarlyOutOfMemoryException: The amount of available memory to commit on the system is low. Commit charge: 87.815 GBytes / 87.938 GBytes. Memory: 47.584 GBytes / 47.999 GBytes
   at Sparrow.LowMemory.MemoryInformation.ThrowInsufficientMemory(MemoryInfoResult memInfo) in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow.Server\LowMemory\MemoryInformation.cs:line 193
   at Sparrow.LowMemory.MemoryInformation.AssertNotAboutToRunOutOfMemory() in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow.Server\LowMemory\MemoryInformation.cs:line 135
   at Sparrow.Utils.NativeMemory.AllocateMemory(Int64 size, ThreadStats& thread) in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow\Utils\NativeMemory.cs:line 143
   at Sparrow.Server.UnmanagedGlobalSegment..ctor(Int32 size) in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow.Server\ByteString.cs:line 462
   at Sparrow.Server.ByteStringMemoryCache.Allocate(Int32 size, Action allocationFailure) in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow.Server\ByteString.cs:line 601
   at Sparrow.Server.ByteStringContext`1.AllocateExternalSegment(Int32 size) in C:\Builds\RavenDB-Stable-5.3\53009\src\Sparrow.Server\ByteString.cs:line 1254
   at Voron.Data.BTrees.IteratorExtensions.ValidateCurrentKey[T](T self, LowLevelTransaction tx, TreeNodeHeader* node) in C:\Builds\RavenDB-Stable-5.3\53009\src\Voron\Data\BTrees\TreeIterator.cs:line 335
   at Voron.Data.BTrees.TreeIterator.Seek(Slice key) in C:\Builds\RavenDB-Stable-5.3\53009\src\Voron\Data\BTrees\TreeIterator.cs:line 47
   at Voron.Data.Tables.Table.SeekByPrimaryKeyPrefix(Slice requiredPrefix, Slice startAfter, Int64 skip)+MoveNext() in C:\Builds\RavenDB-Stable-5.3\53009\src\Voron\Data\Tables\Table.cs:line 1352
   at Raven.Server.Documents.DocumentPutAction.DeleteTombstoneIfNeeded(DocumentsOperationContext context, CollectionName collectionName, Slice id) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\DocumentPutAction.cs:line 760
   at Raven.Server.Documents.DocumentPutAction.DeleteTombstoneIfNeeded(DocumentsOperationContext context, CollectionName collectionName, Byte* lowerId, Int32 lowerSize) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\DocumentPutAction.cs:line 755
   at Raven.Server.Documents.DocumentPutAction.PutDocument(DocumentsOperationContext context, String id, String expectedChangeVector, BlittableJsonReaderObject document, Nullable`1 lastModifiedTicks, String changeVector, String oldChangeVectorForClusterTransactionIndexCheck, DocumentFlags flags, NonPersistentDocumentFlags nonPersistentFlags) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\DocumentPutAction.cs:line 298
   at Raven.Server.Smuggler.Documents.DatabaseDestination.MergedBatchPutCommand.ExecuteCmd(DocumentsOperationContext context) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\DatabaseDestination.cs:line 1434
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 executedOps, DocumentsOperationContext context, Task previousOperation, DurationMeasurement& meter) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 910
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsOnce() in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 518
--- End of stack trace from previous location ---
   at Raven.Server.Documents.TransactionOperationsMerger.Enqueue(MergedTransactionCommand cmd) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 145
   at Raven.Server.Smuggler.Documents.DatabaseDestination.DatabaseDocumentActions.FinishBatchOfDocumentsAsync() in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\DatabaseDestination.cs:line 538
   at Raven.Server.Smuggler.Documents.DatabaseDestination.DatabaseDocumentActions.DisposeAsync() in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\DatabaseDestination.cs:line 350
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessDocumentsAsync(SmugglerResult result, BuildVersionType buildType) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 755
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessTypeAsync(DatabaseItemType type, SmugglerResult result, BuildVersionType buildType, Boolean ensureStepsProcessed) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 195
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ExecuteAsync(Boolean ensureStepsProcessed, Boolean isLastFile) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 94
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ExecuteAsync(Boolean ensureStepsProcessed, Boolean isLastFile) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 104
   at Raven.Server.Smuggler.Documents.Handlers.SmugglerHandler.DoImportInternalAsync(DocumentsOperationContext context, Stream stream, DatabaseSmugglerOptionsServerSide options, SmugglerResult result, Action`1 onProgress, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\Handlers\SmugglerHandler.cs:line 882
   at Raven.Server.Smuggler.Documents.Handlers.SmugglerHandler.DoImportInternalAsync(DocumentsOperationContext context, Stream stream, DatabaseSmugglerOptionsServerSide options, SmugglerResult result, Action`1 onProgress, OperationCancelToken token) in C:\Builds\RavenDB-Stable-5.3\53009\src\Raven.Server\Smuggler\Documents\Handlers\SmugglerHandler.cs:line 883
```

**Comment by ayende** [comment]
Can you attach the debug package?

What is the output of https://docs.microsoft.com/en-us/sysinternals/downloads/vmmap ?

**Comment by Ron-Brouwer** [comment]
He just failed again, this time it just hang and was aborted by RavenDB without furter info.
How do I collect a debug package? > /admin/debug/info-package?

Will start again and collect data

**Comment by ayende** [comment]
Yes, see also https://ravendb.net/learn/inside-ravendb-book/reader/4.0/16-monitoring-troubleshooting-and-disaster-recovery#the-debug-info-package

**Comment by Ron-Brouwer** [comment]
Just send the first package to a@a.com
Thanks!

**Comment by ayende** [comment]
This is the key information from your debug package:

```
    "MemoryInformation": {
        "PhysicalMemory": "47.999 GBytes",
        "WorkingSet": "31.764 GBytes",
        "ManagedAllocations": "734.19 MBytes",
        "UnmanagedAllocations": "89.99 MBytes",
        "EncryptionBuffersInUse": "0 Bytes",
        "EncryptionBuffersPool": "0 Bytes",
        "EncryptionLockedMemory": "0 Bytes",
        "MemoryMapped": "303.77 GBytes",
        "ScratchDirtyMemory": "0 Bytes",
        "IsHighDirty": false,
        "DirtyMemory": "6.75 MBytes",
        "AvailableMemory": "12.78 GBytes",
        "AvailableMemoryForProcessing": "42.259 GBytes",
        "HighMemLastOneMinute": "41.188 GBytes",
        "LowMemLastOneMinute": "12.783 GBytes",
        "HighMemLastFiveMinute": "42.085 GBytes",
        "LowMemLastFiveMinute": "12.783 GBytes",
        "HighMemSinceStartup": "44.995 GBytes",
        "LowMemSinceStartup": "12.782 GBytes"
    },
```

All of this indicate perfectly fine system. 
What database are you bulk inserting into?

**Comment by Ron-Brouwer** [comment]
I'll send you the next batch of debug-info's leading up to 100% of memory usage including MMP's. Fortunately for us RavenDB released 30GB of RAM just seconds before crashing. The last package contains the state after the memory was released. The Import worked this time, hopefully the indexes will also succeed without EOOM as well.  

Hopefully you can use this info to make an even better product 😊

**Comment by garayx** [comment]
When you have high memory usage, you can access directly to `{SERVER_URL}/admin/debug/memory/stats` endpoint, and send us the output from it.
