### ISSUE TITLE
The database *** is currently locked because Checking if we need to recreate indexes

### ISSUE THREAD

**Issue by akbar-ehsaan** [ravendb/ravendb#14181]
I am using RavenTestDriver for my unittests ,so in my hostbuilder class as you can see I created 4 databases :

```
public class TestHostBuilder : RavenTestDriver, IDisposable
    {

        public IHost host = null;
        public IConfiguration Configuration;
        public IDocumentStore documentStore = null;
        public TestHostBuilder()
        {
            ConfigureServer(new TestServerOptions() { FrameworkVersion = null, });
            documentStore = GetDocumentStore();
            Environment.SetEnvironmentVariable("TEST_ENV", "on");
            Appset.EnsureDatabaseExists(documentStore, "shard-1", true);
            Appset.EnsureDatabaseExists(documentStore, "shard-2", true);
            Appset.EnsureDatabaseExists(documentStore, "shard-3", true);
            Appset.EnsureDatabaseExists(documentStore, "shard-4", true);
            var hostBuilder = easy.api.Program.CreateHostBuilder(new string[0])
         .ConfigureWebHost(webHostBuilder =>
         {
             webHostBuilder.UseTestServer();
         }).ConfigureAppConfiguration(config =>
         {
            //config.AddJsonFile("appSettingTest.json", false,false);
        })
        .ConfigureServices(services =>
        {
            domain.Environments.RavenOptions appSettings = new domain.Environments.RavenOptions()
            {
                PublicDbName = documentStore.Database,
                CertificateDirectory="",
                IsHttps=false,
                PublicUrl=documentStore.Identifier.Split("(").First(),
                TseDbName=documentStore.Database,
                ShardUrls=Enumerable.Repeat(documentStore.Identifier.Split("(").First(), 4).ToArray()
            };
            IOptions<domain.Environments.RavenOptions> options = Options.Create(appSettings);
                   services.AddScoped<IOptions<domain.Environments.RavenOptions>>((p) =>
            {
                return options;
            });
            services.AddScoped<ICurrentUserService, InitRequest>();
            services.AddScoped<ICacheStorage>(provider =>
            {
                return new Mock<ICacheStorage>().Object;
            });
            services.AddRavenDbAsyncSession(GetDocumentStore(new GetDocumentStoreOptions()));
            services.AddTransient<IAsyncDocumentSession>((c) =>
             {
                 return documentStore.OpenAsyncSession();
             });

        });

            host = hostBuilder.Start();

        }


    }
```
When I run my tests I get this error :

```
System.AggregateException : One or more errors occurred. (Raven.Client.Exceptions.Database.DatabaseDisabledException: The database shard-1 is currently locked because Checking if we need to recreate indexes
       at Raven.Server.Documents.DatabasesLandlord.UnloadAndLockDatabase(String dbName, String reason) in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\Documents\DatabasesLandlord.cs:line 907
       at Raven.Server.Web.System.AdminDatabasesHandler.Put() in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 327
       at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\Routing\RequestRouter.cs:line 349
       at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\RavenServerStartup.cs:line 174
    The server at /admin/databases?name=shard-1&replicationFactor=1&raft-request-id=32338a9f-b18e-4245-b0ba-9b582ceb2836 responded with status code: ServiceUnavailable.) (The following constructor parameters did not have matching fixture data: TestHostBuilder _fixture)
    ---- Raven.Client.Exceptions.Database.DatabaseDisabledException : Raven.Client.Exceptions.Database.DatabaseDisabledException: The database shard-1 is currently locked because Checking if we need to recreate indexes
       at Raven.Server.Documents.DatabasesLandlord.UnloadAndLockDatabase(String dbName, String reason) in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\Documents\DatabasesLandlord.cs:line 907
       at Raven.Server.Web.System.AdminDatabasesHandler.Put() in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 327
       at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\Routing\RequestRouter.cs:line 349
       at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.2\52000\src\Raven.Server\RavenServerStartup.cs:line 174
    The server at /admin/databases?name=shard-1&replicationFactor=1&raft-request-id=32338a9f-b18e-4245-b0ba-9b582ceb2836 responded with status code: ServiceUnavailable.
    ---- The following constructor parameters did not have matching fixture data: TestHostBuilder _fixture

  Stack Trace: 
    ----- Inner Stack Trace #1 (Raven.Client.Exceptions.Database.DatabaseDisabledException) -----
    RequestExecutor.ThrowFailedToContactAllNodes[TResult](RavenCommand`1 command, HttpRequestMessage request) line 1157
    RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token)
    RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) line 900
    RequestExecutor.UnlikelyExecuteAsync[TResult](RavenCommand`1 command, JsonOperationContext context, Task topologyUpdate, SessionInfo sessionInfo, CancellationToken token) line 584
    ServerOperationExecutor.SendAsync[TResult](IServerOperation`1 operation, CancellationToken token) line 118
    <<RunSync>b__0>d.MoveNext() line 106
    --- End of stack trace from previous location ---
    AsyncHelpers.RunSync[T](Func`1 task) line 125
    ServerOperationExecutor.Send[TResult](IServerOperation`1 operation) line 100
    Appset.EnsureDatabaseExists(IDocumentStore store, String database, Boolean createDatabaseIfNotExists) line 84
    TestHostBuilder.ctor() line 107
    ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```
```
```

I want  to know how I can disable index recreate for all databases  I used this but it didn't work.
```
 store.Maintenance.Send(new SetIndexesLockOperation(new SetIndexesLockOperation.Parameters
                    {
                        Mode=Raven.Client.Documents.Indexes.IndexLockMode.LockedIgnore
                    }));
```

Example code of my unit test class :

```
 public class DraftControllerTests : IClassFixture<TestHostBuilder>
    {

        TestHostBuilder fixture;
        public DraftControllerTests(TestHostBuilder _fixture)
        {
            this.fixture = _fixture;
        }
        [Fact]
        public async Task GetDraftControllerTest()
        {
            //Arrange
            var data = new DraftEntity()
            {
                CautionAgreementSelected=true,
                CorrelationId=Guid.NewGuid().ToString(),
                CreateDateTime=DateTime.Now,
                CustomerIsin=Constants.customerIsin,
                FinancialProviders=domain.Enums.FinancialProviders.TBRFinancialDataProvider,
                Iceberg=1,
                Id="commandId",
                MinimumQuantity=1,
                OrderType =domain.Enums.OrderType.LimiteOrder,
                Price  =22,
                Quantity=1,
                Side=domain.Enums.OrderSide.Buy,
                SymbolIsin ="132",
                SymbolName="122",
                TriggerPrice=444,
                ValidityDate=DateTime.Now,
                ValidityType=domain.Enums.OrderValidityEnum.GOOD_TILL_DATE
            };

            IAsyncDocumentSession session = fixture.documentStore.OpenAsyncSession();
            await session.StoreAsync(data);
            await session.SaveChangesAsync();
            //Act
            using (var client = fixture.host.GetTestServer().CreateClient())
            {
                var response = await client.GetAsync($"api/draft");
                response.EnsureSuccessStatusCode();
                var Result = JsonConvert.DeserializeObject<List<DraftEntity>>(await response.Content.ReadAsStringAsync());
                //Assert
                Assert.Equal(HttpStatusCode.OK, response.StatusCode);
                Assert.Equal(22, Result[0].Price);

            }


        }


    }
```

![image](https://user-images.githubusercontent.com/45014174/167544214-03425d9b-769b-438c-9b7a-146f311103a5.png)

**Comment by akbar-ehsaan** [comment]
@ayende

**Comment by akbar-ehsaan** [comment]
@ayende  would you please check the question ?

**Comment by ppekrol** [comment]
1. Is there a chance you are creating a database concurrently or on a same path? What is inside the `Appset.EnsureDatabaseExists` method?
2. There is no option to disable creation of indexes, you can disable indexing server or database-wide using https://ravendb.net/docs/article-page/5.3/csharp/server/configuration/indexing-configuration#indexing.disable setting

**Comment by akbar-ehsaan** [comment]
> 1. Is there a chance you are creating a database concurrently or on a same path? What is inside the `Appset.EnsureDatabaseExists` method?
> 
>     2. There is no option to disable creation of indexes, you can disable indexing server or database-wide using https://ravendb.net/docs/article-page/5.3/csharp/server/configuration/indexing-configuration#indexing.disable setting

it is the ensureDatabaseExists function 
```

 public static void EnsureDatabaseExists(IDocumentStore store, string database = null, bool createDatabaseIfNotExists = true)
        {

            database = database ?? store.Database;

            if (string.IsNullOrWhiteSpace(database))
                throw new ArgumentException("Value cannot be null or whitespace.", nameof(database));

            try
            {

                store.Maintenance.ForDatabase(database).Send(new GetStatisticsOperation());
            }
            catch (DatabaseDoesNotExistException)
            {
                if (createDatabaseIfNotExists == false)
                    throw;

                try
                {
                    store.Maintenance.Server.Send(new CreateDatabaseOperation(new DatabaseRecord(database)));

                }
                catch (ConcurrencyException)
                {
                    // The database was already created before calling CreateDatabaseOperation
                }

            }

        }
    }
```

**Comment by akbar-ehsaan** [comment]
> 1. Is there a chance you are creating a database concurrently or on a same path? What is inside the `Appset.EnsureDatabaseExists` method?
> 
>     2. There is no option to disable creation of indexes, you can disable indexing server or database-wide using https://ravendb.net/docs/article-page/5.3/csharp/server/configuration/indexing-configuration#indexing.disable setting

I changed this function to this , and I added some catches and now it works .Is it a correct solution ?

```
 public static void EnsureDatabaseExists(IDocumentStore store, string database = null, bool createDatabaseIfNotExists = true)
        {

            database = database ?? store.Database;

            if (string.IsNullOrWhiteSpace(database))
                throw new ArgumentException("Value cannot be null or whitespace.", nameof(database));

            try
            {

                store.Maintenance.ForDatabase(database).Send(new GetStatisticsOperation());
            }
            catch (DatabaseDoesNotExistException)
            {
                if (createDatabaseIfNotExists == false)
                    throw;

                try
                {
                    store.Maintenance.Server.Send(new CreateDatabaseOperation(new DatabaseRecord(database)));

                }
                catch (ConcurrencyException)
                {
                    // The database was already created before calling CreateDatabaseOperation
                }
                catch (DatabaseDisabledException)
                {

                }

            }
            catch (DatabaseDisabledException)
            {

            }
        }
    }
```

**Comment by ppekrol** [comment]
Not sure what is your scenario, but when it comes to testing an often solution is to isolate the tests entirely, each call to RavenTestDriver.GetDocumentStore will create you a separate database. Also you need to either dispose that store or dispose the RavenTestDriver to remove all of the databases that were created.

In you example you, it looks like you are working on 4 of the databases which are shared among the tests? Are the directories where they are created cleaned-up?

**Comment by akbar-ehsaan** [comment]
yes I have to inject all dependencies when I created an in memory host, so we decided to use a shared database in all tests ,No i don't have any clean-up plan for them , I thought they cleaned-up when class disposed

**Comment by ppekrol** [comment]
Only the ones created by 'RavenTestDriver.GetDocumentStore' are removed when RavenTestDriver is class is disposed. The oens that you create manually need to be handled by you.
