### ISSUE TITLE
Error when using AddDays() on a DateOnly property in an index

### ISSUE THREAD

**Issue by jac-dev** [ravendb/ravendb#14279]
Hi

I have an Index which does some date calculations with `DateTime` and `DateOnly`. Invoking `AddDays(..)` on a property of type `DateOnly` leads to an error. I first detected the issue with a MapReduceIndex, but I was able to reproduce it with a much simpler test. I'm using the latest version of RavenDB (5.3.102).

```
public class DateOnlyBug : RavenTestDriver
{
    [Fact]
    public async Task DateOnlyBug_AddDays()
    {
        using var store = GetDocumentStore();

        await store.ExecuteIndexAsync(new EmployeeAlertIndex());

        using (var session = store.OpenAsyncSession())
        {
            await session.StoreAsync(new Employee
            {
                Id = "employees/1",
                DateOnlyValue = new DateOnly(2000, 1, 1),
                DateTimeValue = new DateTime(2022, 5, 25, 12, 13, 14)
            });
            await session.SaveChangesAsync();
        }

        WaitForIndexing(store);

        using (var session = store.OpenAsyncSession())
        {
            var results = await session.Query<EmployeeAlertIndex.Result, EmployeeAlertIndex>()
                .As<Employee>()
                .ToListAsync();

            Assert.Equal(1, results.Count);
        }
    }
}

public class Employee
{
    public string Id { get; set; }
    public DateOnly DateOnlyValue { get; set; }
    public DateTime DateTimeValue { get; set; }
}

public class EmployeeAlertIndex : AbstractIndexCreationTask<Employee>
{
    public class Result
    {
        public string EmployeeId { get; set; }
    }

    public EmployeeAlertIndex()
    {
        Map = employees => from employee in employees`
                           // the next line seems to be problematic
                           where AsDateOnly(employee.DateTimeValue) < employee.DateOnlyValue.AddDays(-50) 
                           select new
                           {
                               EmployeeId = employee.Id
                           };
    }
}
```

This test leads to the following error.

```
Failed to execute mapping function on employees/1. Exception: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Sparrow.Json.LazyStringValue' does not contain a definition for 'AddDays'
   at CallSite.Target(Closure , CallSite , Object , Int32 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Raven.Server.Documents.Indexes.Static.Generated.Index_EmployeeAlertIndex.Map_0(IEnumerable`1 docs)+MoveNext()
   at Raven.Server.Documents.Indexes.Static.TimeCountingEnumerable.Enumerator.MoveNext() in C:\Builds\RavenDB-Stable-5.3\53016\src\Raven.Server\Documents\Indexes\Static\TimeCountingEnumerable.cs:line 41
   at Raven.Server.Documents.Indexes.MapIndexBase`2.HandleMap(IndexItem indexItem, IEnumerable mapResults, Lazy`1 writer, TransactionOperationContext indexContext, IndexingStatsScope stats) in C:\Builds\RavenDB-Stable-5.3\53016\src\Raven.Server\Documents\Indexes\MapIndexBase.cs:line 65
   at Raven.Server.Documents.Indexes.Workers.MapItems.Execute(QueryOperationContext queryContext, TransactionOperationContext indexContext, Lazy`1 writeOperation, IndexingStatsScope stats, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53016\src\Raven.Server\Documents\Indexes\Workers\MapItems.cs:line 105
```

**Comment by ayende** [comment]
You need to use:
`                           where AsDateOnly(employee.DateTimeValue) < AsDateOnly(employee.DateOnlyValue).AddDays(-50) `

RavenDB cannot recognize DateOnly types during indexing, it needs the hint

**Comment by jac-dev** [comment]
All right, thanks for the quick reply.
