### ISSUE TITLE
RavenDB.Client > 5.3.100 dll not found error on m1

### ISSUE THREAD

**Issue by tobiaszuercher** [ravendb/ravendb#14401]
upgrading to 5.3.101 - 5.3.103 (latest) throws the following error on osx m1 when Initialize() on a DocumentStore is called:

```
System.DllNotFoundException: Unable to load shared library 'libzstd.mac.x64.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibzstd.mac.x64.dylib, 0x0001): tried: 'liblibzstd.mac.x64.dylib' (no such file), '/usr/local/lib/liblibzstd.mac.x64.dylib' (no such file), '/usr/lib/liblibzstd.mac.x64.dylib' (no such file), '/Users/tobi/git/xxxxxxx/xxx.API/liblibzstd.mac.x64.dylib' (no such file)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at Sparrow.Utils.DynamicNativeLibraryResolver.Resolver(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath) in C:\Builds\RavenDB-Stable-5.3\53023\src\Sparrow\Utils\DynamicNativeLibraryResolver.cs:line 63
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Sparrow.Utils.ZstdLib.ZSTD_compressBound(UIntPtr srcSize)
   at Sparrow.Utils.ZstdLib.GetMaxCompression(Int32 size) in C:\Builds\RavenDB-Stable-5.3\53023\src\Sparrow\Utils\ZstdLib.cs:line 51
   at Raven.Client.Documents.Conventions.DocumentConventions..cctor() in C:\Builds\RavenDB-Stable-5.3\53023\src\Raven.Client\Documents\Conventions\DocumentConventions.cs:line 159
```

whats a bit weird: it looks for `libzstd.mac.x64.dylib` but says: tried: '**liblib**zstd.mac.x64.dylib' (no such file)

downgrade to 5.3.100 fixes the issue

env info:

```.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.3
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.301/

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  6.0.301 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download```

**Comment by ayende** [comment]
Can you try with the nightly (5.3.104)? 

https://ravendb.net/download#nightly

It should work there, we merged a bunch of stuff for M1.

**Comment by ayende** [comment]
Also, are you getting that in the debugger? Or does it throws out, this should be handled internally

**Comment by tobiaszuercher** [comment]
you're right, it's only in the debugger. if i press play it works. as a user, it's still a bit scary to see this / it's not clear this error message is ok or not.

> Can you try with the nightly (5.3.104)?
> 
> https://ravendb.net/download#nightly
> 
> It should work there, we merged a bunch of stuff for M1.

any chance to get a pre-release in nuget? 104-nightly?

**Comment by ayende** [comment]
Okay, that is a handled error, then. And should have no impact. You can mark that as skip in the deubgger.

The nightlies are here:

https://myget.org/feed/ravendb/package/nuget/RavenDB.Client
