### ISSUE TITLE
Can't start RavenDB pod on Kubernetes

### ISSUE THREAD

**Issue by InverMN** [ravendb/ravendb#14714]
Hello, I am trying to deploy RavenDB on Kubernetes, but I keep getting crashes on the Raven startup. Looks like its some sort of filesystem error.
 
```
Raven.Client.Exceptions.Server.ServerLoadFailureException: Failed to load system storage 
At /data/RavenData/System
 ---> System.InvalidOperationException: Errno: 22='Invalid argument' (rc=0) - 'Attempted to open journal file - Path: /data/RavenData/System/Journals/0000000000000000000.journal Size :65536'. FailCode=FailOpenFile.
   at Sparrow.Server.Platform.PalHelper.ThrowLastError(FailCodes rc, Int32 lastError, String msg) in C:\Builds\RavenDB-Stable-5.4\54001\src\Sparrow.Server\Platform\PalHelper.cs:line 38
   at Voron.Impl.Journal.JournalWriter..ctor(StorageEnvironmentOptions options, VoronPathSetting filename, Int64 size, JournalMode mode) in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\Impl\Journal\JournalWriter.cs:line 45
   at Voron.StorageEnvironmentOptions.DirectoryStorageEnvironmentOptions.<>c__DisplayClass19_0.<CreateJournalWriter>b__1() in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\StorageEnvironmentOptions.cs:line 510
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Sparrow.Utils.LazyWithExceptionRetry`1.get_Value() in C:\Builds\RavenDB-Stable-5.4\54001\src\Sparrow\Utils\LazyWithExceptionRetry.cs:line 28
   at Voron.StorageEnvironmentOptions.DirectoryStorageEnvironmentOptions.CreateJournalWriter(Int64 journalNumber, Int64 journalSize) in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\StorageEnvironmentOptions.cs:line 512
   at Voron.Impl.Journal.WriteAheadJournal.NextFile(Int32 numberOf4Kbs) in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\Impl\Journal\WriteAheadJournal.cs:line 132
   at Voron.Impl.Journal.WriteAheadJournal.WriteToJournal(LowLevelTransaction tx, String& journalFilePath, TimeSpan& writeToJournalDuration) in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\Impl\Journal\WriteAheadJournal.cs:line 1617
   at Voron.Impl.LowLevelTransaction.CommitStage2_WriteToJournal() in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\Impl\LowLevelTransaction.cs:line 1124
   at Voron.Impl.LowLevelTransaction.Commit() in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\Impl\LowLevelTransaction.cs:line 981
   at Voron.StorageEnvironment.CreateNewDatabase() in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\StorageEnvironment.cs:line 468
   at Voron.StorageEnvironment..ctor(StorageEnvironmentOptions options) in C:\Builds\RavenDB-Stable-5.4\54001\src\Voron\StorageEnvironment.cs:line 167
   at Raven.Server.Storage.Layout.StorageLoader.OpenEnvironmentWithPossibleLayoutUpdate(DirectoryStorageEnvironmentOptions options, StorageEnvironmentType type) in C:\Builds\RavenDB-Stable-5.4\54001\src\Raven.Server\Storage\Layout\StorageLoader.cs:line 40
   at Raven.Server.Storage.Layout.StorageLoader.OpenEnvironment(StorageEnvironmentOptions options, StorageEnvironmentType type) in C:\Builds\RavenDB-Stable-5.4\54001\src\Raven.Server\Storage\Layout\StorageLoader.cs:line 20
   at Raven.Server.ServerWide.ServerStore.Initialize() in C:\Builds\RavenDB-Stable-5.4\54001\src\Raven.Server\ServerWide\ServerStore.cs:line 742
   --- End of inner exception stack trace ---
   at Raven.Server.ServerWide.ServerStore.Initialize() in C:\Builds\RavenDB-Stable-5.4\54001\src\Raven.Server\ServerWide\ServerStore.cs:line 746
   at Raven.Server.RavenServer.Initialize() in C:\Builds\RavenDB-Stable-5.4\54001\src\Raven.Server\RavenServer.cs:line 301
   at Raven.Server.Program.Main(String[] args) in C:\Builds\RavenDB-Stable-5.4\54001\src\Raven.Server\Program.cs:line 182
```

I am deploying on Minikube with that simplified Terraform file
```
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "2.12.1"
    }
  }
}

provider "kubernetes" {
  config_path = "~/.kube/config"
}

resource "kubernetes_storage_class" "storage_class" {
  storage_provisioner = "kubernetes.io/no-provisioner"
  metadata {
    name = "ravendb-storage-class"
  }
  volume_binding_mode = "WaitForFirstConsumer"
  allow_volume_expansion = true
}

resource "kubernetes_persistent_volume" "ravendb_persistent_volume" {
  metadata {
    name = "ravendb-pv"
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    capacity = {
      storage = "20Gi"
    }
    persistent_volume_reclaim_policy = "Retain"
    storage_class_name = "ravendb-storage-class"
    volume_mode = "Filesystem"
    persistent_volume_source {
      local {
        path = "/tmp"
      }
    }
    node_affinity {
      required {
        node_selector_term {
          match_expressions {
            key = "kubernetes.io/hostname"
            operator = "In"
            values = ["minikube"]
          }
        }
      }
    }
  }
}

resource "kubernetes_persistent_volume_claim" "ravendb_persistent_volume_claim" {
  metadata {
    name = "ravendb-pcv"
  }
  spec {
    storage_class_name = "ravendb-storage-class"
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = "5Gi"
      }
    }
  }
}

resource "kubernetes_config_map" "ravendb_configmap" {
  metadata {
    name = "ravendb-settings"
    labels = {
      app = "ravendb"
    }
  }
  data = {
    ravendb-0 = file("./ravendb-settings.json")
  }
}

resource "kubernetes_stateful_set" "ravendb_stateful_set" {
  metadata {
    name = "ravendb"
    labels = {
      app = "ravendb"
    }
  }
  spec {
    service_name = "ravendb"
    selector {
      match_labels = {
        app = "ravendb"
      }
    }
    template {
      metadata {
        labels = {
          app = "ravendb"
        }
      }
      spec {
        container {
          name = "ravendb"
          command = ["/bin/sh", "-c", "/opt/RavenDB/Server/Raven.Server --config-path /config/$HOSTNAME"]
          image = "ravendb/ravendb:5.4.1-ubuntu.20.04-x64"

          port {
            name = "http-api"
            container_port = 8080
            protocol = "TCP"
          }
          port {
            name = "tcp-server"
            container_port = 38888
            protocol = "TCP"
          }
          port {
            name = "snmp"
            container_port = 161
            protocol = "TCP"
          }

          volume_mount {
            name = "data"
            mount_path = "/data"
          }
          volume_mount {
            name = "config"
            mount_path = "/config"
          }
        }

        volume {
          name = "data"
          persistent_volume_claim {
            claim_name = "ravendb-pcv"
          }
        }
        volume {
          name = "config"
          config_map {
            name = "ravendb-settings"
          }
        }
      }
    }
    replicas = "1"
  }
}
```

And my `ravendb-settings.json` file is:
```
{
  "Setup.Mode": "None",
  "DataDir": "/data/RavenData",
  "ServerUrl.Tcp": "tcp://0.0.0.0:38888",
  "License.Eula.Accepted": true
}
```

That's a lot of code so I would be really grateful for some help

**Comment by ayende** [comment]
What file system are you deploying this on?
If you do `strace` on the container, what fails?

**Comment by InverMN** [comment]
My host OS is macOS Monterey 12.5, on it I run Docker with Minikube. So I guess the filesystem you are asking for is `osxfs`.

I cannot run strace: `Error from server (BadRequest): pod ravendb-0 does not have a host assigned`

I'll try to deploy it on AKS to know whenever the issue stays.

**Comment by ayende** [comment]
There is a failure to `open()` a file. 

Can you run the following (`C` code):

```
int fd = open(temp_file_name, O_WRONLY | O_DSYNC | O_DIRECT | O_CREAT, S_IWUSR | S_IRUSR);
```

And see what it gives you?

**Comment by InverMN** [comment]
That's code I ran

```
#define _GNU_SOURCE
#include <sys/stat.h>
#include <fcntl.h>
#include <stdio.h>

int main() {
  int fd = open("/data/RavenData/hello.txt", O_WRONLY | O_DSYNC | O_DIRECT | O_CREAT, S_IWUSR | S_IRUSR);
  printf("%d", fd);
  return 0;
}
```

And I got `-1`

**Comment by ayende** [comment]
Great, so that is the repro that is causing the problem.
Can you run: 

```
$ diskutil list
$ mount

```

**Comment by InverMN** [comment]
```
inver@MacBook-Pro-Pawel ~ % diskutil list
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         1.0 TB     disk0
   1:             Apple_APFS_ISC ⁨⁩                        524.3 MB   disk0s1
   2:                 Apple_APFS ⁨Container disk3⁩         994.7 GB   disk0s2
   3:        Apple_APFS_Recovery ⁨⁩                        5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +994.7 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume ⁨Macintosh HD⁩            15.4 GB    disk3s1
   2:              APFS Snapshot ⁨com.apple.os.update-...⁩ 15.4 GB    disk3s1s1
   3:                APFS Volume ⁨Preboot⁩                 447.1 MB   disk3s2
   4:                APFS Volume ⁨Recovery⁩                822.2 MB   disk3s3
   5:                APFS Volume ⁨Data⁩                    398.9 GB   disk3s5
   6:                APFS Volume ⁨VM⁩                      6.4 GB     disk3s6

inver@MacBook-Pro-Pawel ~ % mount        
/dev/disk3s1s1 on / (apfs, sealed, local, read-only, journaled)
devfs on /dev (devfs, local, nobrowse)
/dev/disk3s6 on /System/Volumes/VM (apfs, local, noexec, journaled, noatime, nobrowse)
/dev/disk3s2 on /System/Volumes/Preboot (apfs, local, journaled, nobrowse)
/dev/disk3s4 on /System/Volumes/Update (apfs, local, journaled, nobrowse)
/dev/disk1s2 on /System/Volumes/xarts (apfs, local, noexec, journaled, noatime, nobrowse)
/dev/disk1s1 on /System/Volumes/iSCPreboot (apfs, local, journaled, nobrowse)
/dev/disk1s3 on /System/Volumes/Hardware (apfs, local, journaled, nobrowse)
/dev/disk3s5 on /System/Volumes/Data (apfs, local, journaled, nobrowse, protect)
map auto_home on /System/Volumes/Data/home (autofs, automounted, nobrowse)
inver@MacBook-Pro-Pawel ~ % 
```

**Comment by ayende** [comment]
```
    persistent_volume_source {
      local {
        path = "/tmp"
      }
    }
```

That is likely the problem.

Can you try to put that on a persistent location, instead?

**Comment by InverMN** [comment]
`/var` will be good?

**Comment by InverMN** [comment]
Okay, looks like it works. Thanks for help!
