### ISSUE TITLE
Compare exchange creation problem after the app is running for some time

### ISSUE THREAD

**Issue by adambajguz** [ravendb/ravendb#15120]
I've found a problem with compare exchange (cmpxchg) creation after the applicaiton is running for some time (about 15-25 minutes). I'm using recent Raven Server (running inside Docker) and Client (version 5.4.4). The bug can be reproduced using the app I've created https://github.com/adambajguz/ravendb-bugs/tree/main/CmpxchgBug.

After the application starts it is possible to create a cmpxchg but the next try causes the app to hang for a while waiting for server request, then to throw an exception.

```
dbug: Microsoft.Extensions.Hosting.Internal.Host[2]
      Hosting started
info: RavenDBLockingBugIsolated.DemoHostedService[0]
      Acquiring lock bug-cc37c526-2374-43c0-8c3c-c4899d6d571b--1
info: RavenDBLockingBugIsolated.DemoHostedService[0]
      Lock acquired bug-cc37c526-2374-43c0-8c3c-c4899d6d571b--1 after 00:00:00.1552011
info: RavenDBLockingBugIsolated.DemoHostedService[0]
      Acquiring lock bug-cc37c526-2374-43c0-8c3c-c4899d6d571b--2
crit: RavenDBLockingBugIsolated.DemoHostedService[0]
      An error occurred
      Raven.Client.Exceptions.RavenException: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Raven.Server.ServerWide.RachisLogIndexNotifications.WaitForIndexNotification(Int64 index, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 4482
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\RavenServerStartup.cs:line 253
       ---> System.Threading.Tasks.TaskCanceledException: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Raven.Server.ServerWide.RachisLogIndexNotifications.WaitForIndexNotification(Int64 index, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 4482
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\RavenServerStartup.cs:line 253
         --- End of inner exception stack trace ---
         at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, Action`1 additionalErrorInfo) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 119
         at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 1469
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 890
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token)
         at Raven.Client.Documents.Session.AsyncDocumentSession.SaveChangesAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 166
         at RavenDBLockingBugIsolated.DemoHostedService.TryAcquireAsync(IDocumentStore documentStore, String name, CancellationToken cancellationToken) in Y:\GitHub\PackSite\LIBRARIES\Library.Modeling\examples\RavenDBLockingBugIsolated\DemoHostedService.cs:line 117
         at RavenDBLockingBugIsolated.DemoHostedService.ExecuteAsync(CancellationToken stoppingToken) in Y:\GitHub\PackSite\LIBRARIES\Library.Modeling\examples\RavenDBLockingBugIsolated\DemoHostedService.cs:line 51
fail: Microsoft.Extensions.Hosting.Internal.Host[9]
      BackgroundService failed
      Raven.Client.Exceptions.RavenException: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Raven.Server.ServerWide.RachisLogIndexNotifications.WaitForIndexNotification(Int64 index, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 4482
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\RavenServerStartup.cs:line 253
       ---> System.Threading.Tasks.TaskCanceledException: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Raven.Server.ServerWide.RachisLogIndexNotifications.WaitForIndexNotification(Int64 index, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 4482
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\RavenServerStartup.cs:line 253
         --- End of inner exception stack trace ---
         at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, Action`1 additionalErrorInfo) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 119
         at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 1469
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 890
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token)
         at Raven.Client.Documents.Session.AsyncDocumentSession.SaveChangesAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 166
         at RavenDBLockingBugIsolated.DemoHostedService.TryAcquireAsync(IDocumentStore documentStore, String name, CancellationToken cancellationToken) in Y:\GitHub\PackSite\LIBRARIES\Library.Modeling\examples\RavenDBLockingBugIsolated\DemoHostedService.cs:line 117
         at RavenDBLockingBugIsolated.DemoHostedService.ExecuteAsync(CancellationToken stoppingToken) in Y:\GitHub\PackSite\LIBRARIES\Library.Modeling\examples\RavenDBLockingBugIsolated\DemoHostedService.cs:line 51
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
crit: Microsoft.Extensions.Hosting.Internal.Host[10]
      The HostOptions.BackgroundServiceExceptionBehavior is configured to StopHost. A BackgroundService has thrown an unhandled exception, and the IHost instance is stopping. To avoid this behavior, configure this to Ignore; however the BackgroundService will not be restarted.
      Raven.Client.Exceptions.RavenException: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Raven.Server.ServerWide.RachisLogIndexNotifications.WaitForIndexNotification(Int64 index, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 4482
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\RavenServerStartup.cs:line 253
       ---> System.Threading.Tasks.TaskCanceledException: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Sparrow.Server.AsyncManualResetEvent.WaitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Sparrow.Server\AsyncManualResetEvent.cs:line 65
   at Raven.Server.ServerWide.RachisLogIndexNotifications.WaitForIndexNotification(Int64 index, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\ServerWide\ClusterStateMachine.cs:line 4482
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\RavenServerStartup.cs:line 253
         --- End of inner exception stack trace ---
         at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, Action`1 additionalErrorInfo) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 119
         at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 1469
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 890
         at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token)
         at Raven.Client.Documents.Session.AsyncDocumentSession.SaveChangesAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 166
         at RavenDBLockingBugIsolated.DemoHostedService.TryAcquireAsync(IDocumentStore documentStore, String name, CancellationToken cancellationToken) in Y:\GitHub\PackSite\LIBRARIES\Library.Modeling\examples\RavenDBLockingBugIsolated\DemoHostedService.cs:line 117
         at RavenDBLockingBugIsolated.DemoHostedService.ExecuteAsync(CancellationToken stoppingToken) in Y:\GitHub\PackSite\LIBRARIES\Library.Modeling\examples\RavenDBLockingBugIsolated\DemoHostedService.cs:line 51
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
dbug: Microsoft.Extensions.Hosting.Internal.Host[3]
      Hosting stopping
dbug: Microsoft.Extensions.Hosting.Internal.Host[4]
      Hosting stopped

```

The above exception is a result of the Raven Server returning a 500 error:

```json
{
    "TrafficWatchType": "Http",
    "TimeStamp": "2022-10-14T12:53:25.2421386Z",
    "DatabaseName": "RavenDBLockingBugIsolated",
    "CustomInfo": "N/A",
    "ClientIP": "::ffff:192.168.0.120",
    "CertificateThumbprint": null,
    "RequestId": 10546,
    "HttpMethod": "POST",
    "ElapsedMilliseconds": 961757, // ~ 16 minutes!
    "ResponseStatusCode": 500,
    "RequestUri": "http://192.168.0.201:8080/databases/RavenDBLockingBugIsolated/bulk_docs?raft-request-id=6c3fb245-30cd-4597-9328-ad9161d6a355",
    "AbsoluteUri": "http://192.168.0.201:8080",
    "RequestSizeInBytes": 0,
    "ResponseSizeInBytes": 0,
    "Type": "None"
  },
```
The strange thing about this 500 response is also that the `CustomInfo` field has an `N/A`, while the valid 200 response contains a `CompareExchangePUT  <key>` value.

**Comment by ayende** [comment]
I looked into this, and I tried that on the `live-test` instance, with a delay of 2 minutes between the loops.

I'm not seeing any issue, I'm seeing the following output:

```
info: CmpxchgBug.DemoHostedService[0]
      Acquiring lock bug-a64d6057-9702-4131-bea1-393ec2383875--1
info: CmpxchgBug.DemoHostedService[0]
      Lock acquired bug-a64d6057-9702-4131-bea1-393ec2383875--1 after 00:00:00.3184182
info: CmpxchgBug.DemoHostedService[0]
      Acquiring lock bug-a64d6057-9702-4131-bea1-393ec2383875--2
info: CmpxchgBug.DemoHostedService[0]
      Lock acquired bug-a64d6057-9702-4131-bea1-393ec2383875--2 after 00:00:00.7041959
```

**Comment by ArieSLV** [comment]
I was able to reproduce the problem, but I can’t localize the cause yet. 
In the case of two minutes, there is really no problem. In the case of calling the method `TryAcquireAsync` with an interval of more than 25 minutes, the problem begins.

**Comment by adambajguz** [comment]
Good to hear that the problem is reproducible not only on my machine!

**Comment by ArieSLV** [comment]
Hi @adambajguz 

Link to the issue where you can trace the progress: https://issues.hibernatingrhinos.com/issue/RavenDB-19474/

**Comment by ayende** [comment]
Are you running as a cluster?

**Comment by adambajguz** [comment]
@ayende The compare exchange is created in a cluster wide transaction but I'm not running a cluster (there's only a single node).

**Comment by ArieSLV** [comment]
Hi @adambajguz!

The issue was fixed today:
https://github.com/ravendb/ravendb/pull/15282

This will be available in the next stable next week.
