### ISSUE TITLE
Support for JsonExtensionData

### ISSUE THREAD

**Issue by poostwoud** [ravendb/ravendb#15167]
Hi,

I'm trying to save a document with a property marked with the `JsonExtensionData` attribute:

```csharp
[JsonExtensionData]
public Dictionary<string, JToken> AdditionalData { get; set; } = new();
```

According to the Newtonsoft docs properties marked with this attribute are serialized with the entries as part of the parent and deserialized back into the property (when no matching properties are found; https://www.newtonsoft.com/json/help/html/DeserializeExtensionData.htm).

However Raven doesn't seem to serialize these properties. I've tried using `object` values for the dictionary as well, but this doesn't work.

I've used only [a-zA-Z] characters for the key, so this shouldn't be an issue as well.

Removing the attribute from the property registers the values nested, so it seems Raven somehow "recognizes" the attribute.

Is the attribute simply not supported by Raven, or is there a setting somewhere that needs to be configured to be able to use this feature?

Cheers,

Peter

**Comment by poostwoud** [comment]
In addition, it seems like the `@metadata` is being added to the property on deserialization (!):

![image](https://user-images.githubusercontent.com/6665466/197750971-49dd70cd-2703-4969-8a50-b7b819b288ad.png)

This is only done when applying the `JsonExtensionData` attribute.

**Comment by ayende** [comment]
Can you create a test case showing this behavior?

**Comment by poostwoud** [comment]
This should work with reference to Raven client:

```csharp
using Newtonsoft.Json;
using Raven.Client.Documents;
using System.Diagnostics;

namespace RavenJsonExtensionDataTest;

internal class Program
{
    private static void Main()
    {
        //***************************************************************************
        //***** Raven;
        //***************************************************************************
        const string ravenServerUrl = /* YOURS */;
        const string ravenDatabaseName = /* YOURS */;

        //***************************************************************************
        //***** Init poco's;
        //***************************************************************************

        //*****
        var pocoWithoutExtensionData = new PocoWithoutExtensionData
        {
            Id = Guid.Parse("7e190328-5f02-4b19-8370-4b03ae7cdddd").ToString(),
            Name = "Test document",
            Tags = new Dictionary<string, object>
            {
                ["TagKey1"] = "TagValue1",
                ["TagKey2"] = "TagValue2",
                ["TagKey3"] = "TagValue3"
            }
        };

        //*****
        var pocoWithExtensionData = new PocoWithExtensionData
        {
            Id = Guid.Parse("d7fe539c-9550-4b09-8c6a-b01b654e46bc").ToString(),
            Name = "Test document",
            Tags = new Dictionary<string, object>
            {
                ["TagKey1"] = "TagValue1",
                ["TagKey2"] = "TagValue2",
                ["TagKey3"] = "TagValue3"
            }
        };

        //***************************************************************************
        //***** Without extension data using Newtonsoft;
        //***************************************************************************
        {
            //***** Serialize;
            var jsonWithoutExtensionData = JsonConvert.SerializeObject(pocoWithoutExtensionData);
            Debug.Assert(jsonWithoutExtensionData == $"{{\"Id\":\"{pocoWithoutExtensionData.Id}\",\"Name\":\"Test document\",\"Tags\":{{\"TagKey1\":\"TagValue1\",\"TagKey2\":\"TagValue2\",\"TagKey3\":\"TagValue3\"}}}}", $"Unexpected json output: {jsonWithoutExtensionData}");

            //***** Deserialize;
            var deserializedPocoWithoutExtensionData = JsonConvert.DeserializeObject<PocoWithoutExtensionData>(jsonWithoutExtensionData);
            Debug.Assert(deserializedPocoWithoutExtensionData != null, "Deserialize failed");
            Debug.Assert(string.Equals(deserializedPocoWithoutExtensionData.Id, pocoWithoutExtensionData.Id, StringComparison.Ordinal), $"Id; Expected: {pocoWithoutExtensionData.Id}; Actual: {deserializedPocoWithoutExtensionData.Id}");
            Debug.Assert(string.Equals(deserializedPocoWithoutExtensionData.Name, pocoWithoutExtensionData.Name, StringComparison.Ordinal), $"Name; Expected: {pocoWithoutExtensionData.Name}; Actual: {deserializedPocoWithoutExtensionData.Name}");
            Debug.Assert(pocoWithoutExtensionData.Tags.Count == deserializedPocoWithoutExtensionData.Tags.Count, $"Tags count; Expected: {pocoWithoutExtensionData.Tags.Count}; Actual: {deserializedPocoWithoutExtensionData.Tags.Count}");
            foreach (var tag in deserializedPocoWithoutExtensionData.Tags)
            {
                Debug.Assert(pocoWithoutExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                Debug.Assert(pocoWithoutExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
            }

            foreach (var tag in pocoWithoutExtensionData.Tags)
            {
                Debug.Assert(deserializedPocoWithoutExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                Debug.Assert(deserializedPocoWithoutExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
            }
        }

        //***************************************************************************
        //***** With extension data using Newtonsoft;
        //***************************************************************************
        {
            //***** Serialize;
            var jsonWithExtensionData = JsonConvert.SerializeObject(pocoWithExtensionData);
            Debug.Assert(jsonWithExtensionData == $"{{\"Id\":\"{pocoWithExtensionData.Id}\",\"Name\":\"Test document\",\"TagKey1\":\"TagValue1\",\"TagKey2\":\"TagValue2\",\"TagKey3\":\"TagValue3\"}}", $"Unexpected json output: {jsonWithExtensionData}");

            //***** Deserialize;
            var deserializedPocoWithExtensionData = JsonConvert.DeserializeObject<PocoWithExtensionData>(jsonWithExtensionData);
            Debug.Assert(deserializedPocoWithExtensionData != null, "Deserialize failed");
            Debug.Assert(string.Equals(deserializedPocoWithExtensionData.Id, pocoWithExtensionData.Id, StringComparison.Ordinal), $"Id; Expected: {pocoWithExtensionData.Id}; Actual: {deserializedPocoWithExtensionData.Id}");
            Debug.Assert(string.Equals(deserializedPocoWithExtensionData.Name, pocoWithExtensionData.Name, StringComparison.Ordinal), $"Name; Expected: {pocoWithExtensionData.Name}; Actual: {deserializedPocoWithExtensionData.Name}");
            Debug.Assert(pocoWithExtensionData.Tags.Count == deserializedPocoWithExtensionData.Tags.Count, $"Tags count; Expected: {pocoWithExtensionData.Tags.Count}; Actual: {deserializedPocoWithExtensionData.Tags.Count}");
            foreach (var tag in deserializedPocoWithExtensionData.Tags)
            {
                Debug.Assert(pocoWithExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                Debug.Assert(pocoWithExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
            }

            foreach (var tag in pocoWithExtensionData.Tags)
            {
                Debug.Assert(deserializedPocoWithExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                Debug.Assert(deserializedPocoWithExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
            }
        }

        //***************************************************************************
        //***** Initialize Raven;
        //***************************************************************************
        using var documentStore = new DocumentStore
        {
            Urls = new[] { ravenServerUrl },
            Database = ravenDatabaseName
        };

        //*****
        documentStore.Initialize();

        //***************************************************************************
        //***** Without extension data using Raven;
        //***************************************************************************
        {
            //***** Store;
            using (var session = documentStore.OpenSession())
            {
                session.Store(pocoWithoutExtensionData, pocoWithoutExtensionData.Id);
                session.SaveChanges();
            }

            //***** Load;
            using (var session = documentStore.OpenSession())
            {
                var deserializedPocoWithoutExtensionData = session.Load<PocoWithoutExtensionData>(pocoWithoutExtensionData.Id);
                Debug.Assert(deserializedPocoWithoutExtensionData != null, "Deserialize failed");
                Debug.Assert(string.Equals(deserializedPocoWithoutExtensionData.Id, pocoWithoutExtensionData.Id, StringComparison.Ordinal), $"Id; Expected: {pocoWithoutExtensionData.Id}; Actual: {deserializedPocoWithoutExtensionData.Id}");
                Debug.Assert(string.Equals(deserializedPocoWithoutExtensionData.Name, pocoWithoutExtensionData.Name, StringComparison.Ordinal), $"Name; Expected: {pocoWithoutExtensionData.Name}; Actual: {deserializedPocoWithoutExtensionData.Name}");
                Debug.Assert(pocoWithoutExtensionData.Tags.Count == deserializedPocoWithoutExtensionData.Tags.Count, $"Tags count; Expected: {pocoWithoutExtensionData.Tags.Count}; Actual: {deserializedPocoWithoutExtensionData.Tags.Count}");
                foreach (var tag in deserializedPocoWithoutExtensionData.Tags)
                {
                    Debug.Assert(pocoWithoutExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                    Debug.Assert(pocoWithoutExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
                }

                foreach (var tag in pocoWithoutExtensionData.Tags)
                {
                    Debug.Assert(deserializedPocoWithoutExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                    Debug.Assert(deserializedPocoWithoutExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
                }
            }
        }

        //***************************************************************************
        //***** With extension data using Raven;
        //***************************************************************************
        {
            //***** Store;
            using (var session = documentStore.OpenSession())
            {
                session.Store(pocoWithExtensionData, pocoWithExtensionData.Id);
                session.SaveChanges();
            }

            //***** Load;
            using (var session = documentStore.OpenSession())
            {
                var deserializedPocoWithExtensionData = session.Load<PocoWithExtensionData>(pocoWithExtensionData.Id);
                Debug.Assert(deserializedPocoWithExtensionData != null, "Deserialize failed");
                Debug.Assert(string.Equals(deserializedPocoWithExtensionData.Id, pocoWithExtensionData.Id, StringComparison.Ordinal), $"Id; Expected: {pocoWithExtensionData.Id}; Actual: {deserializedPocoWithExtensionData.Id}");
                Debug.Assert(string.Equals(deserializedPocoWithExtensionData.Name, pocoWithExtensionData.Name, StringComparison.Ordinal), $"Name; Expected: {pocoWithExtensionData.Name}; Actual: {deserializedPocoWithExtensionData.Name}");
                Debug.Assert(pocoWithExtensionData.Tags.Count == deserializedPocoWithExtensionData.Tags.Count, $"Tags count; Expected: {pocoWithExtensionData.Tags.Count}; Actual: {deserializedPocoWithExtensionData.Tags.Count}");
                foreach (var tag in deserializedPocoWithExtensionData.Tags)
                {
                    Debug.Assert(pocoWithExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                    Debug.Assert(pocoWithExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
                }

                foreach (var tag in pocoWithExtensionData.Tags)
                {
                    Debug.Assert(deserializedPocoWithExtensionData.Tags.ContainsKey(tag.Key), $"Contains {tag.Key}; Expected: true; Actual: false");
                    Debug.Assert(deserializedPocoWithExtensionData.Tags.TryGetValue(tag.Key, out var tagValue) && Equals(tagValue, tag.Value), $"Value {tag.Key}; Expected: {tag.Value}; Actual: {tagValue}");
                }
            }
        }
    }
}

public sealed class PocoWithoutExtensionData
{
    public string Id { get; set; }

    public string Name { get; set; }

    public Dictionary<string, object> Tags { get; set; } = new();
}

public sealed class PocoWithExtensionData
{
    public string Id { get; set; }

    public string Name { get; set; }

    [JsonExtensionData]
    public Dictionary<string, object> Tags { get; set; } = new();
}
```

And should output something like:

```
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Tags count; Expected: 3; Actual: 1
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 164
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Contains @metadata; Expected: true; Actual: false
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 167
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Value @metadata; Expected: {
  "@collection": "PocoWithExtensionDatas",
  "Raven-Clr-Type": "RavenJsonExtensionDataTest.PocoWithExtensionData, RavenJsonExtensionDataTest",
  "@change-vector": "A:47-lHD0CkPRL0K8OHn79Xk22A",
  "@id": "d7fe539c-9550-4b09-8c6a-b01b654e46bc",
  "@last-modified": "2022-10-25T13:18:16.1531968Z"
}; Actual: 
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 168
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Contains TagKey1; Expected: true; Actual: false
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 173
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Value TagKey1; Expected: TagValue1; Actual: 
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 174
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Contains TagKey2; Expected: true; Actual: false
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 173
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Value TagKey2; Expected: TagValue2; Actual: 
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 174
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Contains TagKey3; Expected: true; Actual: false
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 173
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
Value TagKey3; Expected: TagValue3; Actual: 
---- Assert Long Message ----

   at RavenJsonExtensionDataTest.Program.Main() in Program.cs:line 174
```

**Comment by ayende** [comment]
The reason behind that is that RavenDB has a feature that uses json extensions data

This is from almost 8 years ago, but it shows the gist:


> Missing properties retention. This one is probably the first feature that we developed strictly for 3.0. The issue is what happens when you load a document from the database, but it has extra properties. What do I mean by that? Imagine that we changed our code to remove the FullName property. However, all our documents retain that property. In 2.5, loading and saving the document would overwrite the existing document with the new one, without the property. We got feedback from customers that this wasn’t a desirable behavior. Now, even though the FullName property isn’t accessible from your model, it will be retained (even if you have made changes to other properties).


If we disable this feature, you'll need to deal with things like the `@metadata` property, which is otherwise handled, etc.

You can handle that better using a `Dictionary` for dynamic values.
