### ISSUE TITLE
Potential regression of CompareExchange handling in the session in 5.4.4

### ISSUE THREAD

**Issue by danielmarbach** [ravendb/ravendb#15247]
One of [our `SaveChangesAsync`](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Outbox/OutboxPersister.cs#L174) calls started throwing `NullReferenceException` with the following stack trace when upgrading to the 5.4.4 client.

```
 at Raven.Client.Documents.Session.ClusterTransactionOperationsBase.CompareExchangeSessionValue.GetCommand(DocumentConventions conventions, JsonOperationContext context, IJsonSerializer jsonSerializer) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\ClusterTransactionSession.cs:line 395
   at Raven.Client.Documents.Session.ClusterTransactionOperationsBase.PrepareCompareExchangeEntities(SaveChangesData result) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\ClusterTransactionSession.cs:line 264
   at Raven.Client.Documents.Session.InMemoryDocumentSessionOperations.PrepareCompareExchangeEntities(SaveChangesData result) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\InMemoryDocumentSessionOperations.cs:line 925
   at Raven.Client.Documents.Session.InMemoryDocumentSessionOperations.PrepareForSaveChanges() in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\InMemoryDocumentSessionOperations.cs:line 869
   at Raven.Client.Documents.Session.Operations.BatchOperation.CreateRequest() in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\Operations\BatchOperation.cs:line 34
   at Raven.Client.Documents.Session.AsyncDocumentSession.SaveChangesAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 158
```

It might be related to the changes done in, but I didn't do more research yet.

> [Session] fixed issue with Compare Exchange metadata not marking values as dirty so they are ignored during 'SaveChanges'

when I downgrade the code to use 5.4.2 everything works as before.

This [is the dependabot PR](https://github.com/Particular/NServiceBus.RavenDB/pull/1006) that caught this in our CI/CD environment

**Comment by danielmarbach** [comment]
Pushed a [new commit](https://github.com/Particular/NServiceBus.RavenDB/pull/1006/commits/8625a8b49c4bfb17153384c7fc390379665d4a12) that downgrades to 5.4.2.

To verify also on the build server that 5.4.2 indeed resolves the issue (I've only verified it locally so far)

**Comment by grisha-kotler** [comment]
Hi Daniel,

The issue was already fixed a few days ago: 
https://github.com/ravendb/ravendb/pull/15228

This will be available in the next stable in about 2 weeks.

**Comment by danielmarbach** [comment]
That is great! Thanks for letting me know. Closing
