### ISSUE TITLE
.NET 7 Index Creation Bug

### ISSUE THREAD

**Issue by JohnGalt1717** [ravendb/ravendb#15294]
Consider the following index:

```
public class TokenByExpirationDate : AbstractIndexCreationTask<AuthToken> {
	public TokenByExpirationDate() {
		Map = tokens => from t in tokens
						select new {
							t.Id,
							t.ExpirationDate
						};
	}
}
```

When you try and create the index you get the following:

```
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Lucene.Net.Documents;
using Raven.Client.Documents.Indexes;
using Raven.Server.Documents.Indexes.Static;
using Raven.Server.Documents.Indexes.Static.Linq;
using Raven.Server.Documents.Indexes.Static.Extensions;

namespace Raven.Server.Documents.Indexes.Static.Generated
{
    public class Index_TokenByExpirationDate : StaticIndexBase
    {
        public Index_TokenByExpirationDate()
        {
            this.AddMap("AuthTokens\"]", docs => docs[@"System.Select(t => new
            {
                Id = Id(t),
                ExpirationDate = t.ExpirationDate
            }));
            this.OutputFields = new System.String[] { "Id", "ExpirationDate" };
            this.StackSizeInSelectClause = 0;
        }
    }
}

(25,56): error CS1003: Syntax error, ',' expected
(25,58): error CS1003: Syntax error, ',' expected
(25,62): error CS1003: Syntax error, ',' expected
(25,76): error CS1003: Syntax error, ',' expected
(25,76): error CS1010: Newline in constant
(25,80): error CS1003: Syntax error, ',' expected
(26,45): error CS1003: Syntax error, ']' expected
(26,45): error CS1026: ) expected
(25,62): error CS0103: The name 'ExpirationDate' does not exist in the current context
, IndexDefinitionProperty='', ProblematicText=''   at Raven.Server.Documents.Indexes.Static.IndexCompiler.CompileInternal(String originalName, String cSharpSafeName, MemberDeclarationSyntax class, IndexDefinition definition) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Indexes\Static\IndexCompiler.cs:line 243
   at Raven.Server.Documents.Indexes.Static.IndexCompiler.Compile(IndexDefinition definition) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Indexes\Static\IndexCompiler.cs:line 169
   at Raven.Server.Documents.Indexes.Static.IndexCompilationCache.GenerateIndex(IndexDefinition definition, RavenConfiguration configuration, IndexType type, Int64 indexVersion) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Indexes\Static\IndexCompilationCache.cs:line 148
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Raven.Server.Documents.Indexes.Static.IndexCompilationCache.GetDocumentsIndexInstance(IndexDefinition definition, RavenConfiguration configuration, IndexType type, Int64 indexVersion) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Indexes\Static\IndexCompilationCache.cs:line 57
   at Raven.Server.Documents.Indexes.Static.IndexCompilationCache.GetIndexInstance(IndexDefinition definition, RavenConfiguration configuration, Int64 indexVersion) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Indexes\Static\IndexCompilationCache.cs:line 40
   at Raven.Server.Documents.Indexes.IndexStore.ValidateStaticIndex(IndexDefinition definition) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Indexes\IndexStore.cs:line 1054
   at Raven.Server.Documents.Indexes.IndexStore.CreateIndexInternal(IndexDefinition definition, String raftRequestId, String source) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Indexes\IndexStore.cs:line 935
   at Raven.Server.Documents.Handlers.Admin.AdminIndexHandler.PutInternal(Boolean validatedAsAdmin) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Handlers\Admin\AdminIndexHandler.cs:line 107
   at Raven.Server.Documents.Handlers.Admin.AdminIndexHandler.Put() in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Documents\Handlers\Admin\AdminIndexHandler.cs:line 36
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Server\RavenServerStartup.cs:line 253, IndexDefinitionProperty='', ProblematicText=''   at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, Action`1 additionalErrorInfo) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 123
   at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 1469
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 890
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Http\RequestExecutor.cs:line 916
   at Raven.Client.Documents.Operations.MaintenanceOperationExecutor.SendAsync[TResult](IMaintenanceOperation`1 operation, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Operations\MaintenanceOperationExecutor.cs:line 61
   at Raven.Client.Documents.Indexes.IndexCreation.CreateIndexesAsync(IEnumerable`1 indexes, IDocumentStore store, DocumentConventions conventions, String database, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54012\src\Raven.Client\Documents\Indexes\IndexCreation.cs:line 79
   --- End of inner exception stack trace ---

```

This same index worked fine in .net 7 RC2 but now fails in .net 7 final.

**Comment by maciejaszyk** [comment]
Hey,
I tried to reproduce it but everything looks just fine. I've used a console app with `.NET7.0` target and `.NET7.0.0` runtime. As a server, I've used our live test (http://live-test.ravendb.net/). Can you send us more information about how did you get the exception?  It would be great if you can create a test/program that reproduces the issue.

**Comment by JohnGalt1717** [comment]
> Hey, I tried to reproduce it but everything looks just fine. I've used a console app with `.NET7.0` target and `.NET7.0.0` runtime. As a server, I've used our live test (http://live-test.ravendb.net/). Can you send us more information about how did you get the exception? It would be great if you can create a test/program that reproduces the issue.

I think that the issue is in the Collection name having a . in it.  I.e. System.Tokens is the collection in Raven which breaks, but using System_Tokens doesn't.

**Comment by maciejaszyk** [comment]
Did you make any modifications for document conventions in `DocumentStore`? If so, can you show them?

**Comment by JohnGalt1717** [comment]
```
return new DocumentConventions {
			SaveEnumsAsIntegers = true,
			Serialization = new NewtonsoftJsonSerializationConventions {
				JsonContractResolver = new StrictTypeContractResolver(),
			},
			MaxNumberOfRequestsPerSession = overrideMaxRequests ? int.MaxValue : 150,
			FindCollectionName = (type) => type.GetCustomAttribute<CollectionAttribute>(true)?.CollectionName ?? throw new InvalidOperationException($"{type} does not have a collection attribute."),

		};
```

ClllectionAttribute is just an attribute we put on the entity to determine where it should be stored. That's where it is getting System.Tokens which breaks where System_Tokens doesn't if we change it.

StrictTypeContractResolver() is from @ayende,  to fix an issue we were having with inheritance.

**Comment by maciejaszyk** [comment]
Ok, I've couple more questions:
Can you show the code for `StrictTypeContractResolver`?
What is the namespace of `TokenByExpirationDate`? I'm asking because you mentioned your  `System.` namespace but I don't see it here.
Can you send me an index map string of this index generated by your client? It's a property of `Index Definition`. To get it just run:
```new IndexName().CreateIndexDefinition().```
and the value is saved in `HashMap<string> as `Maps`.

**Comment by ayende** [comment]
Better yet, can you share a small command line / test case that show this again the live-test server?

This looks very much like a configuration issue that is causing this.
