### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by AnjanaRatnayake** [ravendb/ravendb#15400]
Hey, I found a NullReferenceException, this was the stack trace leading up to this exception.

```
2022-12-06T12:13:35.6415683Z, 25, Information, ?, Raven.Server.Rachis.RachisConsensus, Follower Ambassador for C in term 51: sending Rachis hello to C
2022-12-06T12:13:35.6415776Z, 25, Information, A > C, Raven.Server.Rachis.Remote.RemoteConnection, A says hello to C with AppendEntries
2022-12-06T12:13:35.6650376Z, 29, Information, ?, Raven.Server.Rachis.RachisConsensus, Leader A in term 51:VoteOfNoConfidence
Triggered because of:
C - 491.45 ms
B - 533.443 ms
C: Got last reply 533 ms ago and sent 23 ms (Hello) - Connected with C - Running
B: Got last reply 575 ms ago and sent 574 ms (Heartbeat) - Connected with B - Running

2022-12-06T12:13:35.6650934Z, 29, Information, ?, Raven.Server.Rachis.RachisConsensus, Error when running leader behavior, EXCEPTION: System.TimeoutException: Too long has passed since we got a confirmation from the majority of the cluster that this node is still the leader.
Assuming that I'm not the leader and stepping down.
Triggered because of:
C - 491.45 ms
B - 533.443 ms
C: Got last reply 533 ms ago and sent 23 ms (Hello) - Connected with C - Running
B: Got last reply 575 ms ago and sent 574 ms (Heartbeat) - Connected with B - Running

at Raven.Server.Rachis.Leader.VoteOfNoConfidence() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 428
at Raven.Server.Rachis.Leader.EnsureThatWeHaveLeadership(Int32 majority) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 540
at Raven.Server.Rachis.Leader.Run() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 338
2022-12-06T12:13:35.6651400Z, 29, Information, ?, Raven.Server.Rachis.RachisConsensus, Switching to candidate state because An error occurred during our leadership.
System.TimeoutException: Too long has passed since we got a confirmation from the majority of the cluster that this node is still the leader.
Assuming that I'm not the leader and stepping down.
Triggered because of:
C - 491.45 ms
B - 533.443 ms
C: Got last reply 533 ms ago and sent 23 ms (Hello) - Connected with C - Running
B: Got last reply 575 ms ago and sent 574 ms (Heartbeat) - Connected with B - Running

at Raven.Server.Rachis.Leader.VoteOfNoConfidence() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 428
at Raven.Server.Rachis.Leader.EnsureThatWeHaveLeadership(Int32 majority) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 540
at Raven.Server.Rachis.Leader.Run() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 338 forced: False
2022-12-06T12:13:35.6659875Z, 32, Information, Server, Raven.Server.RavenServerStartup, POST /databases/Bank/bulk_docs? - 201 - 673 ms
2022-12-06T12:13:35.6661738Z, 20, Information, ?, Raven.Server.Rachis.RachisConsensus, Follower Ambassador for B in term 51: waited long time (560) to read a single response from stream (failed).
2022-12-06T12:13:35.6860948Z, 20, Information, ?, Raven.Server.Rachis.RachisConsensus, Follower Ambassador for B in term 51: failure to append entries to B because: A negative Append Entries Response after the connection has been established shouldn't happen. Message: The current term that I have 52 doesn't match 51
2022-12-06T12:13:35.7180205Z, 42, Information, ?, Raven.Server.Rachis.RachisConsensus, Received (Real) 'RequestVote' from C: Election is InProgress in term 52 while our current term is 51, Forced election is False. (Sent from:28)
2022-12-06T12:13:35.7378298Z, 29, Information, ?, Raven.Server.Rachis.RachisConsensus, 12/06/2022 12:13:35, State changed: Leader -> Candidate in term 51, because An error occurred during our leadership.
System.TimeoutException: Too long has passed since we got a confirmation from the majority of the cluster that this node is still the leader.
Assuming that I'm not the leader and stepping down.
Triggered because of:
C - 491.45 ms
B - 533.443 ms
C: Got last reply 533 ms ago and sent 23 ms (Hello) - Connected with C - Running
B: Got last reply 575 ms ago and sent 574 ms (Heartbeat) - Connected with B - Running

at Raven.Server.Rachis.Leader.VoteOfNoConfidence() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 428
at Raven.Server.Rachis.Leader.EnsureThatWeHaveLeadership(Int32 majority) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 540
at Raven.Server.Rachis.Leader.Run() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Leader.cs:line 338
2022-12-06T12:13:35.7380719Z, 19, Information, ?, Raven.Server.Rachis.RachisConsensus, Initiate disposing the term _prior_ to 51 with 5 things to dispose.
2022-12-06T12:13:35.7380812Z, 19, Information, ?, Raven.Server.Rachis.RachisConsensus, Start disposing leader A of term 51.
2022-12-06T12:13:35.7380905Z, 19, Information, ?, Raven.Server.Rachis.RachisConsensus, Dispose Follower Ambassador for C in term 51
2022-12-06T12:13:35.7434363Z, 28, Information, ?, Raven.Server.Rachis.RachisConsensus, Candidate A: Starting elections
2022-12-06T12:13:35.7449171Z, 45, Information, Bank, Raven.Server.Documents.DocumentDatabase, Starting to process record 810 (current 810) for Bank.
2022-12-06T12:13:35.7449637Z, 45, Information, Bank, Raven.Server.Documents.DocumentDatabase, Finish to process record 810 for Bank.
2022-12-06T12:13:35.7450102Z, 45, Information, YourDatabaseName, Raven.Server.Documents.DocumentDatabase, Starting to process record 9 (current 9) for YourDatabaseName.
2022-12-06T12:13:35.7526471Z, 31, Information, Bank, Raven.Server.Documents.TransactionOperationsMerger, Merged 4 operations in 00:00:00.1201126 (async) with 40 operations remaining. Status: HasMore
2022-12-06T12:13:35.7526750Z, 31, Information, Bank, Raven.Server.Documents.TransactionOperationsMerger, EndAsyncCommit on 3316
2022-12-06T12:13:35.7527682Z, 31, Information, Bank, Raven.Server.Documents.TransactionOperationsMerger, BeginAsyncCommit on 3317 with 40 additional operations pending
2022-12-06T12:13:35.7530848Z, 44, Information, ?, Raven.Server.Rachis.RachisConsensus, Dispose Follower Ambassador for C in term 51
2022-12-06T12:13:35.7558043Z, 42, Information, ?, Raven.Server.Rachis.RachisConsensus, Elector A for C: Disposing
2022-12-06T12:13:35.7558135Z, 42, Information, ?, Raven.Server.Rachis.RachisConsensus, Failed to talk to candidate: A, EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
at Raven.Server.Rachis.Elector.HandleVoteRequest() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\Elector.cs:line 168
```

**Comment by ayende** [comment]
This is a race condition here, probably:
https://github.com/ravendb/ravendb/blob/c193781b4850b95b69c18dbabdb7ff636ea343cc/src/Raven.Server/Rachis/Elector.cs#L170

The impact is the same (rejecting the voting), nothing major

**Comment by AnjanaRatnayake** [comment]
```
2022-12-07T16:12:27.4394501Z, 18, Information, ?, Raven.Server.Rachis.RachisConsensus, Dispose Follower Ambassador for C in term 7
2022-12-07T16:12:27.4609450Z, 24, Information, ?, Raven.Server.Rachis.RachisConsensus, Elector B for A: Disposing
2022-12-07T16:12:27.4610847Z, 30, Information, ?, Raven.Server.Rachis.RachisConsensus, Follower Ambassador for A in term 7: Node A is finished with the message 'Closed'.
2022-12-07T16:12:27.4619136Z, 20, Information, ?, Raven.Server.Rachis.RachisConsensus, Leader B of term 7 was disposed
2022-12-07T16:12:27.5403608Z, 25, Information, B > A, Raven.Server.Rachis.Remote.RemoteConnection, Install snapshot response in -1, last log index: -1, Done: False
2022-12-07T16:12:27.6840001Z, 36, Information, ?, Raven.Server.Rachis.RachisConsensus, Dispose CandidateAmbassador for B after the elections were Lost
2022-12-07T16:12:27.6860584Z, 36, Information, ServerStore, Raven.Server.ServerWide.ServerStore, Unable to notify about cluster topology change, EXCEPTION: Raven.Client.Exceptions.RavenException: System.NullReferenceException: Object reference not set to an instance of an object.
at Raven.Server.Rachis.RachisConsensus.GetClusterErrorsFromLeader() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\RachisConsensus.cs:line 2303
at Raven.Server.ServerWide.ServerStore.GetClusterErrors() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ServerStore.cs:line 2841
at Raven.Server.Documents.Handlers.Admin.RachisAdminHandler.GetClusterTopology() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\RachisAdminHandler.cs:line 244
at Raven.Server.Documents.Handlers.Admin.RachisAdminHandler.GetClusterTopology() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\RachisAdminHandler.cs:line 251
at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Routing\RequestRouter.cs:line 358
at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\RavenServerStartup.cs:line 176
---> System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
at Raven.Server.Rachis.RachisConsensus.GetClusterErrorsFromLeader() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\RachisConsensus.cs:line 2303
at Raven.Server.ServerWide.ServerStore.GetClusterErrors() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ServerStore.cs:line 2841
at Raven.Server.Documents.Handlers.Admin.RachisAdminHandler.GetClusterTopology() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\RachisAdminHandler.cs:line 244
at Raven.Server.Documents.Handlers.Admin.RachisAdminHandler.GetClusterTopology() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\RachisAdminHandler.cs:line 251
at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Routing\RequestRouter.cs:line 358
at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\RavenServerStartup.cs:line 176
--- End of inner exception stack trace ---
```
Here is another log where I am seeing a different NullReferenceException due to a race condition.

**Comment by ayende** [comment]
https://issues.hibernatingrhinos.com/issue/RavenDB-19632/Failed-to-talk-to-candidate-A-EXCEPTION-System.NullReferenceException-Object-reference-not-set-to-an-instance-of-an-object.

**Comment by AnjanaRatnayake** [comment]
```
        2022-12-07T16:12:27.3341268Z, 20, Information, ?, Raven.Server.Rachis.RachisConsensus, Initiate disposing the term _prior_ to 7 with 7 things to dispose.
        2022-12-07T16:12:27.3341361Z, 20, Information, ?, Raven.Server.Rachis.RachisConsensus, Start disposing leader B of term 7.
        2022-12-07T16:12:27.3341454Z, 20, Information, ?, Raven.Server.Rachis.RachisConsensus, Dispose Follower Ambassador for C in term 7
        2022-12-07T16:12:27.3344528Z, 26, Information, ?, Raven.Server.Rachis.RachisConsensus, Candidate B: Starting elections
        2022-12-07T16:12:27.3395844Z, 27, Information, ?, Raven.Server.Rachis.RachisConsensus, Follower Ambassador for C in term 7: waited long time (443) to read a single response from stream (failed).
        2022-12-07T16:12:27.3587417Z, 30, Information, ?, Raven.Server.Rachis.RachisConsensus, Got 1st LogLengthNegotiationResponse from A with term 7 (0 / 0) Acceptable, version: 54001
        2022-12-07T16:12:27.3587509Z, 30, Information, ?, Raven.Server.Rachis.RachisConsensus, Follower Ambassador for A in term 7: A agreed on term=7 index=30
        2022-12-07T16:12:27.3588255Z, 30, Information, ?, Raven.Server.Rachis.RachisConsensus, Follower Ambassador for A in term 7: sending empty snapshot to A
        2022-12-07T16:12:27.3588348Z, 30, Information, B > A, Raven.Server.Rachis.Remote.RemoteConnection, Install snapshot on: (30 / 7)
        2022-12-07T16:12:27.3743786Z, 25, Information, Server, Raven.Server.RavenServerStartup, GET /cluster/topology?A - 500 - 50 ms, EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
        at Raven.Server.Rachis.RachisConsensus.GetClusterErrorsFromLeader() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\RachisConsensus.cs:line 2303
        at Raven.Server.ServerWide.ServerStore.GetClusterErrors() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ServerStore.cs:line 2841
        at Raven.Server.Documents.Handlers.Admin.RachisAdminHandler.GetClusterTopology() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\RachisAdminHandler.cs:line 244
        at Raven.Server.Documents.Handlers.Admin.RachisAdminHandler.GetClusterTopology() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\RachisAdminHandler.cs:line 251
        at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Routing\RequestRouter.cs:line 358
        at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\RavenServerStartup.cs:line 176
```
Here is another sequence of events leading to the same NullReferenceException as issue above

**Comment by ayende** [comment]
Those are all meant to be fairly rare scenarios (note that they are basically harmless, error is raised and a single request fails).
How are you reproducing them so successfully

**Comment by davidsearle-antithesis** [comment]
Hi Oren - Anjana's been using the Antithesis tech to seek out these conditions to manifest the issues. Would be great to get on a call to show you what he's been doing. With your help I'm sure we can find even more!

**Comment by ayende** [comment]
I'm not familiar with `Antithesis`, can you send a link?

**Comment by mcrio** [comment]
I guess the intro video at www.antithesis.com explains the fact they are reproducing this rare condition

**Comment by davidsearle-antithesis** [comment]
Thanks Nikola. That video should definitely help.

**Comment by davidsearle-antithesis** [comment]
> I'm not familiar with `Antithesis`, can you send a link?

Oren - With your input I think we could offer up more bugs too.

**Comment by ayende** [comment]
Ping us at support@ravendb.net please with details

**Comment by davidsearle-antithesis** [comment]
Oren - Email sent.

If you want specifics about how we managed to get the bug to manifest please let me know. I can provide logs and specific environment conditions set to make this happen.
