### ISSUE TITLE
Performance during migration

### ISSUE THREAD

**Issue by jgaudetMcc** [ravendb/ravendb#15434]
We are in the mist of migrating 2.5 million docs from share point to raven....we are experiencing a really slow performance issue right now...during our migration. it was fine so far...although the nodes go down once in a while....encountering an unexpected error on the initial handshake.......each of our nodes are on different vm...on the same datacenter.....

Any hints on how to make this better? is this normal behavior that we see in attached picture....thank you!

Attached a picture of our cluster:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/120476520/207352212-153b3235-ffe7-4f45-85ae-94ac9e52f9ea.png)
 storage

**Comment by ayende** [comment]
What do you get in the log?
Given the size of the db in question, I assume that you are writing a LOT of data.
Are you running in the cloud? Is it possible that you are pushing a lot of writes and burned through all of your IOPS budget?

Are you seeing any alerts / notifications in the studio?

**Comment by jgaudetMcc** [comment]
We are writing a lot of data and we have pdfs or jpegs with most documents.
We are not in a cloud; this is on premises.
Other than a few initial handshake issues we see nothing wrong in the alerts on the studio. we did get a not enough memory at one point and we increased the physical memory. As you can see we have 12gb of ram per vm and 1.8 tb of hard disks...
There is no errors in the logs; just information . 

maybe we still need more space or memory? what is a recommended ratio? thank you!

**Comment by ayende** [comment]
I would need to see the exact errors that you go to understand.
See if you got warnings about "slow disk I/O" there.

What do you mean, "initial handshake error" ? What do you mean node goes down? What are the *specific and full* errors?
If you have a log file, please include it as well

**Comment by jgaudetMcc** [comment]
We do have slow writes which I forgot to mention; these are the slow write we get...different indexes journals :
E:\RavenData\Databases\PhysiciansApplyDocuments\Indexes\DocumentByDocumentStoreId\Journals\0000000000000008975.journal
2022 December 13th, 3:55 AM
0.25 MB in 0.53 sec. (0.47MB/s)
E:\RavenData\Databases\PhysiciansApplyDocuments\Indexes\DocumentByCandidateId\Journals\0000000000000008981.journal
2022 December 13th, 3:55 AM
0.32 MB in 0.53 sec. (0.59MB/s)
E:\RavenData\Databases\PhysiciansApplyDocuments\Indexes\DocumentByDocumentStoreId\Journals\0000000000000008969.journal
2022 December 13th, 1:56 AM
0.25 MB in 0.55 sec. (0.45MB/s)
E:\RavenData\Databases\PhysiciansApplyDocuments\Indexes\DocumentByCandidateId\Journals\0000000000000008973.journal
2022 December 13th, 1:56 AM
0.32 MB in 0.57 sec. (0.56MB/s)
E:\RavenData\Databases\PhysiciansApplyDocuments\Indexes\DocumentByDocumentStoreId\Journals\0000000000000008930.journal
2022 December 12th, 5:43 PM
0.07 MB in 0.67 sec. (0.11MB/s)
E:\RavenData\Databases\PhysiciansApplyDocuments\Indexes\DocumentBySupportDocumentId\Journals\0000000000000003023.journal
2022 December 12th, 5:43 PM
0.08 MB in 0.66 sec. (0.12MB/s)
E:\RavenData\Databases\PhysiciansApplyDocuments\Indexes\DocumentByLegacySharePointDocumentId\Journals\0000000000000008378.journal
2022 December 12th, 5:43
etc.......

handshake (A to C and A to B):
System.AggregateException: One or more errors occurred. (Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..)
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Sparrow.Utils.ZstdStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in C:\Builds\RavenDB-Stable-5.4\54006\src\Sparrow\Utils\ZstdStream.cs:line 141
   at Sparrow.Utils.ReadWriteCompressedStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in C:\Builds\RavenDB-Stable-5.4\54006\src\Sparrow\Utils\ReadWriteCompressedStream.cs:line 156
   at Sparrow.Json.JsonOperationContext.ParseToMemoryAsync(Stream stream, String documentId, UsageMode mode, MemoryBuffer bytes, IBlittableDocumentModifier modifier, Nullable`1 token, Int32 maxSize) in C:\Builds\RavenDB-Stable-5.4\54006\src\Sparrow\Json\JsonOperationContext.cs:line 802
   at Raven.Server.Documents.Replication.InterruptibleRead.ReadNextObject(String debugTag, MemoryBuffer buffer, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54006\src\Raven.Server\Documents\Replication\InterruptibleRead.cs:line 122
   --- End of inner exception stack trace ---
   at Raven.Server.Documents.Replication.InterruptibleRead.ReturnAndClearValue() in C:\Builds\RavenDB-Stable-5.4\54006\src\Raven.Server\Documents\Replication\InterruptibleRead.cs:line 102
   at Raven.Server.Documents.Replication.InterruptibleRead.ParseToMemory(AsyncManualResetEvent interrupt, String debugTag, Int32 timeout, MemoryBuffer buffer, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54006\src\Raven.Server\Documents\Replication\InterruptibleRead.cs:line 72
   at Raven.Server.Documents.Replication.OutgoingReplicationHandler.HandleServerResponse(Boolean getFullResponse) in C:\Builds\RavenDB-Stable-5.4\54006\src\Raven.Server\Documents\Replication\OutgoingReplicationHandler.cs:line 1076
   at Raven.Server.Documents.Replication.OutgoingReplicationHandler.InitialHandshake() in C:\Builds\RavenDB-Stable-5.4\54006\src\Raven.Server\Documents\Replication\OutgoingReplicationHandler.cs:line 669

**Comment by ayende** [comment]
Okay, that make sense, then.
Basically, you loaded enough data that the disk started to stall (what kind do you have?).

That means that you started to wait longer on I/O. That in turn may cause some operations to fail. 

Those are *expected* and recovered, you shouldn't pay that any mind unless it is recurring & ongoing basis.

**Comment by jgaudetMcc** [comment]
ok, perfect, so would you recommend more space (physical?)
we have vmware virtual disk scsi
should we aim to always have a minimum of gb free at all times as it grows....
this database is likely to grow by thousands of documents a year...
any other recommendations are welcome and thank you!

**Comment by ayende** [comment]
It isn't about disk *space*, it is about disk _IOPS_.

Given the size, it is possible that you are using HDD?

**Comment by jgaudetMcc** [comment]
we have ssd; our networking person got us this for iops:

You can see it went as far as 709 IOPS:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/120476520/207697640-8623db4d-2d7c-430f-aa30-f04cb7d90b71.png)

**Comment by ayende** [comment]
Check the Disk stats during that time. Likely the disk / machine doesn't provide enough IOPS for your load.

Note that if this is just about migration, I would just ignore this, since importing TB of data is likely to stress things anyway

**Comment by jgaudetMcc** [comment]
ok , thank you. Appreciate the help and comments,

**Comment by jgaudetMcc** [comment]
thank you again

**Comment by jgaudetMcc** [comment]
Good afternoon ,

Sorry our networking person is asking if you would have a recommendation on the iops we would need.

Thank you
Johane

**Comment by ayende** [comment]
In general, the higher the better, see: https://ayende.com/blog/181698-C/why-iops-matter-for-the-database

That said, I would wait until the migration is done and see what is your day to day usage first.
I would recommend at least 1,000 IOPS, assuming that you have a decent number of queries

**Comment by jgaudetMcc** [comment]
Again, thank you so much!
