### ISSUE TITLE
Failed to create static index

### ISSUE THREAD

**Issue by dapesso** [ravendb/ravendb#15498]
Raven.Client.Exceptions.Documents.Indexes.IndexCreationException: Failed to create static index 'sss', the cluster is probably down. Node A state is Leader, I'm the only one in the cluster, so no need for elections, I rule. (at 12/26/2022 08:31:36)
 ---> Raven.Server.ServerWide.RejectPutClusterCommandException: Cannot accept the command 'PutIndexCommand', because the cluster version is '0', while this command can be applied in cluster with minimum version of 40000
   at Raven.Server.ServerWide.RejectPutClusterCommandException.Throw(String msg) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ClusterValidator.cs:line 67
   at Raven.Server.ServerWide.ClusterValidator.AssertPutCommandToLeader(CommandBase cmd) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ClusterValidator.cs:line 15
   at Raven.Server.Rachis.RachisConsensus.PutAsync(CommandBase cmd) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Rachis\RachisConsensus.cs:line 1013
   at Raven.Server.ServerWide.ServerStore.SendToLeaderAsyncInternal(TransactionOperationContext context, CommandBase cmd) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ServerStore.cs:line 3007
   at Raven.Server.ServerWide.ServerStore.SendToLeaderAsyncInternal(CommandBase cmd) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ServerStore.cs:line 2995
   at Raven.Server.ServerWide.ServerStore.SendToLeaderAsync(CommandBase cmd) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\ServerWide\ServerStore.cs:line 2820
   at Raven.Server.Documents.Indexes.IndexStore.CreateIndexInternal(IndexDefinition definition, String raftRequestId, String source) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Indexes\IndexStore.cs:line 918
   --- End of inner exception stack trace ---
   at Raven.Server.Documents.Indexes.IndexStore.ThrowIndexCreationException(String indexType, String indexName, Exception exception, String reason) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Indexes\IndexStore.cs:line 2428
   at Raven.Server.Documents.Indexes.IndexStore.CreateIndexInternal(IndexDefinition definition, String raftRequestId, String source) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Indexes\IndexStore.cs:line 922
   at Raven.Server.Documents.Handlers.Admin.AdminIndexHandler.PutInternal(Boolean validatedAsAdmin) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\AdminIndexHandler.cs:line 110
   at Raven.Server.Documents.Handlers.Admin.AdminIndexHandler.PutJavaScript() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Handlers\Admin\AdminIndexHandler.cs:line 50
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Routing\RequestRouter.cs:line 365
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\RavenServerStartup.cs:line 253

**Comment by karmeli87** [comment]
Do you get it constantly? Or is it a transient one?
Are you able to reproduce it?

**Comment by ayende** [comment]
To reproduce:

* Create a 3 node cluster using setup wizard, but only have a single node in it.
* Create databases / indexes - it shows up consistently.
* Sometimes you need to restart to get it.

Pretty sure that this is related to how we find the minimum version in the cluster in such a scenario.
