### ISSUE TITLE
Could not find index

### ISSUE THREAD

**Issue by zakstam** [ravendb/ravendb#15683]
RavenDB Version : **5.4.100**
Application SDK:  **.NET 6**
RavenDB.Client version: **5.4.100**

EDIT: Fixed .OpenAsyncSession("")
Query:
```CSharp
using var dbSession = DocumentStoreHolder.Store.OpenAsyncSession();
var test = await dbSession.Query<Customer>()
    .SingleOrDefaultAsync(customer => customer.Credentials.Username == "test", ct:
```

Error:
```CSharp
Raven.Client.Exceptions.Documents.Indexes.IndexDoesNotExistException: Could not find index 
   at Raven.Client.Documents.Session.Operations.QueryOperation.EnsureIsAcceptableAndSaveResult(QueryResult result, Nullable`1 duration) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 319
   at Raven.Client.Documents.Session.Operations.QueryOperation.EnsureIsAcceptableAndSaveResult(QueryResult result) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 312
   at Raven.Client.Documents.Session.Operations.QueryOperation.SetResult(QueryResult queryResult) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 69
   at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteActualQueryAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1083
```

As you can see i'm not specifying any index, i was expecting RavenDB to create one automatically (which i think is the issue here). I tried switching from Lucene to Corax but nothing changed.

Explicitly specifying the index name still gives the same error:
```CSharp
using var dbSession = DocumentStoreHolder.Store.OpenAsyncSession();
var test = await dbSession.Query<Customer>("Auto/ApplicationUsers/ByUserName")
    .SingleOrDefaultAsync(customer => customer.Credentials.Username == "test", ct:
```
```CSharp
Raven.Client.Exceptions.Documents.Indexes.IndexDoesNotExistException: Could not find index Auto/ApplicationUsers/ByUserName
   at Raven.Client.Documents.Session.Operations.QueryOperation.EnsureIsAcceptableAndSaveResult(QueryResult result, Nullable`1 duration) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 319
   at Raven.Client.Documents.Session.Operations.QueryOperation.EnsureIsAcceptableAndSaveResult(QueryResult result) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 312
   at Raven.Client.Documents.Session.Operations.QueryOperation.SetResult(QueryResult queryResult) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 69
   at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteActualQueryAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1083
```

NOTE: Querying directly from RavenDB studio using RQL seems to work and the index is created (if it does not exist)

**Comment by ml054** [comment]
In `OpenAsyncSession("");` you specify empty string as database name. Could you try instead: `OpenAsyncSession();`

There is no need to specify database name - you can provide default database name in document store.

**Comment by zakstam** [comment]
Sorry that was a type when i posted the code and removed the database name. In the actual code the error happens regardless of whether i specify a database or not

**Comment by ml054** [comment]
Could you a try an move condition from SingleOrDefault to Where?

```
await dbSession.Query<Customer>()
    .Where(customer => customer.Credentials.Username == "test")
    .SingleOrDefaultAsync()
```

Also could you tell me what query goes to server. You can easily check that on traffic watch view in RavenDB Studio. Example link to our public instance: http://live-test.ravendb.net/studio/index.html#admin/settings/trafficWatch

**Comment by zakstam** [comment]
> Could you a try an move condition from SingleOrDefault to Where?
> 
> ```
> await dbSession.Query<Customer>()
>     .Where(customer => customer.Credentials.Username == "test")
>     .SingleOrDefaultAsync()
> ```

Same error:
```CSharp
var test = await session.Query<Customer>("Auto/ApplicationUsers/ByUserName")
    .Where(customer => customer.Credentials.Username == "zak").SingleOrDefaultAsync(ct);
```
```CSharp
Raven.Client.Exceptions.Documents.Indexes.IndexDoesNotExistException: Could not find index Auto/ApplicationUsers/ByUserName
   at Raven.Client.Documents.Session.Operations.QueryOperation.EnsureIsAcceptableAndSaveResult(QueryResult result, Nullable`1 duration) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 319
   at Raven.Client.Documents.Session.Operations.QueryOperation.EnsureIsAcceptableAndSaveResult(QueryResult result) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 312
   at Raven.Client.Documents.Session.Operations.QueryOperation.SetResult(QueryResult queryResult) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\Operations\QueryOperation.cs:line 69
   at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteActualQueryAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54027\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1083
```

**Comment by ml054** [comment]
Ok please check traffic watch and admin logs (I described traffic watch in previous comment).

**Comment by zakstam** [comment]
> Could you a try an move condition from SingleOrDefault to Where?
> 
> ```
> await dbSession.Query<Customer>()
>     .Where(customer => customer.Credentials.Username == "test")
>     .SingleOrDefaultAsync()
> ```
> 
> Also could you tell me what query goes to server. You can easily check that on traffic watch view in RavenDB Studio. Example link to our public instance: http://live-test.ravendb.net/studio/index.html#admin/settings/trafficWatch

There doesnt seem to be any traffic displayed after the query is run:
![image](https://user-images.githubusercontent.com/1850856/213860000-ade9819b-c8b2-4fde-b672-0c5b2d189b24.png)

**Comment by ml054** [comment]
Rather not possible to be empty. Did you replace live-test.ravendb.net with your server url? 
According to your stack trace EnsureIsAcceptableAndSaveResult is executed after we get query result from server. So it hits some server for sure. :)

**Comment by zakstam** [comment]
I deleted Hasura (was playing around with it) container from docker (maybe it was using port 8080?) and now it seems to work! I will set up Hasura again and see if i can replicate the issue (just for future reference). Thank you @ml054

**Comment by ml054** [comment]
Glad to hear that. Happy hacking with RavenDB. :)

**Comment by zakstam** [comment]
For future reference, [Hasura](https://hasura.io) GraphQL engine is using port 8080 and i guess RavenDB.Client was connecting to this instead of the actual server. Interestingly enough, i did not get any errors when running the server and also the browser loads RavenDB studio properly

**Comment by ml054** [comment]
Maybe one was bound to 127.0.0.1 and second to 192..168.0.XXX? RavenDB shouldn't start if port was in use.

**Comment by zakstam** [comment]
> Maybe one was bound to 127.0.0.1 and second to 192..168.0.XXX? RavenDB shouldn't start if port was in use.

Both 127.0.0.1:8080 and localhost:8080 seem to point to RavenDB studio in the browser. http://host.docker.internal:8080 on the other hand loads Hasura console. The server URL in settings.json of RavenDB is  "ServerUrl": "http://127.0.0.1:8080".
I'm not sure how RavenDB connects internally so i cant make any guesses there.

BTW i'm not running the docker version of RavenDB. I would guess that if i did i would get a port conflict error

EDIT: Thats easily reproducible btw. Just run a local windows instance of RaveDB using powershell and then use docker compose to setup a Hasura container (in case you want to debug it)
