### ISSUE TITLE
members vs watchers

### ISSUE THREAD

**Issue by jgaudetMcc** [ravendb/ravendb#15863]
Good afternoon,

new at ravendb. We are trying to start our endpoint with cluster initialization. Took the code from the course we took with you. It seemed simple enough (please , see code below). 

When our cluster have one leader and 2 member nodes we get an error (Please see below as well) and the endpoint won't stay up and running.
When our cluster have one leader and 2 worker nodes ; same code; no error and all looks good. Endpoint stays up and all works as intended; even if nodes go down and back up....

Read in posts that maybe our license is of the wrong kind.
our license is professional --  max cluster 5; max cores in cluster 6
our version is 
![image](https://user-images.githubusercontent.com/120476520/220443921-bb5cc201-d8a4-4048-8643-bf3047438ee4.png)
in code we are using raven db client 4.2

any insight would be appreciated. thank you.

------code-------
 var store = new DocumentStore //init cluster ; the nodes are on different servers and we don't have a cert yet.
                {
                    Urls = new[] { settings.Url, settings.UrlNodeB, settings.UrlNodeC },
                    Database = settings.Database
                };
            store.Initialize();

------------error:--------------
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at NServiceBus.Persistence.RavenDB.DocumentStoreInitializer.EnsureClusterConfiguration(Raven.Client.Documents.IDocumentStore)
   at NServiceBus.Persistence.RavenDB.DocumentStoreInitializer.Init(NServiceBus.Settings.ReadOnlySettings, NServiceBus.ObjectBuilder.IBuilder)
   at NServiceBus.Persistence.RavenDB.RavenDbSubscriptionStorage+<>c__DisplayClass1_0.<Setup>b__0(NServiceBus.ObjectBuilder.IBuilder)
   at NServiceBus.Extensions.Hosting.ServiceCollectionAdapter+<>c__DisplayClass4_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ConfigureComponent>b__1(System.IServiceProvider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(Microsoft.Extensions.DependencyInjection.ServiceLookup.FactoryCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitCallSiteMain(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=6.0.0.1, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].VisitCallSite(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(System.Type)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].GetOrAdd(System.__Canon, System.Func`2<System.__Canon,System.__Canon>)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(System.Type, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope)
   at NServiceBus.Extensions.Hosting.ServiceProviderAdapter.Build(System.Type)
   at NServiceBus.Extensions.Hosting.ServiceProviderAdapter.Build[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]()
   at NServiceBus.Features.MessageDrivenSubscriptions+<>c__DisplayClass2_0.<Setup>b__1(NServiceBus.ObjectBuilder.IBuilder)
   at NServiceBus.Pipeline.PipelineSettings+<>c__DisplayClass8_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<Register>b__0(NServiceBus.ObjectBuilder.IBuilder)
   at System.Linq.Enumerable+WhereSelectListIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
   at System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Linq.Enumerable.ToArray[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at NServiceBus.Pipeline`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(NServiceBus.ObjectBuilder.IBuilder, NServiceBus.PipelineModifications)
   at NServiceBus.SendComponent.CreateMessageOperations(NServiceBus.ObjectBuilder.IBuilder, NServiceBus.PipelineComponent)
   at NServiceBus.StartableEndpoint+<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.HostingComponent+<Start>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.ExternallyManagedContainerHost+<Start>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at NServiceBus.Extensions.Hosting.NServiceBusHostedService+<StartAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.Internal.Host+<StartAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions+<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)

**Comment by garayx** [comment]
Hello 

The stacktrace you posted is from NServiceBus, and not thrown from RavenDB.

What do you mean by 2 worker nodes ? how its different from 2 member nodes ?

**Comment by ayende** [comment]
I assume that they mean watchers vs. members.
That is typically a NServiceBus limitation you are running into in older versions. 
You aren't showing the actual exception text, show there is no way to really know, but this is what I'll assume

**Comment by jgaudetMcc** [comment]
yes, watchers vs members, sorry....if we demote the nodes to watchers; we are good. ..We are using 

![image](https://user-images.githubusercontent.com/120476520/220611537-d72d01e2-0894-4188-a71a-42aeef4fbefe.png)

**Comment by ayende** [comment]
IIRC, you need NSB 7 for this

**Comment by jgaudetMcc** [comment]
ok, perfect. will try this. thank you.
