### ISSUE TITLE
Facets with NULL_VALUE will fail in corax

### ISSUE THREAD

**Issue by xinix00** [ravendb/ravendb#16514]
I'm using Corax as a test, and using Facets, however when a field is NULL, and it wants to return NULL_VALUE = 1 for example, the client will crash with:
```
Exception thrown: 'Raven.Client.Exceptions.RavenException' in System.Private.CoreLib.dll: 'System.Collections.Generic.KeyNotFoundException: The given key 'NULL_VALUE' was not present in the dictionary.
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexFacetedReadOperation.HandleFacetsPerDocument(IndexEntryReader& entryReader, KeyValuePair`2 result, Dictionary`2 facetsByName, Boolean legacy, QueryTimingsScope queryTimings, AnalyzersScope analyzersScope, CancellationToken token)
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexFacetedReadOperation.FacetedQuery(FacetQuery facetQuery, QueryTimingsScope queryTimings, DocumentsOperationContext context, Func`2 getSpatialField, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexFacetedReadOperation.cs:line 72
```

The code it is refering to is below (placed inline comments)
```
private void HandleFacetsPerDocument(ref IndexEntryReader entryReader,
        KeyValuePair<string, FacetedQueryParser.FacetResult> result,
        Dictionary<string, Dictionary<string, FacetValues>> facetsByName,
        bool legacy,
        QueryTimingsScope queryTimings,
        AnalyzersScope analyzersScope,
        CancellationToken token)
    {
        var needToApplyAggregation = result.Value.Aggregations.Count > 0;
        if (facetsByName.TryGetValue(result.Key, out var facetValues) == false)
            facetsByName[result.Key] = facetValues = new Dictionary<string, FacetValues>(); <---- creates a new dictionary

        GetFieldReader(ref entryReader, result.Value.AggregateBy, out var fieldReader);

        switch (fieldReader.Type)
        {
            case IndexEntryFieldType.ListWithEmpty:
            case IndexEntryFieldType.ListWithNulls:
            case IndexEntryFieldType.List:
            case IndexEntryFieldType.TupleList:
            case IndexEntryFieldType.TupleListWithNulls:
                if (fieldReader.TryReadMany(out var iterator)==false)
                    break;

                while (iterator.ReadNext())
                {
                    if (iterator.IsNull || iterator.IsEmptyCollection)
                    {
                        facetValues[iterator.IsNull ? Constants.NullValue : Constants.EmptyString].IncrementCount(1);  <--- Looks up the NULL_VALUE in dictionary, but that one doesn't exist yet and crashes (empty string is the same by the way)
                        continue;
                    }
                    InsertTerm(iterator.Sequence, ref entryReader);
                }
        
                break;
            case IndexEntryFieldType.Tuple:
            case IndexEntryFieldType.Simple:
                if (fieldReader.Read(out var source))
                    InsertTerm(source, ref entryReader);
                break;
            case IndexEntryFieldType.Null:
                break;
            default:
                throw new Exception($"Got type {fieldReader.Type}");
        }
```

**Comment by xinix00** [comment]
Also got a question, I also got a ListWithEmpty
https://github.com/ravendb/ravendb/commit/f709ac9765b01bfbea1e49cef55ffff6a7364916

When will there be a release?

**Comment by maciejaszyk** [comment]
Hey, thanks for reporting,
I created a ticket for that:
https://issues.hibernatingrhinos.com/issue/RavenDB-20529/Facets-with-NULLVALUE-will-fail-in-corax

**Comment by arekpalinski** [comment]
It looks we have fixed it meanwhile. In https://github.com/ravendb/ravendb/pull/16977 we added a test which verifies that it works.
