### ISSUE TITLE
DynaTrace issues

### ISSUE THREAD

**Issue by ramonsmits** [ravendb/ravendb#16542]
We are using the [embedded server](https://ravendb.net/docs/article-page/5.3/csharp/server/embedded) and have evidence that DynaTrace is causing issues for some of our customer environments.

Are you aware of this and do you know if this can be mitigated?

Likely DynaTrace somehow tries to intercept the communication to/from the RavenDB instance which results in 

```
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:44445
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Raven.Client.Http.RequestExecutor.<SendRequestToServer>d__116`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Client\Http\RequestExecutor.cs:line 1039
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Http.RequestExecutor.<ExecuteAsync>d__114`1.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Client\Http\RequestExecutor.cs:line 866
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Documents.Session.AsyncDocumentSession.<SaveChangesAsync>d__32.MoveNext() in C:\Builds\RavenDB-Stable-5.4\54038\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 185
--- End of stack trace from previous location where exception was thrown ---
```

Our related issues are:

- https://github.com/Particular/ServiceControl/issues/3520
- https://github.com/Particular/ServiceControl/issues/3521

**Comment by arekpalinski** [comment]
Hi,

The exception message clearly indicates some connectivity issue. We're not familiar with DynaTrace and didn't get any reports like that. I just found the following discussion about some problems with it in the past - https://github.com/ravendb/ravendb/discussions/13720

**Comment by ramonsmits** [comment]
@arekpalinski yes, its a connectivety issue but its caused by DynaTrace. Our customer already provided feedback that disabling DynaTrace causes the embedded database to function correctly and after enabling DynaTrace again that the connectivety issues returns. I suspect that DynaTraces tries to add some http pipeline stuff to embed or read tracing data which causes this connectivity problem.

**Comment by simendsjo** [comment]
>  I suspect that DynaTraces tries to add some http pipeline stuff to embed or read tracing data which causes this connectivity problem.

I don't think so. We haven't been monitoring these processes, and we're still seeing issues. It could be related to npcap og libpcap? It's running 1.71, and there are some bugfixes and bumping libpcap in the mean time.

It looks like connections are accepted, but not closed, causing starvation of a resource pool or similar?

![image](https://github.com/ravendb/ravendb/assets/351519/233aa2d4-caf6-42ad-8334-22a285bb7b75)

**Comment by ayende** [comment]
Following up on this: https://github.com/ravendb/ravendb/discussions/13720#discussioncomment-6010123

I think you are no longer using Dynatrace, so we can close this as well?

**Comment by simendsjo** [comment]
> I think you are no longer using Dynatrace, so we can close this as well?

We're using Dynatrace. We've added an issue at Dynatrace, linked to this issue, and also put @ramonsmits in CC for the issue.

**Comment by ramonsmits** [comment]
Ramon from Particular here. We received some additional information from our customer that might be helpful for others that run into issues with RavenDB and DynaTrace:


>"We first tried to deactivate something called "process injection" 
Based on the Dynatrace license available, and frameworks used for the application in use, Dynatrace has some other ways of extracting "deeper" metrics. Our experience is that this works fine in most scenarios, but some applications can be sensitive to this apporach.
>
>What we ended up doing in your case to turn off autodiscovery of logfiles related to the specific process you mentioned. We have experienced that this can cause spawning of some threads that could lock the process."
>
>It was after they turned of logfile autodiscovery the ServiceControl process was running fine.

I'm unaware if this issue has been forwarded to DynaTrace support but as the problem ben be mitigated using the above procedure I will close the issue.
