### ISSUE TITLE
After 00:05:00, did not get a reply for operation ...

### ISSUE THREAD

**Issue by wallaceturner** [ravendb/ravendb#16641]
we are using v5.4.1 (both server and client)

We are starting to see this intermittent error (below) on one of our servers (single node cluster running on win2012 R2)

we have an Extension method to `DeleteByIndex`

```
        public static void DeleteByIndex<TEntity, TIndexCreator>(this IDocumentStore store, Expression<Func<TEntity, bool>> query) where TIndexCreator : AbstractIndexCreationTask, new()
        {
            var options = new QueryOperationOptions();
            options.AllowStale = true;
            options.StaleTimeout = TimeSpan.FromMinutes(2);

            Operation operation = store.Operations.Send(new DeleteByQueryOperation<TEntity, TIndexCreator>(query, options));
            operation.WaitForCompletion(TimeSpan.FromMinutes(5));
        }
```

and invoke it like

```
_session.Advanced.DocumentStore.DeleteByIndex<CmeStaticDataReconcilerSecBoardSnapshot, CmeStaticDataReconcilerSecBoardSnapshot_ByTradeDate>(r => r.TradeDate < tradeDate);
```

the document collection in question has very few rows (less than 10)

We have reviewed the '[whats new](https://ravendb.net/docs/article-page/5.4/Csharp/start/whats-new#54049)' between our version of ravendb and the latest version and there doesnt appear to be any fixes related to `Advanced.DocumentStore.DeleteByIndex`

As the problem is intermittment could you provide any recommendations?
We also note the issue occurs on other `DeleteByIndex` calls - not just specific to the example shown above

```
 System.TimeoutException: After 00:05:00, did not get a reply for operation 222953
   at Raven.Client.Documents.Operations.Operation.<WaitForCompletionAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Raven.Client.Util.AsyncHelpers.RunSync[T](Func`1 task)
   at Raven.Client.Documents.Operations.Operation.WaitForCompletion(Nullable`1 timeout) in C:\Builds\RavenDB-Stable-5.4\54001\src\Raven.Client\Documents\Operations\Operation.cs:line 346
   at FexOnline.Web.Application.Database.RavenDbExtensions.DeleteByIndex[TEntity,TIndexCreator](IDocumentStore store, Expression`1 query) in C:\aaa_development\source\f...\Application\Database\RavenDbExtensions.cs:line 47
```

**Comment by ayende** [comment]
Is it reproducible? 
If you look at the delete operation in the studio, what do you see?

**Comment by wallaceturner** [comment]
@ayende havent been able to reproduce it yet - will hopefully come back with one
"look at the delete operation in the studio" <-- can you clarify -  is this something i can look at/inspect/diagnose after its occurred ? (as we are calling it from code not the studio)

**Comment by JezhikLaas** [comment]
Hello! This sounds very much like the issue we are facing from time to time: https://issues.hibernatingrhinos.com/issue/RavenDB-21719 .

**Comment by ayende** [comment]
Not reproducible — the reporter was unable to reproduce it either. Closing due to inactivity. Please reopen with a reproduction if this recurs.
