### ISSUE TITLE
System.Net.Sockets.SocketException (10013) during EmbeddedServer.Instance.GetDocumentStore(...)

### ISSUE THREAD

**Issue by Kevin-570** [ravendb/ravendb#16677]
We are seeing this error on some devices (log message from raven at the bottom).
We have set ServerOptions.ServerUrl = "http://localhost:8082".
It doesn't appear to be a problem with port 8082, since the error message reported is different when we explicitly restrict access to this port.  From what we can tell, Raven uses 2 other port connections internally when it launches its Kestrel server.  We discovered this with the following powershell script:

`$Connections = Get-NetTCPConnection
foreach($Connection in $Connections)
{
    $Process = Get-Process -Id $Connection.OwningProcess
    if($Process.ProcessName -like "*Raven*")
    {
        $Process.ProcessName + "  " + $Connection.LocalAddress + "  " + $Connection.LocalPort
    }
}`

We think that these internal ports are causing issues, and we see no way to control what ports are used.
After searching around, this may be caused by attempting to use ports that are restricted by Windows: 
https://ardalis.com/attempt-made-to-access-socket/

Any ideas what is causing this?

`
2023-05-09T19:07:33.5840446Z, 1, Operations, Server, Raven.Server.RavenServer, Could not start server, EXCEPTION: System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Raven.Server.RavenServer.Initialize() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\RavenServer.cs:line 257
2023-05-09T19:07:33.6911574Z, 1, Operations, Server, Raven.Server.Program, Failed to initialize the server, EXCEPTION: System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.Start()
   at Raven.Server.RavenServer.Initialize() in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\RavenServer.cs:line 257
   at Raven.Server.Program.Main(String[] args) in C:\Builds\RavenDB-Stable-5.4\54018\src\Raven.Server\Program.cs:line 185
2023-05-09T19:07:33.6920897Z, 1, Operations, Server, Raven.Server.Program, 
2023-05-09T19:07:33.7232540Z, 1, Operations, Server, Raven.Server.Program, Server has shut down
`

**Comment by ayende** [comment]
RavenDB uses two separate sockets by default.
1 for HTTP, 1 for TCP 

The error you are seeing here is the HTTP one, not the TCP one.

Can you show the full configuration you use for RavenDB?

**Comment by Kevin-570** [comment]
If we use an http port that is restricted by windows, we get this error instead:

`System.IO.IOException: Failed to bind to address http://localhost:8884.
 ---> System.AggregateException: One or more errors occurred. (An attempt was made to access a socket in a way forbidden by its access permissions.) (An attempt was made to access a socket in a way forbidden by its access permissions.)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)`

This is slightly different, since it calls out the actual socket it failed on.  This is why we assumed it was the internal Raven socket.

We are setting the following properties on ServerOptions:  ServerUrl, DataDirectory, LogsPath, ServerDirectory.
We also set the MasterKey and the License via CommandLineArgs, and we call ServerOptions.Secured(...) with a cert.
This is all done in code, and is the only configuration changes we make.

**Comment by ayende** [comment]
Please show the *full* configuration you are using.
You can create a simple repro?
Do you have AV running that may interfer?
