### ISSUE TITLE
[RavenDB 6 nightly] The latest version seems to throw a NullReferenceException

### ISSUE THREAD

**Issue by dstarosta** [ravendb/ravendb#16773]
The query uses a static Corax index and only has a couple of simple `WhereEquals` conditions.

```c#
System.NullReferenceException: Object reference not set to an instance of an object.\r\n at Corax.Queries.AllEntriesMatch..ctor(IndexSearcher searcher, Transaction tx) in C:\\Builds\\RavenDB-6.0-Nightly\\20230628-0100\\src\\Corax\\Queries\\AllEntriesMatch.cs:line 34\r\n at Corax.IndexSearcher.AllEntries() in C:\\Builds\\RavenDB-6.0-Nightly\\20230628-0100\\src\\Corax\\IndexSearcher\\IndexSearcher.cs:line 247\r\n at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.Parameters..ctor(Ind…ers.QueriesHandler.Post() in C:\\Builds\\RavenDB-6.0-Nightly\\20230628-0100\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 15\r\n at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\\Builds\\RavenDB-6.0-Nightly\\20230628-0100\\src\\Raven.Server\\Routing\\RequestRouter.cs:line 376\r\n at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\\Builds\\RavenDB-6.0-Nightly\\20230628-0100\\src\\Raven.Server\\RavenServerStartup.cs:line 255"
```

**Comment by garayx** [comment]
Hi

Can you share the query, static index and sample document that you use when you are getting this exception?

**Comment by dstarosta** [comment]
The index definition is
```
public class VoteIndex : AbstractIndexCreationTask<Vote, VoteProjection>
{
    public VoteIndex()
    {
        SearchEngineType = Raven.Client.Documents.Indexes.SearchEngineType.Corax;

        Map = votes =>
            from vote in votes
            select new VoteProjection
            {
                Id = vote.Id,
                QuestionId = vote.QuestionId,
                AnswerId = vote.AnswerId,
                UserId = vote.UserId,
                VoteType = vote.VoteType,
                CreationDate = vote.CreationDate
            };
    }
}
```

The `query.ToString()` is `from index 'VoteIndex' where QuestionId = $p0`

All IDs are integers prefixed by `documents/`, VoteType is an enum and CreationDate is a DateTime.

**Comment by arekpalinski** [comment]
Thanks @dstarosta! We'll check it.

**Comment by ayende** [comment]
I tried looking into that, but couldn't reproduce this.
Is this something that you can provide us as a failing test case?

Note that the stack trace doesn't make sense to me, this query should never call to `AllEntriesMatch`, for example. 

We are doing heavy work on Corax at the moment, so it is possible that this was already resolved on my end, though.

**Comment by dstarosta** [comment]
Here is the full stack trace from the latest nightly build which may help. Reproducing the case would require creating a database.

Raven.Client.Exceptions.RavenException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Corax.Queries.AllEntriesMatch..ctor(IndexSearcher searcher, Transaction tx) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Corax\Queries\AllEntriesMatch.cs:line 34
   at Corax.IndexSearcher.AllEntries() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Corax\IndexSearcher\IndexSearcher.cs:line 247
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.Parameters..ctor(IndexSearcher searcher, ByteStringContext allocator, TransactionOperationContext serverContext, DocumentsOperationContext documentsContext, IndexQueryServerSide query, Index index, BlittableJsonReaderObject queryParameters, QueryBuilderFactories factories, IndexFieldsMapping indexFieldsMapping, FieldsToFetch fieldsToFetch, Dictionary`2 highlightingTerms, Int32 take, IndexReadOperationBase indexReadOperation, List`1 buildSteps, CancellationToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 77
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexReadOperation.QueryInternal[THighlighting,TQueryFilter,THasProjection,TDistinct](IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, Reference`1 scannedDocuments, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexReadOperation.cs:line 558
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Index.cs:line 3412
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Index.cs:line 3412
   at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Index.cs:line 3145
   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Queries\StaticIndexQueryRunner.cs:line 41
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 99
   at Raven.Server.Documents.Handlers.Processors.Queries.DatabaseQueriesHandlerProcessorForGet.GetQueryResultsAsync(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, Boolean metadataOnly, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Handlers\Processors\Queries\DatabaseQueriesHandlerProcessorForGet.cs:line 53
   at Raven.Server.Documents.Handlers.Processors.Queries.AbstractQueriesHandlerProcessorForGet`4.ExecuteAsync() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Handlers\Processors\Queries\AbstractQueriesHandlerProcessorForGet.cs:line 219
   at Raven.Server.Documents.Handlers.QueriesHandler.Post() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 15
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Routing\RequestRouter.cs:line 376
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\RavenServerStartup.cs:line 255
 ---> System.NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
   at Corax.Queries.AllEntriesMatch..ctor(IndexSearcher searcher, Transaction tx) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Corax\Queries\AllEntriesMatch.cs:line 34
   at Corax.IndexSearcher.AllEntries() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Corax\IndexSearcher\IndexSearcher.cs:line 247
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.Parameters..ctor(IndexSearcher searcher, ByteStringContext allocator, TransactionOperationContext serverContext, DocumentsOperationContext documentsContext, IndexQueryServerSide query, Index index, BlittableJsonReaderObject queryParameters, QueryBuilderFactories factories, IndexFieldsMapping indexFieldsMapping, FieldsToFetch fieldsToFetch, Dictionary`2 highlightingTerms, Int32 take, IndexReadOperationBase indexReadOperation, List`1 buildSteps, CancellationToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 77
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexReadOperation.QueryInternal[THighlighting,TQueryFilter,THasProjection,TDistinct](IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, Reference`1 scannedDocuments, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexReadOperation.cs:line 558
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Index.cs:line 3412
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Index.cs:line 3412
   at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Indexes\Index.cs:line 3145
   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Queries\StaticIndexQueryRunner.cs:line 41
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 99
   at Raven.Server.Documents.Handlers.Processors.Queries.DatabaseQueriesHandlerProcessorForGet.GetQueryResultsAsync(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, Boolean metadataOnly, OperationCancelToken token) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Handlers\Processors\Queries\DatabaseQueriesHandlerProcessorForGet.cs:line 53
   at Raven.Server.Documents.Handlers.Processors.Queries.AbstractQueriesHandlerProcessorForGet`4.ExecuteAsync() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Handlers\Processors\Queries\AbstractQueriesHandlerProcessorForGet.cs:line 219
   at Raven.Server.Documents.Handlers.QueriesHandler.Post() in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 15
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\Routing\RequestRouter.cs:line 376
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-6.0-Nightly\20230703-0100\src\Raven.Server\RavenServerStartup.cs:line 255
   --- End of inner exception stack trace ---
   at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, Action`1 additionalErrorInfo) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 119
   at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Http\RequestExecutor.cs:line 1486
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Http\RequestExecutor.cs:line 937
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Http\RequestExecutor.cs:line 937
   at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteActualQueryAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1088
   at Raven.Client.Documents.Session.AsyncDocumentQuery`1.InitAsync(CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1073
   at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteQueryOperationInternal(Nullable`1 take, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1033
   at Raven.Client.Documents.Session.AsyncDocumentQuery`1.ExecuteQueryOperation(Nullable`1 take, CancellationToken token) in C:\Builds\RavenDB-Stable-5.4\54061\src\Raven.Client\Documents\Session\AsyncDocumentQuery.cs:line 1014

**Comment by ayende** [comment]
Pretty sure that we'll need something more than that, I'm afraid.
I tried that here:
http://live-test.ravendb.net/studio/index.html#databases/query/index/votes?&database=t

And I think we need some data to reproduce this

**Comment by dstarosta** [comment]
Rebuilding the index fixes the problem. There might have been some incompatible change in the code.

**Comment by ayende** [comment]
Oh, that is for sure.
Corax is currently _not_ stable, and in general, whenever you update a build we assume that you start from a clear slate.
Once we'll have a beta build out, we'll be more careful about that.
