### ISSUE TITLE
[Integrations]  Would like PostgreSQL integration to support DBeaver

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [ravendb/ravendb#17037]
Would like to be able to use [DBeaver](https://dbeaver.io/) to browse _RavenDB_ as this is a very common and easy to use GUI

Currently getting an UE when trying to connect:

```bash
ERROR: Unhandled query (Are you using ; in your query? That is likely causing the postgres client to split the query and results in partial queries): 
SET extra_float_digits = 3
  Detail: Raven.Server.Integrations.PostgreSQL.Exceptions.PgErrorException: Unhandled query (Are you using ; in your query? That is likely causing the postgres client to split the query and results in partial queries): 
SET extra_float_digits = 3
   at Raven.Server.Integrations.PostgreSQL.PgQuery.CreateInstance(String queryText, Int32[] parametersDataTypes, DocumentDatabase documentDatabase, PgSession session) in C:\dev\xcm\ravendb\src\Raven.Server\Integrations\PostgreSQL\PgQuery.cs:line 58
   at Raven.Server.Integrations.PostgreSQL.PgTransaction.Init(String cleanQueryText, Int32[] parametersDataTypes) in C:\dev\xcm\ravendb\src\Raven.Server\Integrations\PostgreSQL\PgTransaction.cs:line 45
   at Raven.Server.Integrations.PostgreSQL.Messages.Parse.HandleMessage(PgTransaction transaction, MessageBuilder messageBuilder, PipeWriter writer, CancellationToken token) in C:\dev\xcm\ravendb\src\Raven.Server\Integrations\PostgreSQL\Messages\Parse.cs:line 80
   at Raven.Server.Integrations.PostgreSQL.Messages.Message.Handle(PgTransaction transaction, MessageBuilder messageBuilder, PipeReader reader, PipeWriter writer, CancellationToken token) in C:\dev\xcm\ravendb\src\Raven.Server\Integrations\PostgreSQL\Messages\Message.cs:line 162
   at Raven.Server.Integrations.PostgreSQL.Messages.ExtendedProtocolMessage.Handle(PgTransaction transaction, MessageBuilder messageBuilder, PipeReader reader, PipeWriter writer, CancellationToken token) in C:\dev\xcm\ravendb\src\Raven.Server\Integrations\PostgreSQL\Messages\ExtendedProtocolMessage.cs:line 15
   at Raven.Server.Integrations.PostgreSQL.PgSession.Run() in C:\dev\xcm\ravendb\src\Raven.Server\Integrations\PostgreSQL\PgSession.cs:line 184
```

DBeaver Version 22.2.4.202211061524

RavenDB commit 7beae099fa03721f161489741ad475e9b0aecbf1

**Comment by ayende** [comment]
Hi,
It is unlikely that this will happen in the near future, without community contribution. (We'll gladly help on those).

The issue is typically that those tool send queries of particular type and expect Postgres style response.
This is primarily the reason the feature is experimental.
For PowerBI, we thought RavenDB how to respond to the metadata queries from PowerBI.

For DBeaver, we'll need to do the same. 

The process we choose means that we need to identify the queries and craft specific answers to them, rather than trying to implement the whole SQL stack for Postgres.

See how it is done here:
https://github.com/ravendb/ravendb/blob/2315e7f7b9a506e3dc92267520bcd3d5b299e70b/src/Raven.Server/Integrations/PostgreSQL/HardcodedQuery.cs#L12

**Comment by tzarger** [comment]
@ayende 

I tried several clients and they all send the `;` which seems like a pretty standard thing for PostgreSQL. I guess from your comment, it is only for PowerBI and not really a traditional PostgreSQL client? Maybe the docs should be more clear.

Here is the error I received for the record, from both **pgAdmin** and **SQLStudio Pro** on Mac.

```
ERROR:  Unhandled query (Are you using ; in your query? That is likely causing the postgres client to split the query and results in partial queries): 
SELECT * FROM pg_database WHERE datistemplate = false;
DETAIL:  Raven.Server.Integrations.PostgreSQL.Exceptions.PgErrorException: Unhandled query (Are you using ; in your query? That is likely causing the postgres client to split the query and results in partial queries): 
SELECT * FROM pg_database WHERE datistemplate = false;
at Raven.Server.Integrations.PostgreSQL.PgQuery.CreateInstance(String queryText, Int32[] parametersDataTypes, DocumentDatabase documentDatabase, PgSession session) in /_/70006/src/Raven.Server/Integrations/PostgreSQL/PgQuery.cs:line 60
at Raven.Server.Integrations.PostgreSQL.Messages.Query.HandleMessage(PgTransaction transaction, MessageBuilder messageBuilder, PipeWriter writer, CancellationToken token) in /_/70006/src/Raven.Server/Integrations/PostgreSQL/Messages/Query.cs:line 27
at Raven.Server.Integrations.PostgreSQL.Messages.Message.Handle(PgTransaction transaction, MessageBuilder messageBuilder, PipeReader reader, PipeWriter writer, CancellationToken token) in /_/70006/src/Raven.Server/Integrations/PostgreSQL/Messages/Message.cs:line 162
at Raven.Server.Integrations.PostgreSQL.PgSession.Run() in /_/70006/src/Raven.Server/Integrations/PostgreSQL/PgSession.cs:line 198
```

**Comment by ayende** [comment]
Yes, the situation is pretty much the same in this regard. We support `PowerBI` directly, but not generic clients.
Note that you use `Npgsql` to connect to RavenDB via code, that should work, but generic PG clients will likely not.

**Comment by oiBio** [comment]
Hi,

can you clarify the current status of this issue?

Is this something that is already implemented, planned to be implemented, or should it be considered as not going to be addressed (won’t fix)?

Thanks.
