### ISSUE TITLE
NRE during startup is preventing server from starting

### ISSUE THREAD

**Issue by jamesfera** [ravendb/ravendb#17485]
Build 60002, Version 6.0, SemVer 6.0.0, Commit 434ea49
 PID 9, 64 bits, 8 Cores, Phys Mem 3 GBytes, Arch: X64
 Source Code (git repo): https://github.com/ravendb/ravendb
 Built with love by Hibernating Rhinos and awesome contributors!
+---------------------------------------------------------------+
Using GC in server concurrent mode.
Node A in cluster 2a631f36-4a47-4d41-8141-ddf7a4f97f2f
Server available on: http://ravendb-59b9dcd4f-84fdk:8080
Tcp listening on 10.240.2.79:38888
Server started, listening to requests...
TIP: type 'help' to list the available commands.
ravendb> End of standard input detected, switching to server mode...
Running non-interactive.

UnhandledException occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemoveInternal(TKey key, TValue& value, Boolean matchValue, TValue oldValue)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)
   at Sparrow.Server.Utils.ThreadNames.RemoveFullThreadName(Int64 id) in C:\Builds\RavenDB-Stable-6.0\60002\src\Sparrow.Server\Utils\ThreadNames.cs:line 25
   at Raven.Server.Utils.PoolOfThreads.PooledThread.DoWork() in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Utils\PoolOfThreads.cs:line 245
   at Raven.Server.Utils.PoolOfThreads.PooledThread.Run() in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Utils\PoolOfThreads.cs:line 193
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemoveInternal(TKey key, TValue& value, Boolean matchValue, TValue oldValue)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryRemove(TKey key, TValue& value)
   at Sparrow.Server.Utils.ThreadNames.RemoveFullThreadName(Int64 id) in C:\Builds\RavenDB-Stable-6.0\60002\src\Sparrow.Server\Utils\ThreadNames.cs:line 25
   at Raven.Server.Utils.PoolOfThreads.PooledThread.DoWork() in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Utils\PoolOfThreads.cs:line 245
   at Raven.Server.Utils.PoolOfThreads.PooledThread.Run() in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Utils\PoolOfThreads.cs:line 193
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

**Comment by ayende** [comment]
There should be absolutely no way to _get_ an NRE in this code path that I can see.
Can you check if you run this on a clean location, does it still fail?
