### ISSUE TITLE
Tried to send 'SingleNodeBatchCommand' request - System.TimeoutException: Could not verify that etag

### ISSUE THREAD

**Issue by avaisWes** [ravendb/ravendb#17626]
Hi, we are experiencing intermittent issue with RavenDb while trying to put data on ravendb.

Logs suggest:

`2023-10-27 21:28:03.384 +01:00 [ERR] Tried to send 'SingleNodeBatchCommand' request via `POST /databases/Mist/bulk_docs?&waitForReplicasTimeout=00:00:15&throwOnTimeoutInWaitForReplicas=True&numberOfReplicasToWaitFor=1` to all configured nodes in the topology, none of the attempt succeeded. 
I was able to fetch Mist topology from https://xxx-x-ravdb01.
Topology:
[Url: https://xxx-xxx-ravdb01.ad.xxx.co.uk:444, ClusterTag: B, ServerRole: Member, Exception: System.TimeoutException: Could not verify that etag C:1341-g3XjHU9xqEivfj-wMhkxSQ, B:1979-iEv0XqU9HUexO0MvZUxyVA, A:1981-nfM4tgL1tkSmEiCGqyF4TA was replicated to 1 servers in 00:00:15. So far, it only replicated to 0
   at Raven.Server.Documents.Handlers.BatchHandler.WaitForReplicationAsync(DocumentDatabase database, TimeSpan waitForReplicasTimeout, String numberOfReplicasStr, Boolean throwOnTimeoutInWaitForReplicas, String lastChangeVector) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 343
   at Raven.Server.Documents.Handlers.BatchHandler.BulkDocs() in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 141
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Server\Routing\RequestRouter.cs:line 356
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Server\RavenServerStartup.cs:line 239
..... 
The server at /databases/Mist/bulk_docs?&waitForReplicasTimeout=00:00:15&throwOnTimeoutInWaitForReplicas=True&numberOfReplicasToWaitFor=1 responded with status code: RequestTimeout.
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---<---

   --- End of inner exception stack trace ---
   at Raven.Client.Http.RequestExecutor.ThrowFailedToContactAllNodes[TResult](RavenCommand`1 command, HttpRequestMessage request) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 1186
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token)
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 898
   at Raven.Client.Http.RequestExecutor.HandleServerDown[TResult](String url, ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, Exception e, SessionInfo sessionInfo, Boolean shouldRetry, RequestContext requestContext, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 1536
   at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 1420
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 872
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 898
   at Raven.Client.Http.RequestExecutor.UnlikelyExecuteAsync[TResult](RavenCommand`1 command, JsonOperationContext context, Task topologyUpdate, SessionInfo sessionInfo, CancellationToken token) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 584
   at Raven.Client.Util.AsyncHelpers.RunSync(Func`1 task) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Util\AsyncHelpers.cs:line 40
   at Raven.Client.Http.RequestExecutor.Execute[TResult](RavenCommand`1 command, JsonOperationContext context, SessionInfo sessionInfo) in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Http\RequestExecutor.cs:line 512
   at Raven.Client.Documents.Session.DocumentSession.SaveChanges() in C:\Builds\RavenDB-Stable-5.3\53002\src\Raven.Client\Documents\Session\DocumentSession.cs:line 105
   at ContentHandler.Services.RavenContentHandler.SetByteArray(Byte[] contents, String name, Int32 keepForDays)
   at ContentHandler.Services.RavenContentHandler.SetByteArray(Byte[] contents, String name)
   at Loader.SQL.Services.LoaderService.StartAsync(CancellationToken cancellationToken) in D:\a\1\s\src\applicationname\SQL\Services\LoaderService.cs:line 155
2023-10-27 21:28:03.440 +01:00 [DBG] Sending Active Batch report to for job 304

We have increased the "waitForReplicasTimeout", not sure if that would fix it but would like to get some insights.

Appreciate your inputs

**Comment by garayx** [comment]
Hi

I would start from updating both RavenDB Server version & RavenDB.Client nugget to latest stable LTS version [5.4.111](https://hibernatingrhinos.com/builds?product=RavenDB&version=5.4&channel=Stable&pageNr=1)

The build you are using is almost 2 years old, so you might hit some old bug that was already fixed.
