### ISSUE TITLE
Indexing error with Corax

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17710]
Hello, we upgraded to Raven 6.0 and wanted to try out switching Lucene to Corax and one of our indexes threw the same error multiple times and couldn't complete reindexing.  This is the error - 

Unexpected exception occurred: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'size')
   at Voron.Util.PFor.FastPForDecoder.Init(Byte* input, Int32 size) in C:\Builds\RavenDB-Stable-6.0\60002\src\Voron\Util\PFor\FastPForDecoder.cs:line 46
   at Corax.IndexWriter.AddEntriesToTermResultViaSmallPostingList(Span`1 tmpBuf, EntriesModifications& entries, Int64& termIdInTree, Int64 idInTree) in C:\Builds\RavenDB-Stable-6.0\60002\src\Corax\IndexWriter.cs:line 2439
   at Corax.IndexWriter.TextualFieldInserter.ProcessSingleEntry(EntriesModifications& entries, CompactKeyLookup& key, Boolean isNullTerm, Slice term, Int64 postListId, Int64 termContainerId, Int32 pageOffset) in C:\Builds\RavenDB-Stable-6.0\60002\src\Corax\IndexWriter.cs:line 2067
   at Corax.IndexWriter.TextualFieldInserter.InsertTextualField() in C:\Builds\RavenDB-Stable-6.0\60002\src\Corax\IndexWriter.cs:line 1982
   at Corax.IndexWriter.Commit[TStatsScope](TStatsScope stats) in C:\Builds\RavenDB-Stable-6.0\60002\src\Corax\IndexWriter.cs:line 1780
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexWriteOperation.Commit(IndexingStatsScope stats) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexWriteOperation.cs:line 81
   at Raven.Server.Documents.Indexes.Index.DoIndexingWork(IndexingStatsScope stats, CancellationToken cancellationToken) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Index.cs:line 2538
   at Raven.Server.Documents.Indexes.Index.ExecuteIndexing() in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Index.cs:line 1936

**Comment by ppekrol** [comment]
Hi, we released today version 6.0.1 with fixes around this area. Can you try using that version? Please remember to reset the indexes after the update.

**Comment by arekpalinski** [comment]
Did you have a chance to test it with the usage of version 6.0.1?

**Comment by arekpalinski** [comment]
https://github.com/ravendb/ravendb/issues/17717
