### ISSUE TITLE
Corax error when we do a search 

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17711]
Hello, we upgraded to Raven 6.0 and wanted to try switching from Lucene to Corax. The index is using Standard Analyzer, completed reindexing successfully but errors when we perform a search. That's the error - 

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Corax.IndexSearcher.IndexSearcher.AllInQuery[TTerm](FieldMetadata& field, HashSet`1 allInTerms, Boolean skipEmptyItems, CancellationToken& cancellationToken) in C:\Builds\RavenDB-Stable-6.0\60002\src\Corax\IndexSearcher\MultiTermMatches\IndexSearcher.MultiTermMatches.In.cs:line 89
   at Corax.IndexSearcher.IndexSearcher.AllInQuery(FieldMetadata& field, HashSet`1 allInTerms, Boolean skipEmptyItems, CancellationToken& token) in C:\Builds\RavenDB-Stable-6.0\60002\src\Corax\IndexSearcher\MultiTermMatches\IndexSearcher.MultiTermMatches.In.cs:line 78
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.HandleIn(Parameters builderParameters, InExpression ie, Boolean exact) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 619
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.ToCoraxQuery(Parameters builderParameters, QueryExpression expression, StreamingOptimization& leftOnlyOptimization, Boolean exact, Nullable`1 proximity) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 528
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.ToCoraxQuery(Parameters builderParameters, QueryExpression expression, StreamingOptimization& leftOnlyOptimization, Boolean exact, Nullable`1 proximity) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 386
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxQueryBuilder.BuildQuery(Parameters builderParameters, OrderMetadata[]& sortMetadata) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxQueryBuilder.cs:line 238
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexFacetedReadOperation.FacetedQuery(FacetQuery facetQuery, QueryTimingsScope queryTimings, DocumentsOperationContext context, Func`2 getSpatialField, CancellationToken token) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexFacetedReadOperation.cs:line 57
   at Raven.Server.Documents.Indexes.Index.FacetedQuery(FacetQuery facetQuery, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Indexes\Index.cs:line 3749
   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteFacetedQuery(IndexQueryServerSide query, Nullable`1 existingResultEtag, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Queries\StaticIndexQueryRunner.cs:line 105
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteFacetedQuery(IndexQueryServerSide query, Nullable`1 existingResultEtag, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 195
   at Raven.Server.Documents.Handlers.Processors.Queries.DatabaseQueriesHandlerProcessorForGet.GetFacetedQueryResultAsync(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Handlers\Processors\Queries\DatabaseQueriesHandlerProcessorForGet.cs:line 40
   at Raven.Server.Documents.Handlers.Processors.Queries.AbstractQueriesHandlerProcessorForGet`4.HandleFacetedQueryAsync(IndexQueryServerSide query, TQueryContext queryContext, TOperationContext operationContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Handlers\Processors\Queries\AbstractQueriesHandlerProcessorForGet.cs:line 288
   at Raven.Server.Documents.Handlers.Processors.Queries.AbstractQueriesHandlerProcessorForGet`4.ExecuteAsync() in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Handlers\Processors\Queries\AbstractQueriesHandlerProcessorForGet.cs:line 219
   at Raven.Server.Documents.Handlers.QueriesHandler.Post() in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 15
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\Routing\RequestRouter.cs:line 377
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-6.0\60002\src\Raven.Server\RavenServerStartup.cs:line 254
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass7_0`1.b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

**Comment by ppekrol** [comment]
Hi, we released today version 6.0.1 with fixes around this area. Can you try using that version? Please remember to reset the indexes after the update.

**Comment by arekpalinski** [comment]
https://github.com/ravendb/ravendb/issues/17717
