### ISSUE TITLE
Error reindexing with Corax with Raven 6.0.1

### ISSUE THREAD

**Issue by meghanajoshilw** [ravendb/ravendb#17717]
1. Error using Standard Analyzer - 

System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: System.NullReferenceException: Object reference not set to an instance of an object.
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexReadOperation.HasHighlighting.Setup(IndexQueryServerSide query, DocumentsOperationContext context) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexReadOperation.cs:line 172
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexReadOperation.QueryInternal[THighlighting,TQueryFilter,THasProjection,TDistinct](IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, Reference`1 scannedDocuments, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext() in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexReadOperation.cs:line 624
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Index.cs:line 3559
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Index.cs:line 3559
   at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Index.cs:line 3292
   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Queries\StaticIndexQueryRunner.cs:line 40
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 99
   at Raven.Server.Documents.Handlers.Processors.Queries.DatabaseQueriesHandlerProcessorForGet.GetQueryResultsAsync(IndexQueryServerSide query, QueryOperationContext queryContext, Nullable`1 existingResultEtag, Boolean metadataOnly, OperationCancelToken token) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Handlers\Processors\Queries\DatabaseQueriesHandlerProcessorForGet.cs:line 53
   at Raven.Server.Documents.Handlers.Processors.Queries.AbstractQueriesHandlerProcessorForGet`4.ExecuteAsync() in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Handlers\Processors\Queries\AbstractQueriesHandlerProcessorForGet.cs:line 219
   at Raven.Server.Documents.Handlers.QueriesHandler.Post() in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Handlers\QueriesHandler.cs:line 15
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Routing\RequestRouter.cs:line 387
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\RavenServerStartup.cs:line 254
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass7_0`1.b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---

2. Error with whitespace Analyzer

Unexpected exception occurred: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'size')
   at Voron.Util.PFor.FastPForDecoder.Init(Byte* input, Int32 size) in C:\Builds\RavenDB-Stable-6.0\60003\src\Voron\Util\PFor\FastPForDecoder.cs:line 47
   at Corax.Indexing.IndexWriter.AddEntriesToTermResultViaSmallPostingList(Span`1 tmpBuf, EntriesModifications& entries, Int64& termIdInTree, Int64 idInTree) in C:\Builds\RavenDB-Stable-6.0\60003\src\Corax\Indexing\IndexWriter.cs:line 1558
   at Corax.Indexing.IndexWriter.TextualFieldInserter.ProcessSingleEntry(EntriesModifications& entries, CompactKeyLookup& key, Boolean isNullTerm, Slice term, Int64 postListId, Int64 termContainerId, Int32 pageOffset) in C:\Builds\RavenDB-Stable-6.0\60003\src\Corax\Indexing\IndexWriter.cs:line 1195
   at Corax.Indexing.IndexWriter.TextualFieldInserter.InsertTextualField() in C:\Builds\RavenDB-Stable-6.0\60003\src\Corax\Indexing\IndexWriter.cs:line 1110
   at Corax.Indexing.IndexWriter.Commit[TStatsScope](TStatsScope stats) in C:\Builds\RavenDB-Stable-6.0\60003\src\Corax\Indexing\IndexWriter.cs:line 908
   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexWriteOperation.Commit(IndexingStatsScope stats) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Persistence\Corax\CoraxIndexWriteOperation.cs:line 82
   at Raven.Server.Documents.Indexes.Index.DoIndexingWork(IndexingStatsScope stats, CancellationToken cancellationToken) in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Index.cs:line 2538
   at Raven.Server.Documents.Indexes.Index.ExecuteIndexing() in C:\Builds\RavenDB-Stable-6.0\60003\src\Raven.Server\Documents\Indexes\Index.cs:line 1936

**Comment by grisha-kotler** [comment]
Can you share the index definition and the query?

**Comment by arekpalinski** [comment]
@meghanajoshilw 

1. The first error comes from querying and according to the stacktrace it involves the highlighting feature. We have something similar reported already: https://issues.hibernatingrhinos.com/issue/RavenDB-21702/NRE-in-highlighting


2. This is really interesting and we'd love to get to the root cause of this issue. Can you please provide us with a way of reproducing it?

**Comment by arekpalinski** [comment]
@meghanajoshilw any update from you here?
