### ISSUE TITLE
Cert error after upgrade to ravendb 6.0 nuget

### ISSUE THREAD

**Issue by MohMehrnia** [ravendb/ravendb#17739]
i upgraded ravendb nuget but cert error

```
try
{
    var g = Properties.Resources.Well172;
    using var documentStore = new DocumentStore
    {
        Urls = [ConstantsProperties.RavenDBServer],
        Database = ConstantsProperties.ParameterDB,
        Certificate = cert,
        Conventions = { UseHttpCompression = true }
    };
    documentStore.Initialize();
    using (IAsyncDocumentSession Session = documentStore.OpenAsyncSession(
        new SessionOptions { NoCaching = true }))
    {
        var results = await Session.Query<ParameterInfo>()
            .Customize(cr => cr.WaitForNonStaleResults())
            .Where(c => c.Visible)
            .ToListAsync();
        results.ForEach(
            (record) =>
            {
                record.Title = string.IsNullOrEmpty(record.Title) ? record.Id : record.Title;
            });
        return results;
    }

}
catch (Exception ex)
{
    var f = ex;
    return null;
}
```

**Comment by garayx** [comment]
what is the error (message + full stacktrace) ?

**Comment by MohMehrnia** [comment]
`m_safeCertContext is an invalid handle.`

```
   at System.Security.Cryptography.X509Certificates.X509Certificate.ThrowIfInvalid()
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_HasPrivateKey()
   at Raven.Client.Documents.DocumentStore.Initialize()
   at AIKI.CO.OilWell.Monitoring.RavenDB.LogCreator.<LoadAllParameterProfile>d__24.MoveNext() in D:\MySourceCodes\Projets-Windows (dotnet 8.0)\nisoc-oilwell-monitoring(4.8)\AIKI.CO.OilWell.Monitoring.RavenDB\LogCreator.cs:line 495
```

My Code Work in RavnenDB Nuget 5.x

**Comment by MohMehrnia** [comment]
```
public static readonly X509Certificate2 cert = new(
    Properties.Resources.Well172,
    ConstantsProperties.RavenDbCertificatePassword);
```

cert is valid

**Comment by ppekrol** [comment]
Hi, I think this is related to the change in 6.0. During disposal of DocumentStore the certificate is disposed as well. This can be controlled via DocumentConventions.DisposeCertificate convention https://github.com/ravendb/ravendb/blob/013e95b7105978f097a12012639579934464bad6/src/Raven.Client/Documents/Conventions/DocumentConventions.cs#L1024 

Worth noting here, is that it may also be an indication that you are using multiple instances of DocumentStore in your application and our recommendation would be to use just one (singleton). Example here: https://ravendb.net/docs/article-page/6.0/csharp/client-api/creating-document-store#creating-a-document-store---example
