### ISSUE TITLE
RavenDB.Embedded - Win Arm 64 (macOS M2) - librvnpal version might be invalid, missing or not usable on current platform

### ISSUE THREAD

**Issue by bkempinski** [ravendb/ravendb#17966]
Hello,

I'm attempting to run RavenDB Embedded on Windows through Parallels on a Mac, and I'm encountering the following exception. This issue is likely due to the absence of librvnpal for Windows Arm X64:

### Exception
Unhandled exception. Unhandled exception. System.TypeInitializationException: The type initializer for 'Sparrow.Server.Platform.Pal' threw an exception.
 ---> Sparrow.Utils.IncorrectDllException: librvnpal version might be invalid, missing or not usable on current platform. Initialization error could also be caused by missing 'Microsoft Visual C++ 2015 Redistributable Package' (or newer). It can be downloaded from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. Arch: Arm64, OSDesc: Microsoft Windows 10.0.22621
 ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Sparrow.Utils.DynamicNativeLibraryResolver.Resolver(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath) in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow\Utils\DynamicNativeLibraryResolver.cs:line 70
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Sparrow.Server.Platform.Pal.rvn_get_pal_ver()
   at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 22
   --- End of inner exception stack trace ---
   at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 43
   --- End of inner exception stack trace ---
   at Sparrow.Server.Platform.Pal.rvn_get_pal_ver()
   at Raven.Server.Utils.Cli.RavenCli.GetInfoText() in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Utils\Cli\RavenCli.cs:line 596
   at Raven.Server.Program.Main(String[] args) in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Program.cs:line 125
System.TypeInitializationException: The type initializer for 'Sparrow.Server.Platform.Pal' threw an exception.
 ---> Sparrow.Utils.IncorrectDllException: librvnpal version might be invalid, missing or not usable on current platform. Initialization error could also be caused by missing 'Microsoft Visual C++ 2015 Redistributable Package' (or newer). It can be downloaded from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. Arch: Arm64, OSDesc: Microsoft Windows 10.0.22621
 ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Sparrow.Utils.DynamicNativeLibraryResolver.Resolver(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath) in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow\Utils\DynamicNativeLibraryResolver.cs:line 70
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Sparrow.Server.Platform.Pal.rvn_get_pal_ver()
   at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 22
   --- End of inner exception stack trace ---
   at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 43
   --- End of inner exception stack trace ---
   at Sparrow.Server.Platform.Pal.rvn_get_pal_ver()
   at Raven.Server.Utils.Cli.RavenCli.GetInfoText() in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Utils\Cli\RavenCli.cs:line 596
   at Raven.Server.Program.Main(String[] args) in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Program.cs:line 125

### System Info
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Parallels International GmbH.
System Model:              Parallels ARM Virtual Machine
System Type:               ARM64-based PC
Processor(s):              4 Processor(s) Installed.
                           [01]: ARMv8 (64-bit) Family 8 Model 0 Revision   0   ~3200 Mhz
                           [02]: ARMv8 (64-bit) Family 8 Model 0 Revision   0   ~3200 Mhz
                           [03]: ARMv8 (64-bit) Family 8 Model 0 Revision   0   ~3200 Mhz
                           [04]: ARMv8 (64-bit) Family 8 Model 0 Revision   0   ~3200 Mhz
BIOS Version:              Parallels International GmbH. 19.2.1 (54832), 01/01/1601
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
Input Locale:              en-us;English (United States)
Total Physical Memory:     6,139 MB
Available Physical Memory: 3,062 MB
Virtual Memory: Max Size:  17,403 MB
Virtual Memory: Available: 14,336 MB
Virtual Memory: In Use:    3,067 MB
Page File Location(s):     C:\pagefile.sys
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5032007
                           [02]: KB5029517
                           [03]: KB5033375
                           [04]: KB5032393
Network Card(s):           2 NIC(s) Installed.
                           [01]: Parallels VirtIO Ethernet Adapter
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by ppekrol** [comment]
Hi, at the moment we do not support Windows ARM64. I've created an issue for tracking purposes: https://issues.hibernatingrhinos.com/issue/RavenDB-21913/Support-Windows-ARM64

**Comment by bkempinski** [comment]
Hello @ppekrol, thank you for your response! This feature is particularly valuable, especially for developers who are using Visual Studio. It's worth noting that Visual Studio for Mac is scheduled to be retired on August 31, 2024, and using Visual Studio through Parallels might be the next viable option for Mac users. Cheers!

**Comment by RickTprivate** [comment]
> Hello,
> 
> I'm attempting to run RavenDB Embedded on Windows through Parallels on a Mac, and I'm encountering the following exception. This issue is likely due to the absence of librvnpal for Windows Arm X64:
> 
> ### Exception
> 
> Unhandled exception. Unhandled exception. System.TypeInitializationException: The type initializer for 'Sparrow.Server.Platform.Pal' threw an exception. ---> Sparrow.Utils.IncorrectDllException: librvnpal version might be invalid, missing or not usable on current platform. Initialization error could also be caused by missing 'Microsoft Visual C++ 2015 Redistributable Package' (or newer). It can be downloaded from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. Arch: Arm64, OSDesc: Microsoft Windows 10.0.22621 ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B) at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError) at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError) at Sparrow.Utils.DynamicNativeLibraryResolver.Resolver(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath) in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow\Utils\DynamicNativeLibraryResolver.cs:line 70 at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags) at Sparrow.Server.Platform.Pal.rvn_get_pal_ver() at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 22 --- End of inner exception stack trace --- at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 43 --- End of inner exception stack trace --- at Sparrow.Server.Platform.Pal.rvn_get_pal_ver() at Raven.Server.Utils.Cli.RavenCli.GetInfoText() in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Utils\Cli\RavenCli.cs:line 596 at Raven.Server.Program.Main(String[] args) in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Program.cs:line 125 System.TypeInitializationException: The type initializer for 'Sparrow.Server.Platform.Pal' threw an exception. ---> Sparrow.Utils.IncorrectDllException: librvnpal version might be invalid, missing or not usable on current platform. Initialization error could also be caused by missing 'Microsoft Visual C++ 2015 Redistributable Package' (or newer). It can be downloaded from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads. Arch: Arm64, OSDesc: Microsoft Windows 10.0.22621 ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B) at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError) at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError) at Sparrow.Utils.DynamicNativeLibraryResolver.Resolver(String libraryName, Assembly assembly, Nullable`1 dllImportSearchPath) in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow\Utils\DynamicNativeLibraryResolver.cs:line 70 at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags) at Sparrow.Server.Platform.Pal.rvn_get_pal_ver() at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 22 --- End of inner exception stack trace --- at Sparrow.Server.Platform.Pal..cctor() in D:\Builds\RavenDB-Stable-6.0\60005\src\Sparrow.Server\Platform\Pal.cs:line 43 --- End of inner exception stack trace --- at Sparrow.Server.Platform.Pal.rvn_get_pal_ver() at Raven.Server.Utils.Cli.RavenCli.GetInfoText() in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Utils\Cli\RavenCli.cs:line 596 at Raven.Server.Program.Main(String[] args) in D:\Builds\RavenDB-Stable-6.0\60005\src\Raven.Server\Program.cs:line 125
> 
> ### System Info
> 
> OS Name: Microsoft Windows 11 Pro OS Version: 10.0.22621 N/A Build 22621 OS Manufacturer: Microsoft Corporation OS Configuration: Standalone Workstation OS Build Type: Multiprocessor Free System Manufacturer: Parallels International GmbH. System Model: Parallels ARM Virtual Machine System Type: ARM64-based PC Processor(s): 4 Processor(s) Installed. [01]: ARMv8 (64-bit) Family 8 Model 0 Revision 0 ~3200 Mhz [02]: ARMv8 (64-bit) Family 8 Model 0 Revision 0 ~3200 Mhz [03]: ARMv8 (64-bit) Family 8 Model 0 Revision 0 ~3200 Mhz [04]: ARMv8 (64-bit) Family 8 Model 0 Revision 0 ~3200 Mhz BIOS Version: Parallels International GmbH. 19.2.1 (54832), 01/01/1601 Windows Directory: C:\Windows System Directory: C:\Windows\system32 Boot Device: \Device\HarddiskVolume2 Input Locale: en-us;English (United States) Total Physical Memory: 6,139 MB Available Physical Memory: 3,062 MB Virtual Memory: Max Size: 17,403 MB Virtual Memory: Available: 14,336 MB Virtual Memory: In Use: 3,067 MB Page File Location(s): C:\pagefile.sys Hotfix(s): 4 Hotfix(s) Installed. [01]: KB5032007 [02]: KB5029517 [03]: KB5033375 [04]: KB5032393 Network Card(s): 2 NIC(s) Installed. [01]: Parallels VirtIO Ethernet Adapter Connection Name: Ethernet DHCP Enabled: Yes [02]: Bluetooth Device (Personal Area Network) Connection Name: Bluetooth Network Connection Status: Media disconnected Hyper-V Requirements: A hypervisor has been detected. Features required for Hyper-V will not be displayed.

Hi,

Did you ever find a solution to this problem as I have the same one?
Thanks!

**Comment by ayende** [comment]
Hi,
We currently don't support that, no.
Can you use an x64 instead?

Win ARM 64 is _really_ rare

**Comment by espenrl** [comment]
My operating system is Windows on Arm (Snapdragon X Elite) and I run RavenDB through `Docker Desktop for Windows on Arm`. The images for Linux / ARM works fine.

I remember I had some trouble and needed to explicitly set the arm architecture in docker command line.

**Comment by kenosan** [comment]
It’d be great to have this working. Currently can’t use H&R Block 2025 Premium & Business on Parallels Windows 11 VM running on a Mac Studio M4 because of this issue.

**Comment by ayende** [comment]
Windows ARM64 is not currently supported. Closing due to age — please reopen or file a new issue if demand increases.
