### ISSUE TITLE
Backup Restore ends in Exception

### ISSUE THREAD

**Issue by tobiaszuercher** [ravendb/ravendb#18216]
I'm restoring a 160GB backup into a new database. After 4h59' i get the following exception:

```
Unexpected index argument value: 42 (Parameter 'index')
Actual value was 42.
System.ArgumentOutOfRangeException: Unexpected index argument value: 42 (Parameter 'index')
Actual value was 42.
   at Sparrow.Json.BlittableJsonReaderObject.ThrowOutOfRangeException(Int32 indexValue) in D:\Builds\RavenDB-Stable-5.4\54106\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 788
   at Sparrow.Json.BlittableJsonReaderObject.GetPropertyByIndex(Int32 index, PropertyDetails& prop, Boolean addObjectToCache) in D:\Builds\RavenDB-Stable-5.4\54106\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 752
   at Raven.Server.Documents.CountersStorage.CreateHalfDocument(DocumentsOperationContext context, BlittableJsonReaderObject values, Int32 start, Int32 end, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\CountersStorage.cs:line 866
   at Raven.Server.Documents.CountersStorage.SplitCounterDocument(DocumentsOperationContext context, BlittableJsonReaderObject values, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\CountersStorage.cs:line 719
   at Raven.Server.Documents.CountersStorage.SplitCounterGroup(DocumentsOperationContext context, CollectionName collectionName, Table table, Slice documentKeyPrefix, Slice countersGroupKey, BlittableJsonReaderObject values, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames, String changeVector) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\CountersStorage.cs:line 585
   at Raven.Server.Documents.CountersStorage.PutCounters(DocumentsOperationContext context, String documentId, String collection, String changeVector, BlittableJsonReaderObject sourceData) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\CountersStorage.cs:line 1106
   at Raven.Server.Documents.Handlers.CountersHandler.SmugglerCounterBatchCommand.PutCounters(DocumentsOperationContext context, CounterGroupDetail counterGroupDetail) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\Handlers\CountersHandler.cs:line 468
   at Raven.Server.Documents.Handlers.CountersHandler.SmugglerCounterBatchCommand.ExecuteCmd(DocumentsOperationContext context) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\Handlers\CountersHandler.cs:line 391
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 executedOps, DocumentsOperationContext context, Task previousOperation, DurationMeasurement& meter) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 930
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsWithAsyncCommit(DocumentsOperationContext& previous, IDisposable& returnPreviousContext, List`1 previousPendingOps) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 707
--- End of stack trace from previous location ---
   at Raven.Server.Documents.TransactionOperationsMerger.Enqueue(MergedTransactionCommand cmd) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 142
   at Raven.Server.Smuggler.Documents.DatabaseDestination.CounterActions.HandleBatchOfCountersIfNecessaryAsync() in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseDestination.cs:line 2157
   at Raven.Server.Smuggler.Documents.DatabaseDestination.CounterActions.WriteCounterAsync(CounterGroupDetail counterDetail) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseDestination.cs:line 2115
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessCountersAsync(SmugglerResult result) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 939
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessCountersAsync(SmugglerResult result) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 939
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessCountersAsync(SmugglerResult result) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 939
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessTypeAsync(DatabaseItemType type, SmugglerResult result, BuildVersionType buildType, Boolean ensureStepsProcessed) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 292
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ExecuteAsync(Boolean ensureStepsProcessed, Boolean isLastFile) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 111
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ExecuteAsync(Boolean ensureStepsProcessed, Boolean isLastFile) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 111
   at Raven.Server.Documents.PeriodicBackup.Restore.RestoreBackupTaskBase.ImportSingleBackupFile(DocumentDatabase database, Action`1 onProgress, RestoreResult restoreResult, String filePath, DocumentsOperationContext context, DatabaseDestination destination, DatabaseSmugglerOptionsServerSide options, Boolean isLastFile, Action`1 onIndexAction, Action`1 onDatabaseRecordAction) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\PeriodicBackup\Restore\RestoreBackupTaskBase.cs:line 968
   at Raven.Server.Documents.PeriodicBackup.Restore.RestoreBackupTaskBase.ImportSingleBackupFile(DocumentDatabase database, Action`1 onProgress, RestoreResult restoreResult, String filePath, DocumentsOperationContext context, DatabaseDestination destination, DatabaseSmugglerOptionsServerSide options, Boolean isLastFile, Action`1 onIndexAction, Action`1 onDatabaseRecordAction) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\PeriodicBackup\Restore\RestoreBackupTaskBase.cs:line 968
   at Raven.Server.Documents.PeriodicBackup.Restore.RestoreBackupTaskBase.ImportSingleBackupFile(DocumentDatabase database, Action`1 onProgress, RestoreResult restoreResult, String filePath, DocumentsOperationContext context, DatabaseDestination destination, DatabaseSmugglerOptionsServerSide options, Boolean isLastFile, Action`1 onIndexAction, Action`1 onDatabaseRecordAction) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\PeriodicBackup\Restore\RestoreBackupTaskBase.cs:line 968
   at Raven.Server.Documents.PeriodicBackup.Restore.RestoreBackupTaskBase.ImportSingleBackupFile(DocumentDatabase database, Action`1 onProgress, RestoreResult restoreResult, String filePath, DocumentsOperationContext context, DatabaseDestination destination, DatabaseSmugglerOptionsServerSide options, Boolean isLastFile, Action`1 onIndexAction, Action`1 onDatabaseRecordAction) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\PeriodicBackup\Restore\RestoreBackupTaskBase.cs:line 968
   at Raven.Server.Documents.PeriodicBackup.Restore.RestoreBackupTaskBase.SmugglerRestore(DocumentDatabase database, List`1 filesToRestore, DocumentsOperationContext context, DatabaseRecord databaseRecord, Action`1 onProgress, RestoreResult result, DatabaseDestination lastFileDestination) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\PeriodicBackup\Restore\RestoreBackupTaskBase.cs:line 840
   at Raven.Server.Documents.PeriodicBackup.Restore.RestoreBackupTaskBase.Execute(Action`1 onProgress) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\PeriodicBackup\Restore\RestoreBackupTaskBase.cs:line 380
   at Raven.Server.Documents.PeriodicBackup.Restore.RestoreBackupTaskBase.Execute(Action`1 onProgress) in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Documents\PeriodicBackup\Restore\RestoreBackupTaskBase.cs:line 462
   at Raven.Server.Web.System.AdminDatabasesHandler.<>c__DisplayClass10_1.<<RestoreDatabase>b__1>d.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54106\src\Raven.Server\Web\System\AdminDatabasesHandler.cs:line 659
```

The importing raven server runs 5.4.116.
The backup was done probably with 5.4.110 (not yet sure anymore). maybe it was higher. in 5.4.112 there was a breaking change. but i saw the studio also tell me that it cant import a backup if it wasn't compatible anymore. so i guess it has nothing to do with that breaking change.

i'm trying again creating a backup with 5.4.116 and re-import.

**Comment by tobiaszuercher** [comment]
question: given folder permission is under control: is it save to just copy/move the Database folder located in RavenData/Databases/MyDB?

idea:
- stop source & target raven server
- rsync from the old server to the new
- start the new server

or is there more state in the System DB that would have to be synced?

**Comment by ayende** [comment]
Yes, you can stop & rsync the files. Need to ensure that the db user has rights to it, but that is about it.

**Comment by ayende** [comment]
About the backup error. Are you uploading the file and is it possible that the upload connection failed?
There is no issue with backing up from an _old_ version

**Comment by tobiaszuercher** [comment]
the file was on the same disk as the running server and mounted into the container -> no upload connection failed

**Comment by ayende** [comment]
Did you restore it again, did it work?

**Comment by tobiaszuercher** [comment]
i could successfully import the newly created backup.
