### ISSUE TITLE
Unable to load document without ChangeVector in a cluster transaction session

### ISSUE THREAD

**Issue by crazedpeanut** [ravendb/ravendb#18225]
We get a `ArgumentNullException` when trying to load documents that do not have a ChangeVector, while in a session that has a `TransactionMode `of `ClusterWide`.

Suggested change to `DocumentHandler.cs` ![image](https://github.com/ravendb/ravendb/assets/7700874/b6a78c6b-b46d-4387-aab0-565f536a87a8)

```
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
at System.String.Contains(String value)
at Raven.Server.Documents.Handlers.DocumentHandler.GetDocumentsByIdAsync(DocumentsOperationContext context, StringValues ids, Boolean metadataOnly) in C:\Builds\RavenDB-Stable-5.4\54083\src\Raven.Server\Documents\Handlers\DocumentHandler.cs:line 338
at Raven.Server.Documents.Handlers.DocumentHandler.Get() in C:\Builds\RavenDB-Stable-5.4\54083\src\Raven.Server\Documents\Handlers\DocumentHandler.cs:line 131
at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in C:\Builds\RavenDB-Stable-5.4\54083\src\Raven.Server\Routing\RequestRouter.cs:line 375
at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\Builds\RavenDB-Stable-5.4\54083\src\Raven.Server\RavenServerStartup.cs:line 255 at Raven.Client.Exceptions.ExceptionDispatcher.<Throw>d__3.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54109\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 121
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Raven.Client.Http.RequestExecutor.<HandleUnsuccessfulResponse>d__141`1.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54109\src\Raven.Client\Http\RequestExecutor.cs:line 1580
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Raven.Client.Http.RequestExecutor.<ExecuteAsync>d__117`1.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54109\src\Raven.Client\Http\RequestExecutor.cs:line 969
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Raven.Client.Http.RequestExecutor.<ExecuteAsync>d__117`1.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54109\src\Raven.Client\Http\RequestExecutor.cs:line 994
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Raven.Client.Documents.Session.AsyncDocumentSession.<LoadAsyncInternal>d__61.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54109\src\Raven.Client\Documents\Session\AsyncDocumentSession.Load.cs:line 211
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Raven.Client.Documents.Session.AsyncDocumentSession.<LoadAsync>d__53`1.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54109\src\Raven.Client\Documents\Session\AsyncDocumentSession.Load.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by grisha-kotler** [comment]
This is fixed here: https://github.com/ravendb/ravendb/pull/17508
You need to upgrade the server to `5.4.116` (same as the client version that you are running).
