### ISSUE TITLE
Can't delete DB on arm64v8 Docker image

### ISSUE THREAD

**Issue by felix029** [ravendb/ravendb#18341]
Running on Mac M3 Pro with this docker-compose:
``` 
 ravendb-master:
    image: ravendb/ravendb:6.0-ubuntu-arm64v8-latest
    hostname: ravendb-master
    volumes:
      - raven-master-data:/var/lib/ravendb/data
    environment:
      RAVEN_Setup_Mode: None
      RAVEN_License_Eula_Accepted: true
      RAVEN_PublicServerUrl: http://localhost:8080
      RAVEN_Security_UnsecuredAccessAllowed: PrivateNetwork
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '3'
```

Everything works fine until I delete a DB. When I do so, the DB I'm trying to delete stays stuck in `LOADING...` state forever.

The problem occurs mostly after I do a docker-compose down and then bring it back up, making me think it is related with the volume I mounted.

This seems to be a problem only on the arm image since I don't have this issue with this image on a windows desktop: 
`ravendb/ravendb:6.0.101-windows-1809`

Here are the debug logs related to this:
[arm64v8_cant_delete_db_logs.zip](https://github.com/ravendb/ravendb/files/14873933/arm64v8_cant_delete_db_logs.zip)

**Comment by ayende** [comment]
Can you _create_ a database?
From the logs you sent, it looks like in terms of firewall, it is unable to talk to itself.

Can you go to Admin > Logs and watch the _debug_ logs when you do this?

**Comment by felix029** [comment]
I can successfully create databases.

From what I saw in the logs, it indeed seems to be a problem in terms of firewall:

```
2024-04-04T18:13:18.9156604Z, 26, Information, Heartbeats supervisor from A to A in term 3, Raven.Server.ServerWide.Maintenance.ClusterMaintenanceSupervisor+ClusterNode, Exception was thrown while collecting info from A, EXCEPTION: System.AggregateException: Failed to connect to all urls tcp://localhost:38888 (Connection refused)
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Sockets.TcpClient.CompleteConnectAsync(ValueTask task)
   at Raven.Client.Util.TcpUtils.ConnectAsync(String url, Nullable`1 timeout, Boolean useIPv6, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60017\src\Raven.Client\Util\TcpUtils.cs:line 146
   at Raven.Client.Util.TcpUtils.ConnectSecuredTcpSocket(TcpConnectionInfo info, X509Certificate2 cert, CipherSuitesPolicy cipherSuitesPolicy, OperationTypes operationType, NegotiationCallback negotiationCallback, JsonOperationContext negContext, Nullable`1 timeout, List`1 logs, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60017\src\Raven.Client\Util\TcpUtils.cs:line 320
   --- End of inner exception stack trace ---
   at Raven.Client.Util.TcpUtils.ConnectSecuredTcpSocket(TcpConnectionInfo info, X509Certificate2 cert, CipherSuitesPolicy cipherSuitesPolicy, OperationTypes operationType, NegotiationCallback negotiationCallback, JsonOperationContext negContext, Nullable`1 timeout, List`1 logs, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60017\src\Raven.Client\Util\TcpUtils.cs:line 364
   at Raven.Server.ServerWide.Maintenance.ClusterMaintenanceSupervisor.ClusterNode.ConnectToClientNodeAsync(TcpConnectionInfo tcpConnectionInfo, TimeSpan timeout) in D:\Builds\RavenDB-Stable-6.0\60017\src\Raven.Server\ServerWide\Maintenance\ClusterMaintenanceSupervisor.cs:line 479
   at Raven.Client.Util.AsyncHelpers.RunSync[T](Func`1 task)
   at Raven.Server.ServerWide.Maintenance.ClusterMaintenanceSupervisor.ClusterNode.ConnectToClientNode(TcpConnectionInfo tcpConnectionInfo, TimeSpan timeout) in D:\Builds\RavenDB-Stable-6.0\60017\src\Raven.Server\ServerWide\Maintenance\ClusterMaintenanceSupervisor.cs:line 468
   at Raven.Server.ServerWide.Maintenance.ClusterMaintenanceSupervisor.ClusterNode.ListenToMaintenanceWorker() in D:\Builds\RavenDB-Stable-6.0\60017\src\Raven.Server\ServerWide\Maintenance\ClusterMaintenanceSupervisor.cs:line 281
```

**Comment by felix029** [comment]
After further investigation, I found out that this configuration with the specified PublicServerUrl_Tcp config seems to be doing the trick. 
```
 ravendb-master:
    image: ravendb/ravendb:6.0-ubuntu-arm64v8-latest
    hostname: ravendb-master
    volumes:
      - raven-master-data:/var/lib/ravendb/data
    environment:
      RAVEN_Setup_Mode: None
      RAVEN_License_Eula_Accepted: true
      RAVEN_PublicServerUrl: http://localhost:8080
      RAVEN_PublicServerUrl_Tcp: tcp://localhost:38888
      RAVEN_ServerUrl_Tcp: tcp://localhost:38888
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '3'
```

Somehow this is not required with the Windows image.

**Comment by ayende** [comment]
I cannot explain the difference. Those are the _default_ values, after all. 
Should have identical behaviors.
