### ISSUE TITLE
Corrupted Counters

### ISSUE THREAD

**Issue by tobiaszuercher** [ravendb/ravendb#18802]
Hi
in SaveChangesAsync() we get the following exception:

```
Raven.Client.Exceptions.RavenException: System.ArgumentOutOfRangeException: Unexpected index argument value: 24 (Parameter 'index')
Actual value was 24.
   at Sparrow.Json.BlittableJsonReaderObject.ThrowOutOfRangeException(Int32 indexValue) in D:\Builds\RavenDB-Stable-5.4\54133\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 788
   at Sparrow.Json.BlittableJsonReaderObject.GetPropertyByIndex(Int32 index, PropertyDetails& prop, Boolean addObjectToCache) in D:\Builds\RavenDB-Stable-5.4\54133\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 756
   at Raven.Server.Documents.CountersStorage.CreateHalfDocument(DocumentsOperationContext context, BlittableJsonReaderObject values, Int32 start, Int32 end, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 848
   at Raven.Server.Documents.CountersStorage.SplitCounterGroup(DocumentsOperationContext context, CollectionName collectionName, Table table, Slice documentKeyPrefix, Slice countersGroupKey, BlittableJsonReaderObject values, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames, String changeVector) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 536
   at Raven.Server.Documents.CountersStorage.PutOrIncrementCounter(DocumentsOperationContext context, String documentId, String collection, String name, Int64 delta, Boolean& exists, Boolean overrideExisting) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 435
   at Raven.Server.Documents.Handlers.CountersHandler.ExecuteCounterBatchCommand.ExecuteCmd(DocumentsOperationContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\Handlers\CountersHandler.cs:line 112
   at Raven.Server.Documents.Handlers.BatchHandler.MergedBatchCommand.ExecuteCmd(DocumentsOperationContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 1205
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 executedOps, DocumentsOperationContext context, Task previousOperation, DurationMeasurement& meter) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 890
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsOnce() in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 517
--- End of stack trace from previous location ---
   at Raven.Server.Documents.TransactionOperationsMerger.Enqueue(MergedTransactionCommand cmd) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 129
   at Raven.Server.Documents.Handlers.BatchHandler.BulkDocs() in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 110
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Routing\RequestRouter.cs:line 407
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\RavenServerStartup.cs:line 184
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'System.ArgumentOutOfRangeException: Unexpected index argument value: 24 (Parameter 'index')
Actual value was 24.
   at Sparrow.Json.BlittableJsonReaderObject.ThrowOutOfRangeException(Int32 indexValue) in D:\Builds\RavenDB-Stable-5.4\54133\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 788
   at Sparrow.Json.BlittableJsonReaderObject.GetPropertyByIndex(Int32 index, PropertyDetails& prop, Boolean addObjectToCache) in D:\Builds\RavenDB-Stable-5.4\54133\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 756
   at Raven.Server.Documents.CountersStorage.CreateHalfDocument(DocumentsOperationContext context, BlittableJsonReaderObject values, Int32 start, Int32 end, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 848
   at Raven.Server.Documents.CountersStorage.SplitCounterGroup(DocumentsOperationContext context, CollectionName collectionName, Table table, Slice documentKeyPrefix, Slice countersGroupKey, BlittableJsonReaderObject values, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames, String changeVector) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 536
   at Raven.Server.Documents.CountersStorage.PutOrIncrementCounter(DocumentsOperationContext context, String documentId, String collection, String name, Int64 delta, Boolean& exists, Boolean overrideExisting) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 435
   at Raven.Server.Documents.Handlers.CountersHandler.ExecuteCounterBatchCommand.ExecuteCmd(DocumentsOperationContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\Handlers\CountersHandler.cs:line 112
   at Raven.Server.Documents.Handlers.BatchHandler.MergedBatchCommand.ExecuteCmd(DocumentsOperationContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 1205
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 executedOps, DocumentsOperationContext context, Task previousOperation, DurationMeasurement& meter) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 890
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsOnce() in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 517
--- End of stack trace from previous location ---
   at Raven.Server.Documents.TransactionOperationsMerger.Enqueue(MergedTransactionCommand cmd) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 129
   at Raven.Server.Documents.Handlers.BatchHandler.BulkDocs() in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\Handlers\BatchHandler.cs:line 110
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Routing\RequestRouter.cs:line 407
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\RavenServerStartup.cs:line 184')
   --- End of inner exception stack trace ---
   at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, Action`1 additionalErrorInfo) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 119
   at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Client\Http\RequestExecutor.cs:line 1535
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Client\Http\RequestExecutor.cs:line 971
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Client\Http\RequestExecutor.cs:line 996
   at Raven.Client.Documents.Session.AsyncDocumentSession.SaveChangesAsync(CancellationToken token) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 184
   at X.X.X.X.X(Int32 id) in /app/src/X.X.X/X.cs:line 192
   at X.X.X.X.X(CancellationToken cancellationToken) in /app/src/X.X.X/X.cs:line 68
```

The SaveChangesAsync() should store or update some documents, time series and counters.

In order to debug the issue locally, i've tried to import it to a local database which already has some data. It fails with the same error:

```
[11:47:15 INFO] Read 854,000 counters.
Unexpected index argument value: 29 (Parameter 'index')
Actual value was 29.
System.ArgumentOutOfRangeException: Unexpected index argument value: 29 (Parameter 'index')
Actual value was 29.
   at Sparrow.Json.BlittableJsonReaderObject.ThrowOutOfRangeException(Int32 indexValue) in D:\Builds\RavenDB-Stable-5.4\54133\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 788
   at Sparrow.Json.BlittableJsonReaderObject.GetPropertyByIndex(Int32 index, PropertyDetails& prop, Boolean addObjectToCache) in D:\Builds\RavenDB-Stable-5.4\54133\src\Sparrow\Json\BlittableJsonReaderObject.cs:line 756
   at Raven.Server.Documents.CountersStorage.CreateHalfDocument(DocumentsOperationContext context, BlittableJsonReaderObject values, Int32 start, Int32 end, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 848
   at Raven.Server.Documents.CountersStorage.SplitCounterDocument(DocumentsOperationContext context, BlittableJsonReaderObject values, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 716
   at Raven.Server.Documents.CountersStorage.SplitCounterGroup(DocumentsOperationContext context, CollectionName collectionName, Table table, Slice documentKeyPrefix, Slice countersGroupKey, BlittableJsonReaderObject values, BlittableJsonReaderArray dbIds, BlittableJsonReaderObject originalNames, String changeVector) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 536
   at Raven.Server.Documents.CountersStorage.PutCounters(DocumentsOperationContext context, String documentId, String collection, String changeVector, BlittableJsonReaderObject sourceData) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\CountersStorage.cs:line 1106
   at Raven.Server.Documents.Handlers.CountersHandler.SmugglerCounterBatchCommand.PutCounters(DocumentsOperationContext context, CounterGroupDetail counterGroupDetail)
   at Raven.Server.Documents.Handlers.CountersHandler.SmugglerCounterBatchCommand.ExecuteCmd(DocumentsOperationContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\Handlers\CountersHandler.cs:line 385
   at Raven.Server.Documents.TransactionOperationsMerger.ExecutePendingOperationsInTransaction(List`1 executedOps, DocumentsOperationContext context, Task previousOperation, DurationMeasurement& meter) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 890
   at Raven.Server.Documents.TransactionOperationsMerger.MergeTransactionsWithAsyncCommit(DocumentsOperationContext& previous, IDisposable& returnPreviousContext, List`1 previousPendingOps) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 707
--- End of stack trace from previous location ---
   at Raven.Server.Documents.TransactionOperationsMerger.Enqueue(MergedTransactionCommand cmd) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Documents\TransactionOperationsMerger.cs:line 129
   at Raven.Server.Smuggler.Documents.DatabaseDestination.CounterActions.HandleBatchOfCountersIfNecessaryAsync() in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseDestination.cs:line 2204
   at Raven.Server.Smuggler.Documents.DatabaseDestination.CounterActions.WriteCounterAsync(CounterGroupDetail counterDetail) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseDestination.cs:line 2168
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessCountersAsync(SmugglerResult result) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 923
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessCountersAsync(SmugglerResult result) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 912
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessCountersAsync(SmugglerResult result) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 912
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ProcessTypeAsync(DatabaseItemType type, SmugglerResult result, BuildVersionType buildType, Boolean ensureStepsProcessed) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 246
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ExecuteAsync(Boolean ensureStepsProcessed, Boolean isLastFile) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 99
   at Raven.Server.Smuggler.Documents.DatabaseSmuggler.ExecuteAsync(Boolean ensureStepsProcessed, Boolean isLastFile) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\DatabaseSmuggler.cs:line 109
   at Raven.Server.Smuggler.Documents.Handlers.SmugglerHandler.DoImportInternalAsync(DocumentsOperationContext context, Stream stream, DatabaseSmugglerOptionsServerSide options, SmugglerResult result, Action`1 onProgress, OperationCancelToken token) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\Handlers\SmugglerHandler.cs:line 969
   at Raven.Server.Smuggler.Documents.Handlers.SmugglerHandler.DoImportInternalAsync(DocumentsOperationContext context, Stream stream, DatabaseSmugglerOptionsServerSide options, SmugglerResult result, Action`1 onProgress, OperationCancelToken token) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\Handlers\SmugglerHandler.cs:line 970
   at Raven.Server.Smuggler.Documents.Handlers.SmugglerHandler.<>c__DisplayClass16_1.<<PostImportAsync>b__1>d.MoveNext() in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\Handlers\SmugglerHandler.cs:line 733
--- End of stack trace from previous location ---
   at Raven.Server.Smuggler.Documents.Handlers.SmugglerHandler.PostImportAsync() in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Smuggler\Documents\Handlers\SmugglerHandler.cs:line 678
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\Routing\RequestRouter.cs:line 407
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\Builds\RavenDB-Stable-5.4\54133\src\Raven.Server\RavenServerStartup.cs:line 184
```

Creating a new & fresh db, it fails also while importing with the same error. i was exporting the data using the Tasks -> Export Database -> Did choose only 1 collection.

Version 5.4.200

This looks to me as a bug in raven.

**Comment by grisha-kotler** [comment]
Can you send us the exported database?

**Comment by tobiaszuercher** [comment]
i did. any update?

**Comment by grisha-kotler** [comment]
@tobiaszuercher we're looking into this.

**Comment by tobiaszuercher** [comment]
was there ever an outcome or a fix?

**Comment by ayende** [comment]
That was fixed here, I believe: https://github.com/ravendb/ravendb/pull/19409
