### ISSUE TITLE
RavenDB 6.0: Invalid checksum for page x, Raven.voron might be corrupted (out of nowhere)

### ISSUE THREAD

**Issue by victornor** [ravendb/ravendb#18993]
Out of nowhere, my C# applications using a ravendb server are all throwing exceptions.
It's running on a ubuntu 22.04 server, which was restarted a few days ago (no idea if this has anything to do with it).
I see no errors anywhere in the database dashboard and the database still seems to be somewhat functional.

Here's the stackrace:

> System.IO.InvalidDataException: Invalid checksum for page 234794, data file /var/lib/ravendb/data/Databases/ig/Raven.voron might be corrupted, expected hash to be 5407215390887200039 but was 11362497751045971862. Page flags: Single, VariableSizeTreePage. 
   at Voron.StorageEnvironment.ThrowInvalidChecksum(Int64 pageNumber, PageHeader* current, UInt64 checksum) in D:\Builds\RavenDB-Stable-6.0\60035\src\Voron\StorageEnvironment.cs:line 1610
   at Voron.StorageEnvironment.UnlikelyValidatePage(Int64 pageNumber, PageHeader* current, Int64 index, Int64 old, Int64 bitToSet) in D:\Builds\RavenDB-Stable-6.0\60035\src\Voron\StorageEnvironment.cs:line 1573
   at Voron.Impl.LowLevelTransaction.GetPageInternal(Int64 pageNumber) in D:\Builds\RavenDB-Stable-6.0\60035\src\Voron\Impl\LowLevelTransaction.cs:line 655
   at Voron.Data.BTrees.Tree.SearchForPage(Slice key, TreeNodeHeader*& node) in D:\Builds\RavenDB-Stable-6.0\60035\src\Voron\Data\BTrees\Tree.cs:line 774
   at Raven.Server.Documents.DocumentPutAction.PutDocument(DocumentsOperationContext context, String id, String expectedChangeVector, BlittableJsonReaderObject document, Nullable`1 lastModifiedTicks, ChangeVector changeVector, String oldChangeVectorForClusterTransactionIndexCheck, DocumentFlags newFlags, NonPersistentDocumentFlags nonPersistentFlags) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\DocumentPutAction.cs:line 142
   at Raven.Server.Documents.Handlers.Batches.Commands.MergedBatchCommand.ExecuteCmd(DocumentsOperationContext context) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\Handlers\Batches\Commands\MergedBatchCommand.cs:line 58
   at Raven.Server.Documents.TransactionMerger.AbstractTransactionOperationsMerger`2.ExecutePendingOperationsInTransaction(List`1 executedOps, TOperationContext context, Task previousOperation, DurationMeasurement& meter) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\TransactionMerger\AbstractTransactionOperationsMerger.cs:line 717
   at Raven.Server.Documents.TransactionMerger.AbstractTransactionOperationsMerger`2.MergeTransactionsOnce() in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\TransactionMerger\AbstractTransactionOperationsMerger.cs:line 358
--- End of stack trace from previous location ---
   at Raven.Server.Documents.TransactionMerger.AbstractTransactionOperationsMerger`2.Enqueue(MergedTransactionCommand`2 cmd) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\TransactionMerger\AbstractTransactionOperationsMerger.cs:line 124
   at Raven.Server.Documents.Handlers.Processors.Batches.BatchHandlerProcessorForBulkDocs.HandleTransactionAsync(JsonOperationContext context, MergedBatchCommand command, IndexBatchOptions indexBatchOptions, ReplicationBatchOptions replicationBatchOptions) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\Handlers\Processors\Batches\BatchHandlerProcessorForBulkDocs.cs:line 37
   at Raven.Server.Documents.Handlers.Processors.Batches.AbstractBatchHandlerProcessorForBulkDocs`3.ExecuteInternalAsync() in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\Handlers\Processors\Batches\AbstractBatchHandlerProcessorForBulkDocs.cs:line 124
   at Raven.Server.Documents.Handlers.Processors.Batches.AbstractBatchHandlerProcessorForBulkDocs`3.ExecuteAsync() in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\Handlers\Processors\Batches\AbstractBatchHandlerProcessorForBulkDocs.cs:line 48
   at Raven.Server.Documents.Handlers.Batches.BatchHandler.BulkDocs() in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Documents\Handlers\Batches\BatchHandler.cs:line 13
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\Routing\RequestRouter.cs:line 413
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Server\RavenServerStartup.cs:line 192
   at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, CommandUnsuccessfulResponseBehavior unsuccessfulResponseBehavior) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 116
   at Raven.Client.Exceptions.ExceptionDispatcher.Throw(JsonOperationContext context, HttpResponseMessage response, CommandUnsuccessfulResponseBehavior unsuccessfulResponseBehavior) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Client\Exceptions\ExceptionDispatcher.cs:line 120
   at Raven.Client.Http.Behaviors.DefaultCommandResponseBehavior.TryHandleUnsuccessfulResponseAsync[TResult](JsonOperationContext context, RavenCommand`1 command, HttpResponseMessage response, CommandUnsuccessfulResponseBehavior unsuccessfulResponseBehavior) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Client\Http\Behaviors\DefaultCommandResponseBehavior.cs:line 52
   at Raven.Client.Http.RequestExecutor.HandleUnsuccessfulResponse[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, HttpRequestMessage request, HttpResponseMessage response, String url, SessionInfo sessionInfo, Boolean shouldRetry, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Client\Http\RequestExecutor.cs:line 1630
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Client\Http\RequestExecutor.cs:line 1026
   at Raven.Client.Http.RequestExecutor.ExecuteAsync[TResult](ServerNode chosenNode, Nullable`1 nodeIndex, JsonOperationContext context, RavenCommand`1 command, Boolean shouldRetry, SessionInfo sessionInfo, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Client\Http\RequestExecutor.cs:line 1051
   at Raven.Client.Documents.Session.AsyncDocumentSession.SaveChangesAsync(CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60035\src\Raven.Client\Documents\Session\AsyncDocumentSession.cs:line 175

**Comment by ayende** [comment]
You can try running `Voron.Recovery` - but the first thing to do is to check if there has been some corruption on the disk level.
Are you hosting RavenDB on a container? Network drive?
Physical drive?

Check you do a disk check?
