### ISSUE TITLE
System.IndexOutOfRangeException on query

### ISSUE THREAD

**Issue by alex-bermishev** [ravendb/ravendb#19336]
after upgrading existing database to stable 6.0, we encountered the following problem

```
2024-09-26T07:45:50.5331216Z, 7, Information, Server, Raven.Server.RavenServerStartup, POST /databases/archive/streams/queries - 200 - 23 ms, EXCEPTION: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Raven.Server.Documents.Queries.StreamQueryResult`1.HandleExceptionAsync(Exception e, CancellationToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Queries\StreamQueryResult.cs:line 108
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Indexes\Index.cs:line 3518
   at Raven.Server.Documents.Indexes.Index.StreamQuery(HttpResponse response, IStreamQueryResultWriter`1 writer, IndexQueryServerSide query, QueryOperationContext queryContext, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Indexes\Index.cs:line 3261
   at Raven.Server.Documents.Queries.StaticIndexQueryRunner.ExecuteStreamQuery(IndexQueryServerSide query, QueryOperationContext queryContext, HttpResponse response, IStreamQueryResultWriter`1 writer, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Queries\StaticIndexQueryRunner.cs:line 50
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteStreamQuery(IndexQueryServerSide query, QueryOperationContext queryContext, HttpResponse response, IStreamQueryResultWriter`1 writer, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Queries\QueryRunner.cs:line 109
   at Raven.Server.Documents.Handlers.Processors.Streaming.StreamingHandlerProcessorForGetStreamQuery.ExecuteAndWriteQueryStreamAsync(DocumentsOperationContext context, IndexQueryServerSide query, String format, String[] propertiesArray, String fileNamePrefix, Boolean _, Boolean fromSharded, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Handlers\Processors\Streaming\StreamingHandlerProcessorForGetStreamQuery.cs:line 86
   at Raven.Server.Documents.Handlers.Processors.Streaming.StreamingHandlerProcessorForGetStreamQuery.ExecuteAndWriteQueryStreamAsync(DocumentsOperationContext context, IndexQueryServerSide query, String format, String[] propertiesArray, String fileNamePrefix, Boolean _, Boolean fromSharded, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Handlers\Processors\Streaming\StreamingHandlerProcessorForGetStreamQuery.cs:line 114
   at Raven.Server.Documents.Handlers.Processors.Streaming.StreamingHandlerProcessorForGetStreamQuery.ExecuteAndWriteQueryStreamAsync(DocumentsOperationContext context, IndexQueryServerSide query, String format, String[] propertiesArray, String fileNamePrefix, Boolean _, Boolean fromSharded, OperationCancelToken token) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Handlers\Processors\Streaming\StreamingHandlerProcessorForGetStreamQuery.cs:line 115
   at Raven.Server.Documents.Handlers.Processors.Streaming.AbstractStreamingHandlerProcessorForGetStreamQuery`2.ExecuteAsync() in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Handlers\Processors\Streaming\AbstractStreamingHandlerProcessorForGetStreamQuery.cs:line 131
   at Raven.Server.Documents.Handlers.Streaming.StreamingHandler.StreamQueryPost() in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Documents\Handlers\Streaming\StreamingHandler.cs:line 43
   at Raven.Server.Routing.RequestRouter.HandlePath(RequestHandlerContext reqCtx) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\Routing\RequestRouter.cs:line 413
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in D:\Builds\RavenDB-Stable-6.0\60039\src\Raven.Server\RavenServerStartup.cs:line 192
```

attached administrative logs

[raven@158.log](https://github.com/user-attachments/files/17145096/raven%40158.log)

**Comment by ayende** [comment]
What query do you run here?

**Comment by alex-bermishev** [comment]
[2024-09-26 8-26-26 - Node [A].zip](https://github.com/user-attachments/files/17145507/2024-09-26.8-26-26.-.Node.A.zip)

attached debug package

**Comment by alex-bermishev** [comment]
something like this. don't know how to monitor actual query in the admin panel.

timestampInterval.Start = "2024-09-02"
timestampInterval.End = "2024-09-27"


```C#
using var querySession = _documentStore.OpenAsyncSession();

var query = querySession.Query<IdxPrimaryEntry, IdxPrimary>()
    .Where( entry => entry.Timestamp >= timestampInterval.Start.Value )
    .Where( entry => entry.Timestamp <= timestampInterval.End.Value )
    .Skip( arguments.Pagination.Skip )
    .Take( arguments.Pagination.Limit );

List<EntryModel> entries = [];

var queryString = query.ToString();

var stopwatch = Stopwatch.StartNew();

var queryToExecute = query.OfType<EntryModel>();

var reader = await querySession.Advanced.StreamAsync( queryToExecute );
while ( await reader.MoveNextAsync() )
    entries.Add( reader.Current.Document );

var response = new QueryResponse
{
    Items = entries
        .Select( entry => entry.ToMqttDelivery() )
        .ToList()
};

var totalCount = await query.GetTotalResultsAsync();
response.PagedResult =
    arguments.Pagination.IsNotNull()
    ? new( totalCount.ToInt(), pagination: arguments.Pagination )
    : new( totalCount.ToInt(), pageSize: _configuration.UnspecifiedPageLimit );

Logger?.LogTrace(
    "query executed by {elapsed} {query}",
    stopwatch.Elapsed,
    queryString );
```

**Comment by alex-bermishev** [comment]
query is pretty trivial. just timestamp interval.
dot not get to LogTrace to examine actual value.

we receive this exception on production server, which is not trivial to debug in code, unfortunately

**Comment by alex-bermishev** [comment]
we are using 6.0.105

I did disk check - ok.

we will try upgrading to 6.2.0 to test this issue.
can rebuilding index help, also?

**Comment by alex-bermishev** [comment]
> What query do you run here?

```
from index 'IdxPrimary' where (Timestamp >= $p0) and (Timestamp <= $p1) and (QualifiedName in ($p2)) order by Timestamp limit $p3, $p4
```

emulated same query in development environment

**Comment by ppekrol** [comment]
We fixed similar issue in Corax indexes, fixes are available in latest 6.0 and 6.2. Could you update to this version, reset the index and check if the problem still occurs?

**Comment by alex-bermishev** [comment]
1. upgraded test environment to 6.2. copied db from production server. same exception
2. reset index IdxPrimary on test environment with 6.2. db from production server. same exception

```
{
    "ResultEtag": -201720055517376919,
    "IsStale": false,
    "IndexName": "IdxPrimary",
    "TotalResults": 0,
    "IndexTimestamp": "2024-09-26T09:32:21.3105893Z",
    "Results": [],
    "Error": "System.IndexOutOfRangeException: Index was outside the bounds of the array.\n   at Voron.Data.Lookups.Lookup`1.GetFor(Span`1 keys, Span`1 terms, Int64 missingValue)\n   at Corax.Querying.Matches.SortingMatches.SortingMatch`1.EntryComparerByLong.SortBatch(SortingMatch`1& match, LowLevelTransaction llt, PageLocator pageLocator, Span`1 batchResults, Span`1 batchTermIds, UnmanagedSpan* batchTerms, Boolean descending) in /_/62001/src/Corax/Querying/Matches/SortingMatches/SortingMatch.Comparers.cs:line 352\n   at Corax.Querying.Matches.SortingMatches.SortingMatch`1.SortResults[TEntryComparer](SortingMatch`1& match, Span`1 batchResults) in /_/62001/src/Corax/Querying/Matches/SortingMatches/SortingMatch.cs:line 575\n   at Corax.Querying.Matches.SortingMatches.SortingMatch`1.SortUsingIndex[TEntryComparer,TDirection](SortingMatch`1& match, Span`1 allMatches) in /_/62001/src/Corax/Querying/Matches/SortingMatches/SortingMatch.cs:line 417\n   at Corax.Querying.Matches.SortingMatches.SortingMatch`1.Fill[TEntryComparer,TDirection](SortingMatch`1& match, Span`1 matches) in /_/62001/src/Corax/Querying/Matches/SortingMatches/SortingMatch.cs:line 180\n   at Corax.Querying.Matches.SortingMatches.SortingMatch.StaticFunctionCache`1.<.cctor>g__FillFunc1_1(SortingMatch& match, Span`1 matches) in /_/62001/src/Corax/Querying/Matches/SortingMatches/SortingMatch.Erasure.cs:line 82\n   at Raven.Server.Documents.Indexes.Persistence.Corax.CoraxIndexReadOperation.QueryInternal[THighlighting,TQueryFilter,THasProjection,TDistinct](IndexQueryServerSide query, QueryTimingsScope queryTimings, FieldsToFetch fieldsToFetch, Reference`1 totalResults, Reference`1 skippedResults, Reference`1 scannedDocuments, IQueryResultRetriever retriever, DocumentsOperationContext documentsContext, Func`2 getSpatialField, CancellationToken token)+MoveNext()\n   at Raven.Server.Utils.Enumerators.PulsedTransactionEnumerator`2.MoveNext() in /_/62001/src/Raven.Server/Utils/Enumerators/PulsedTransactionEnumerator.cs:line 46\n   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, QueryOperationContext queryContext, Boolean pulseDocsReadingTransaction, OperationCancelToken token)"
}
```

**Comment by ppekrol** [comment]
Is there a possibility for you to send us (support@ravendb.net) export of that database so we can check what is going on exactly?
Meanwhile, I think that the issue is related to the Corax search engine, could you switch that index to the Lucene search engine?

**Comment by alex-bermishev** [comment]
switching database search engine to lucene did help.
thanks a lot!

let me check if there is a possibility to share database with you.

**Comment by arekpalinski** [comment]
The fix for Corax is here: https://github.com/ravendb/ravendb/pull/19360
